### ISSUE TITLE
4.50 Needs PopID Filter

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#10]
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L3167-L3203

When filtering out the different Populations, the code uses pop.LOTH = 1, however that includes populations 94,95,96
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSAReferenceTables.sql#L217-L219

These are not included in the list of population types in v1.2.2 of the spec:
![image](https://user-images.githubusercontent.com/44095973/46973420-685a3880-d07e-11e8-99f6-d105fd9858b9.png)

A filter like:

```{sql}
where lh.ESDays > 0
	and pop.LOTH = 1
and (lh.SystemPath in (1,3,5,7,9,10,12) or pop.SystemPath is null)
AND pop.id NOT IN (94,95,96)
```
should work

**Comment by MollyMcEvilley** [comment]
The code is okay here; unfortunately, the list of populations in the specs was truncated...
