### ISSUE TITLE
Inconsistency between HoHAdult and Age in tmp_person

### ISSUE THREAD

**Issue by nathanandrade74** [abtassociates/LSASampleCode#100]
FlagID 331 is what tipped me off to this. In section 4.12 the sample code sets HoHAdult based on the max AgeGroup (if the person ever served as an adult) but when we set the Age field we look for the min AgeGroup. If a person has two enrollments during the reporting period, one at age 17 and one at age 18, then this could lead to an inconsistency where someone is given an Age <= 17 but HoHAdult =  1. This could then cause results that should not happen, such as a record in LSAPerson with Age = 17 but VetStatus != -1.

**Comment by MollyMcEvilley** [comment]
Age = 17 and VetStatus <> -1 in LSAPerson should not generate an error -- the whole reason age has to be calculated over and over and over and over is to capture people who are served at both 17 and 18.

**Comment by AzimShivji-Abt** [comment]
That's not what the flag is saying. Flag 331 is saying that UnduplicatedAdult1 **should** be counting people with at least one active enrollment during the report period where the age was 18+ (i.e., including those people who were 17 in their earliest enrollment, but had a subsequent enrollment during the report period as an adult). Flag 331 is flagging cases where UnduplicatedAdult1 incorrectly **excluded** those 17-year-old people who subsequently had an enrollment as an adult.

**Comment by MollyMcEvilley** [comment]
Note to self/reference for 331:
unduplicatedadult1<all_vet_univ   & unduplicatedadult1=all_age_over17
--
