### ISSUE TITLE
4.21 - Households that switch between HoHs over time in different project types not filtered 

### ISSUE THREAD

**Issue by ericwilka** [abtassociates/LSASampleCode#101]
When setting HoHEST, HoHRRH, and HoHPSH we're only checking that a the person in active enrollment was served in active household as a HoH, and that the active Enrollment project type was in the EST/RRH/PSH category.  the sample code doesn't check that the corresponding record in active Household was also for the EST/RRH/PSH types.

**Comment by eanders** [comment]
We believe this may be the root cause of QC Error 283.
