### ISSUE TITLE
QC Error 183

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#104]
We are receiving a bunch of 183 errors, "The LSAHousehold field TotalHomelessDays cannot be lower than Other3917Days. The following row in your LSAHousehold file violates that rule."  In trying to track this down, it appears that step 4.35 sets Other3917Days to the difference of the DateToStreetESSH and the EntryDate.  Then it adds 
```
(select count(distinct st.sysDate)
    from sys_Time st
    where st.sysStatus = 7
    and st.HoHID = lhh.HoHID and st.HHType = lhh.HHType)
```
to whatever Other3917Days was set in the first step.  

When it calculates TotalHomelessDays, it is strictly the count of days from:
```
(select count(distinct st.sysDate)
    from sys_Time st
    where st.sysStatus in (3,4,5,6,7)
    and st.HoHID = lhh.HoHID and st.HHType = lhh.HHType)
```

Wouldn't this make Other3917Days larger than TotalHomelessDays in the situation where the enrollment start for a client only enrolled in project type "Other (7)" has a DateToStreetESSH before the EntryDate?  

Should time between DateToStreetESSH and EntryDate also be included in TotalHomelessDays?

**Comment by jbloescw** [comment]
That's what I was referencing in my #93.  I didn't put an error marker on that one but we noticed that also.
