### ISSUE TITLE
RelationshipToHoH3 is always zero (QC Error 214)

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#105]
All CoCs are coming through with a RelationshipToHoH3 = 0.  The logic for calculating RelationshipToHoH1 and RelationshipToHoH3 seem somewhat different.
```
RelationshipToHoH3 = (select count(distinct n.EnrollmentID)
      from dq_Enrollment n
      where  (n.RelationshipToHoH not in (1,2,3,4,5) or n.RelationshipToHoH is null))
```
```
RelationshipToHoH1 = (select count(distinct n.EnrollmentID)
      from tmp_Person lp
      inner join active_Enrollment n on n.PersonalID = lp.PersonalID
      where lp.ReportID = rpt.ReportID
        --CHANGE 9/28/2018 add parentheses
        and (n.RelationshipToHoH not in (1,2,3,4,5)
          or n.RelationshipToHoH is null))
```
And as far as we can tell, something in 4.70 is preventing RelationshipToHoH = 99 from being included in dq_Enrollment.  active_Enrollment does include some RelationshipToHoH = 99.

**Comment by ericwilka** [comment]
I think this error is just a natural result of transforming households with > 1 HoH and setting clients in active_enrollment relationship to 99, but that value would never appear in the raw data.  The committed change would stop checking the condition mentioned in the specs: Active_Enrollment.RelationshipToHoH NOT BETWEEN 1 AND 5.  

This will clear validation errors, but the change seems more about clearing validation than correcting an error.
