### ISSUE TITLE
Error 19696 (Unsure if the problem is code or flag)

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#108]
Error 19696 (and others like it) are popping up on a lot of ES/SH/TH programs saying numbers don't equal.
As I understand the flag, it seems to be comparing the sum of results of project IDs in section 4.65 that have project IDs to the sum of results of the 2nd half of the code in section 4.66 (universe 16).
The problem is that in 4.65, counts are added to the total via the rrhpsh join but in 4.66, universe 16, it is excluded.
If the flag is comparing ES/SH/TH numbers, it will never be satisfied if one section gets to include the rrhpsh numbers but the other section doesn't.  

Am I wrong or misunderstanding something; or does this seem a bit funky?
Please advise.

**Comment by jbloescw** [comment]
I should specify/clarify that the flag is looking at ES/SH/TH and is unable to extract just ES/SH/TH programs from 4.65 to compare to 4.66.  Hope that helps.

**Comment by jbloescw** [comment]
This is still causing a problem and I'm looking for an official update to notify customers about.
There may be more flags associated to the "master flag" but these are the ones that are popping up for us:
19694
19697
19698
19699
19704
19705
19706

I ran each join type (EST, RRH, BN) by itself for both 4.65 and 4.66 and numbers match when it's just EST and BN.  But when you add RRH in 4.65 to the mix, the numbers do in fact spike for that section (4.65) thus setting off those flags.

Something is wrong with either the flag or the code.

**Comment by MollyMcEvilley** [comment]
So does it seem from the values you're seeing in the QC reports that the sum of project-level counts from 4.65 that is being compared to the EST project type counts in 4.66 includes RRH and PSH bednights?  I would have guessed that the QC query joined to lsa_Project so that it was possible to include only ES, SH, and TH projects / exclude RRH/PSH projects?
