### ISSUE TITLE
4.36 RRH Housed Days Sample code does not match specs QC flag 169

### ISSUE THREAD

**Issue by bcarverwellsky** [abtassociates/LSASampleCode#109]
4.36 LSA RRH Housed Days issue 
QC Flag 169
The sample code did not match the specs

Page 124 of the LSA Specifications RRHHousedDays must be -1 if RRHMoveIn not in (1,2)

In the sample code it was checking RRHStatus = 0 to set RRHHousedDays to be -1

Current code 

update lhh
set lhh.RRHHousedDays = -1
from tmp_Household lhh
where lhh.RRHHousedDays = 0 and lhh.RRHStatus = 0

Should be 

update lhh
set lhh.RRHHousedDays = -1
from tmp_Household lhh
where lhh.RRHHousedDays = 0 and lhh.RRHMoveIn not in (1, 2)

QC Flag 169 :
The LSAHousehold field RRHHousedDays, which reports days housed in RRH, must equal -1 (not applicable) if the household was not placed, either during or before the report period (as reported in RRHMoveIn), or if the household was not served in RRH during the report period (as reported in RRHStatus). The following row in your LSAHousehold file violates that rule.

**Comment by bcarverwellsky** [comment]
QC Flag 169

The LSAHousehold field RRHHousedDays, which reports days housed in RRH, must equal -1 (not applicable) if the household was not placed, either during or before the report period (as reported in RRHMoveIn), or if the household was not served in RRH during the report period (as reported in RRHStatus). The following row in your LSAHousehold file violates that rule.


Issue we ran into

A client has entered a RRH program during the report time frame but does not have a move in date yet. (Waiting for a unit to open up.)

In the sample code logic that results in the following 
RRHHousedDays = 0
RRHStatus = 21 (Entered during report period; active on last day)
RRHMoveIn = 0 (Not Placed)

The RRHHousedDays should be -1 (Not Applicable) and that is what is getting flagged but the sample code logic does not set it to -1 for this case.

**Comment by MollyMcEvilley** [comment]
There are flags being triggered by data that is consistent with the business logic for setting values for **RRHHousedDays** (QC Flag #169), **ESDays**  (QC Flag #141) and **THDays** (QC Flag #143), as it is defined in section 4.36 of the specs.   Later sections of the specs are inconsistent with section 4.36, but they aren’t related to setting the values. 

Julia is working with the data review team the identify flags that are generating false positives (and, ideally, to have them excluded from the QC reports).
