### ISSUE TITLE
4.50 System Path should always be -1

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#11]
pg 77 of the v1.2.2 of the specs states (section 4.50 "Population, HHType and SystemPath") states:

> Generate rows 1-9 for each of the following household types and populations without regard to the value of tmp_Household.SystemPath. The value of LSACalculated.SystemPath should be -1 for these records

However the code does enforce that in any of the inserts, e.g:
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L3167-L3203
It is doing a `Coalesce(pop.systempath, -1)` on it. Since the only filter on pop is to make sure that LOTH = 1 this will include records where systemPath = 1-12, and does not ensure that LSACalculated.SystemPath = -1 in each case.

**Comment by MollyMcEvilley** [comment]
As we discussed on 10/18/2018, this statement combines the insert of report row 1 for all households regardless of system path (specs section 4.50) and for the system path values required by the specs in section 4.51. (As do subsequent statements in the combined section 4.50-4.51 of the sample code.)
