### ISSUE TITLE
4.63 and 4.64 Project-Level vs Project Type counts of people (flag ID 16571)

### ISSUE THREAD

**Issue by MollyMcEvilley** [abtassociates/LSASampleCode#110]
Placeholder... If served in two different populations in the same project type -- AO 18-21 and AC 22-24 Parenting Youth -- project level counts are pulling counts from specific enrollments with associated HHAdultAge, project type counts are pulling from the more broadly applicable tmp_Person for HHAdultAge, where there can only be a single value.  In one instance, this results in Project-Type count for AC Parenting Youth 18-21.   This isn't really a bug, but could maybe be improved with additional thought...

**Comment by MollyMcEvilley** [comment]
Notes:  Why might LSAPerson/LSAHousehold # be lower than LSACalculated #?

1)	Comparisons of people counts in ES/SH/TH (between LSAPerson and LSACalculated)
2)	Comparisons of household counts in ES/SH/TH (between LSAHousehold and LSACalculated)
3)	Comparisons of people counts in RRH (between LSAPerson and LSACalculated)
4)	Comparisons of household counts in RRH (between LSAHousehold and LSACalculated)
5)	Comparisons of people counts in PSH (between LSAPerson and LSACalculated)
6)	Comparisons of household counts in PSH (between LSAHousehold and LSACalculated)

For all of these comparisons, the LSAPerson or LSAHousehold number should never be lower than the LSACalculated number. But the LSAPerson or LSAHousehold number can be greater than the LSACalculated number for…
•	The comparisons highlighted in yellow (1, 2, 4, and 6) because of one reason:
a)	The difference in the definitions of “active during the report period.” LSAPerson/LSAHousehold includes people/heads of household who exited on the first day of the report period and never returned (in that same household type and project group). LSACalculated does not.
•	The comparisons highlighted in green (3 and 5) because of two reasons:
a)	The difference in the definitions of “active during the report period” (as described above).
b)	The difference between the broader enrolled population and the narrower placed population. The LSAPerson number in this comparison includes enrollees who were not housed. The LSACalculated number does not.

**Comment by TanyaPieterse** [comment]
In Step 4.64 in both insert statements; I changed the below line in inner join ref_Populations and it removed my Flags that related to these comparisons (changed an.AgeGroup to lp.Age - that is how I interpreted Azim's email explanation).

and (an.AgeGroup = pop.Age or pop.Age is null)
Changed To:
and (lp.Age = pop.Age or pop.Age is null)

Thanks!
