### ISSUE TITLE
Are the specs and sample code clear that enrollment data from after ReportEnd are not relevant?

### ISSUE THREAD

**Issue by MollyMcEvilley** [abtassociates/LSASampleCode#112]
Check this per Julia.

**Comment by MollyMcEvilley** [comment]
MoveInDate was the only value I could find where data after ReportEnd would have been inserted into the interim tables.

**Comment by MollyMcEvilley** [comment]
MoveInDate was the only value I could find where the sample code would have used data from after ReportEnd.

**Comment by michelleogburn** [comment]
@MollyMcEvilley 

A related question, (sorry, I can't find exactly where in the code this is...)

A recent change was made to:

`is replaced with 
foreach ( 
[HoH project data collection stage] with [information date] <= [report end date] 
sorted by [information date] ASC 
) `


I wonder if you meant to write:
[HoH project data collection stage] with **[move-in date]** <= [report end date] 
sorted by [information date] ASC 
)
