### ISSUE TITLE
Excluding all clients

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#116]
The recent change that added `and hn.EnrollmentID is null` is now excluding all clients.
Perhaps the closing parenthesis should come after line 919?

https://github.com/HMIS/LSASampleCode/blob/518fb5d8795060e2ec1a240512d628bc324d70b6/LSASampleCode.sql#L919

**Comment by eanders** [comment]
On second thought.  Why would there ever be a missing EnrollmentID in `hmis_Enrollment`?  That's a required field and it's an inner join, so every row should have that.

**Comment by MollyMcEvilley** [comment]
This was a dumb one on my part... sorry about that.
