### ISSUE TITLE
4.50 should not reference/filter on tmp_household.SystemPath

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#12]
pg 77 of the v1.2.2 of the specs states (section 4.50 "Population, HHType and SystemPath") states:

> Generate rows 1-9 for each of the following household types and populations without regard to the value of tmp_Household.SystemPath. The value of LSACalculated.SystemPath should be -1 for these records

However the code references tmp_Household.System path in most of the filter conditions, e.g
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L3167-L3203

**Comment by MollyMcEvilley** [comment]
INSERT statement in code combines sections 4.50 and 4.51 of the specs.  (See issue #10)
