### ISSUE TITLE
Discrepancy between RRHPreMoveInDays and RRHPSHPreMoveInDays

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#121]
Hello,

Example:
Client's Project Dates in RRH:
- EntryDate 2017-09-20	
- MoveInDate 2017-12-29	
- ExitDate 2018-03-13

RRHPreMoveInDays:
Step 4.30 that counts Dates for Client in RRH prior to MoveIn
joins ref_Calendar where cal.theDate <= coalesce(dateadd(dd, -1, an.MoveInDate), dateadd(dd, -1, an.ExitDate), @StopDate)
Calculates to 99 Days

RRHPSHPreMoveInDays:
Step 4.34 that finds the Dates for LSA_sys_Time.sysStatus = 5 or 6
joins ref_Calendar where cal.theDate < coalesce(sn.MoveInDate, sn.ExitDate, @StopDate)
Then in Step 4.36 RRHPSHPreMoveInDays is calculated by looking at the above Dates
Calculates to 100 days

Which one is correct?  Since the Client is only in RRH, and not PSH, RRHPreMoveInDays should equal RRHPSHPreMoveInDays.

Thanks!

**Comment by MollyMcEvilley** [comment]
Is anyone else encountering instances where RRHPSHPreMoveInDays > RRHPreMoveInDays and PSHStatus = 0?

I changed the dates for one of the households in my database to match yours and came up with 100 days for both columns when I ran the sample code.

Unfortunately, I did find a bug in 4.34 (see issue #124) as I was combing through the criteria, but it doesn't apply to these circumstances...
