### ISSUE TITLE
4.67 -- possible missing rpt.ReportEnd date checks in sample code

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#127]
Hello @MollyMcEvilley,

My name is Thomas Brittain, I work with Michelle Ogburn and I'm attempting to fill in for her while she's on vacation.

Our developers have found a possible discrepancy between the sample code and the specifications.  Specifically, in the join logic of section 4.67.
https://github.com/HMIS/LSASampleCode/blob/fc65eca3509254bec6de58abcf7c7bac4e12e05b/LSASampleCode.sql#L4879-L4886

It looks as though these joins might be missing `est.theDate <= rpt.ReportEnd` and `rrhpsh.theDate <= rpt.ReportEnd`, as I think the additional logic is needed to meet the specifications found on page 111.

![image](https://user-images.githubusercontent.com/6241517/59283235-dbc54180-8c2f-11e9-9039-5c2d00c8fa9a.png)

![image](https://user-images.githubusercontent.com/6241517/59228160-b804eb80-8b9c-11e9-9d70-d6b5c4ae8d72.png)

**Comment by MollyMcEvilley** [comment]
Hi @Ladvien / Thomas,

Unless I'm missing something -- always a possibility -- the criteria for theDate in relationship to ReportEnd is in the next line -- it must be less than:

1. The ExitDate in active_Enrollment (which is only populated if it is prior to ReportEnd) if it exists, or 
2. ReportEnd + 1 day (which is the equivalent of <= ReportEnd

Does that address the spec requirement?
