### ISSUE TITLE
Separate config from queries

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#139]
Would it be possible to break apart the files just a bit more?  
Specifically, "3.1 Report Parameters and Metadata" which creates the report record has hard-coded sample data. If that were its own file, it would be very helpful for us.  

Similarly, it would be helpful to have "4.1 Get Project Records for Export" in its own file since that will need to be replaced for LSAScope = 2.

**Comment by MollyMcEvilley** [comment]
This is done -- thanks for the suggestion!
