### ISSUE TITLE
LSA does not accept null ZIP or GeographyType, but HMIS does

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#140]
In 4.4
ProjectCoCs are brought over without regard to the not-null-ness of their fields.  Should vendors limit projects included to only those with valid ZIP and GeographyType columns, should vendors use some sane defaults, or should the LSA ignore those records with null values?

https://github.com/HMIS/LSASampleCode/blob/0cfea4e66e34d47248f71201e01ba8c30d6fddb6/4_1%20to%204_6%20PDDEs%20for%20Export.sql#L121-L122

One possible solution is to replace the above with:
```
where hcoc.DateDeleted is null
		and hcoc.CoCCode = rpt.ReportCoC
		and hcoc.ZIP is not null
		and hcoc.GeographyType is not null
```

**Comment by MollyMcEvilley** [comment]
The HDX will alert users to missing values for GeographyType and ZIP -- updated table to allow NULL values.
