### ISSUE TITLE
HDX validation code

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#142]
Hi earlier in this process it was said that we would be receiving the HMIS sample files, the LSA sample export, and a set of validations we could run against our LSA results to ensure that it will pass validation when uploaded to the HDX.  The first two were released on 4/24/2020.  Is there still a plan to release the validations? If so, what is that timeline?

**Comment by cwanska** [comment]
The AHAR team has released the full list of flags. We will not be able to provide anything further for this year but can re-look at what can be an offering in future years to help with transparency.
