### ISSUE TITLE
Sample HMIS Export file missing files

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#143]
The recently released sample HMIS CSV file is missing four files.  User.csv, Assessment.csv, 
AssessmentQuestions.csv, and AssessmentResults.csv.  

I've attached blank files here.
[missing_files.zip](https://github.com/HMIS/LSASampleCode/files/4545776/missing_files.zip)

**Comment by dburgstrom** [comment]
None of this information is used in the LSA sample code, so these .csv's are blank. They were created as part of the standard HMIS export but if it would be helpful not to include the blank files, they can be removed.

**Comment by eanders** [comment]
It would be great *to* include them, even though they are not used in the LSA.  They were not included in the sample HMIS export provided here:

Location: site "HMIS Vendors" > Resources > Dummy Data Sets > [FY 2020 HMIS CSV Data 2020_04_24.zip](https://sakai.lampschools.org/access/content/group/44c5c653-66cd-47c3-9c06-44d89ed087ff/Dummy%20Data%20Sets/FY%202020%20HMIS%20CSV%20Data%202020_04_24.zip)

Thank you!

**Comment by dburgstrom** [comment]
Ah, beg your pardon. I thought we had already uploaded an updated version of the file that had them. That should be posted later today.

**Comment by eanders** [comment]
These are now included.  Thank you!
