### ISSUE TITLE
Project dates end up in odd formats

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#147]
Selecting using the format method appears to get very confused.  
For dates, they are ending up as `2012-00-01` instead of 2012-10-01.  It appears this isn't necessary at all for dates.  
https://github.com/HMIS/LSASampleCode/blob/0cfea4e66e34d47248f71201e01ba8c30d6fddb6/4_1%20to%204_6%20PDDEs%20for%20Export.sql#L26-L27

```
, convert(date, hp.OperatingStartDate, 23)
, case when hp.OperatingEndDate is not null then convert(date, hp.OperatingEndDate, 23) else null end
```
Correctly returns those two columns as they were formatted .

The formatting of DateCreated and DateUpdated is returning odd timestamps like: `2020-00-13 12:00:00`. 

I have not managed to find a conversion to get that correct yet.

**Comment by eanders** [comment]
Upon further investigation, one possible solution is to use `format(hp.OperatingStartDate, 'yyyy-MM-dd')` and `format(hf.DateCreated, 'yyyy-MM-dd hh:mm:ss')`.  The months need to be capital Ms.

**Comment by MollyMcEvilley** [comment]
Thank you!
