### ISSUE TITLE
Test Data - Inventory designated beds issues

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#148]
InventoryID = 4083317, 
- HouseholdType = 4 (Households with only Children)
- Designated beds for this Inventory include CHVetBeds, VetBed, CHBeds
- For HouseholdType 4, we have no way to add this type of designated beds to the inventory.

InventoryID = 4083318,
- HouseholdType = 3 (Households with at least one adult and one child)
- Designated beds for this Inventory include CHYouthBedInventory
- For HouseholdType 3, we have no way to add this type of designated bed to the inventory.

**Comment by michelleogburn** [comment]
@MollyMcEvilley 
Further problems with the test data... except for ProjectID=441, none of the other projects are permanent, and so couldn't have any CH dedicated beds, of any variety. 

And another noticing.

ProjectID = 240 (APR - Emergency Shelter/SSO)

- Project Type = 1 (Emergency Shelter)
- No values for [Availability] or [ESBedType] values
- Our system does not allow for creating a bed inventory for ES projects with these fields


And there is an additional inventory (InventoryID = 4717088), where HouseholdType = 4 and includes designated beds that are not appropriate for Households with Only Children.

**Comment by dburgstrom** [comment]
Thank you for pointing these issues out. They should be corrected on the test kit and sample LSA output updated on the vendor hub this afternoon.

**Comment by michelleogburn** [comment]
Problem corrected in latest test kit.
