### ISSUE TITLE
LSAScope for HUD submission

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#149]
I'm probably reading this wrong, but I think 3.1 (page 14) should indicate "LSAScope must be 1 for submissions to HUD."  Currently it indicates 2.

![Screen Shot 2020-04-30 at 5 56 52 PM](https://user-images.githubusercontent.com/1346876/80763284-30a1cd00-8b0c-11ea-905d-e06116018594.png)

The code correctly specifies 1
https://github.com/HMIS/LSASampleCode/blob/388c8c05f7a479754e89f147596b8d473b9fa7fe/3_1%20LSAReport%20Parameters%20and%20Vendor%20Info%20Hardcoded%20Sample%20Data.sql#L18-L40

**Comment by MollyMcEvilley** [comment]
You are reading it correctly -- I was writing it wrong.  :)
