### ISSUE TITLE
4.53 Insert for Report rows 12,13 should be seperate from 14

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#15]
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L3509-L3546

In the above the code is inserting for report rows 12, 13, and 14. In the select statement it is checking that `RRHMoveIn in (1,2)` to get report rows of 14. Because the where clause filters on RRHMoveIn > 0 there is no case that won't result in a report row of 14. Furthermore the specs require that for report rows 12, 13 the value of RRHMoveIn = 0.

![image](https://user-images.githubusercontent.com/44095973/47029308-75cbfd00-d128-11e8-8db5-cb417f35eb4e.png)

 The insert for 12, and 13 should be separate from report row 14. Or the filter needs to be changed and 14 moved into the insert with report rows 15 and 16.

You can find more evidence for this in that the TestKit Upload Data (v1.4.3) has no records in LSACalculated.csv for report rows 12 and 13.

**Comment by tcalder** [comment]
removing the filter might work better. That way the logic for report row 14 doesn't need to be moved into it's own insert.

EDIT:
Doing that would require some changes to the way the case statement works in the select, but still might be the easiest solution.

**Comment by MollyMcEvilley** [comment]
Changed 'where lh.RRHMoveIn > 0' to 'where lh.RRHStatus > 2.'  I think the case statement can stand as is -

- **when lh.RRHMoveIn in (1,2) then 14** = all households placed in PH,  
- **when RRHStatus in (12,22) then 12** = all exited households not placed in PH
- **else 13 end** = all other RRH clients / all active households not placed in PH
