### ISSUE TITLE
Spec Record Selection lists ProjectType 3 twice

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#150]
In 3.3 (page 19), this list appears to have a duplicate 3.
 
![Screen Shot 2020-04-30 at 6 25 39 PM](https://user-images.githubusercontent.com/1346876/80765088-241f7380-8b10-11ea-8353-9ecd9fcc834a.png)

**Comment by MollyMcEvilley** [comment]
Corrected in the specs.
