### ISSUE TITLE
lsa_Exit won't accept null HHVet, but tlsa_Exit contains some

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#151]
Apologies in advance for a somewhat incomplete set of information, but I'm somewhat stumped by 7.8 hitting some null HHVet columns.

When running the sample code against production data I'm hitting an issue where 7.8 won't run because HHVet contains null values.  It appears that 7.4 should be populating this, but perhaps there is some combination of the inner joins that is preventing the update in some situations.  I've attached the results of the 7.8 select below and the two rows in tlsa_Exit.  Maybe a particular system path or cohort is the issue?  Any direction you can provide (@MollyMcEvilley I assume) would be very helpful.

https://github.com/HMIS/LSASampleCode/blob/388c8c05f7a479754e89f147596b8d473b9fa7fe/7_1%20to%207_8%20LSAExit.sql#L109-L154

![Screen Shot 2020-05-04 at 9 09 04 AM](https://user-images.githubusercontent.com/1346876/80969039-faec3500-8de6-11ea-8135-b733dd97202d.png)

![Screen Shot 2020-05-04 at 9 14 58 AM](https://user-images.githubusercontent.com/1346876/80969631-ee1c1100-8de7-11ea-8c08-707ee9094850.png)

Thank you!

**Comment by MollyMcEvilley** [comment]
I can't reproduce this one -- is anyone else experiencing this issue?

**Comment by eanders** [comment]
@MollyMcEvilley, not sure if this is helpful, or quite enough data, but here are the source records that cause us to get into this situation.  They have been de-identified, but are mostly un-touched.
[issue 151 data.zip](https://github.com/HMIS/LSASampleCode/files/4595591/issue.151.data.zip)

**Comment by dburgstrom** [comment]
Imported the data, thank you. It appears that the values are not being created because these clients do not have an entry into tlsa_enrollment. It appears that they don't have an entry into tlsa_enrollment because their exit dates are prior to their intake dates (screenshot of tlsa_hhid):
![image](https://user-images.githubusercontent.com/64597095/81345638-ce564880-9086-11ea-8451-7eb5bea3d0c5.png)
Thanks

**Comment by dburgstrom** [comment]
Further explanation: which means that this restriction at the end of section 3.4 is not met:
"and hn.EntryDate between hhid.EntryDate and isnull(hhid.ExitDate, rpt.ReportEnd)"

**Comment by eanders** [comment]
So, if I'm following, the first enrollment has an exit before 10/1/2019, so it should be excluded in 3.4 and subsequently when added to tlsa_Exit.  

I'm unclear on the second enrollment that doesn't have an exit record, where did the Exit Date value of 2018-06-30 come from?  Oh!  It came from the OperatingEndDate on the project.  So, there definitely are data quality issues with the second enrollment, but the first should probably be excluded somewhere in the calculations or selection for lsa_Exit?

Actually both OperatingEndDates are too old. 

![Screen Shot 2020-05-07 at 5 26 10 PM](https://user-images.githubusercontent.com/1346876/81346250-f98d6780-9087-11ea-9ba8-059d6d65b3bb.png)

**Comment by eanders** [comment]
Maybe 7.2 should inner join tlsa_HHID and tlsa_Enrollment to avoid selecting items that don't qualify?  (Obviously fixing the source data is necessary, but we can't always control that.)

**Comment by eanders** [comment]
This appears fixed.  Thanks @MollyMcEvilley.  Closing
