### ISSUE TITLE
5.10 Set CHTime and CHTimeStatus Setting Value to 99

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#152]
https://github.com/HMIS/LSASampleCode/blob/388c8c05f7a479754e89f147596b8d473b9fa7fe/5_1%20to%205_19%20LSAPerson.sql#L355-L412

![image](https://user-images.githubusercontent.com/44415627/81008705-fb052880-8e18-11ea-88d8-f25253132448.png)

There are 3 update statements to set tlsa_Person.CHTimeStatus = 99
1. It looks like the first statement addresses the first 3 bullet points.  No problem here.
2. The second statement seems to attempt to 6th and 7th bullet point due to the project type NOT IN (1,8) but code vs specs don't seem to align.  That and I think there are some missing parens in the And Or portions in the where clause.
3. The last statement seems to cover all the bullet points making me wonder the necessity of the first 2 statements.

Is this the intention or am I misunderstanding something?

**Comment by MollyMcEvilley** [comment]
Thank you!  Deleted the extraneous update statements.
