### ISSUE TITLE
Extraneous comma

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#153]
This is super tiny, but I keep noticing it.
Throughout the document there are lists of project types: `(1,2,8,),`  The extra comma within the parenthesis does not need to be there.

![Screen Shot 2020-05-05 at 10 20 11 AM](https://user-images.githubusercontent.com/1346876/81076783-1411e600-8eba-11ea-8db2-b400cfc7b2aa.png)

**Comment by MollyMcEvilley** [comment]
Corrected in the specs.  Thank you!
