### ISSUE TITLE
Data set data issues: HealthandDV.csv

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#157]
Looking at the data set whose name ends in 2020_4_30, our validator is finding HealthandDV.csv WhenOccurred errors in this format--[hundreds of clients] admission form dated [mm/dd/yyyy] is missing an answer to "When experience occurred" within the Domestic Violence section in [project] 
Is data inadvertently missing in that field? Thanks!

**Comment by dburgstrom** [comment]
Hi Michelle, thank you for telling us about this. We have looked into the cause and it seems to be an adaptation in our system previously needed for export to RHY and VA repositories. The data itself was not actually missing for that field. We have removed that adjustment which should fix this issue when we upload the updated file this week.

Thanks.

**Comment by MichelleNevius** [comment]
Thanks, David. I appreciate it.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.
