### ISSUE TITLE
Data set question on Enrollment.csv, regarding RunawayYouth

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#158]
Using the 2020_4_30 data set, our validator is producing an error on this record: In Enrollment.csv, in EnrollmentID176926, which relates to PersonalID 70094, ProjectID 960, EntryDate 11/18/2014, our validator is saying RunawayYouth is blank and that’s not allowed. Could you examine this on your end? I've located the page in the specs: 
https://files.hudexchange.info/resources/documents/HMIS-Data-Standards-Manual.pdf p.168
R2 Field 2, response 1
Can you tell: Is my validator not handling this correctly, and a blank value is allowed for this record?
Thanks!

**Comment by bayboos** [comment]
Hello David, hi Michelle.

The specification is clear: RunawayYouth is not allowed to be null when EligibleForRHY is 1. In the case of this enrollment record, EligibleForRHY is 1, and that means our validator works perfectly fine. It's a clear data issue in the Sample Kit Data file.

**Comment by dburgstrom** [comment]
Agreed. We are working to update this in our export and you should not see the issue in the updated test kit file.
Thanks.

**Comment by MichelleNevius** [comment]
This seems solved in the 5.8 test kit (at least i didn't hit up against an error here), so I'm going to to go ahead and close this one.
