### ISSUE TITLE
4.52 Case statement for report rows 10,11 not same as specs

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#16]
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L3471-L3505

Code is setting 10 to those rows where PSHStatus in (12,22), however specs say report row 10 should be any row as long as PSHMoveIn = 1 and that report row 11 should be those with a PSHStatus in (11,21)

From the specs:
![image](https://user-images.githubusercontent.com/44095973/47033120-3eae1980-d131-11e8-8621-6bb4d3962ee2.png)

It seems like 10 should be a separate insert from 11, since data pertinent to report row 11 is also pertinent to report row 10.

**Comment by MollyMcEvilley** [comment]
![image](https://user-images.githubusercontent.com/6156815/47373691-56017f80-d6ba-11e8-88d0-20a2abf063bc.png)

**Comment by MollyMcEvilley** [comment]
This is also being corrected in the specs to match the LSA Dictionary (and code).  Row 10 should be the number of days housed in PSH for households who exited during the report period; Row 11 is for those still active at ReportEnd.
