### ISSUE TITLE
Data Set issue in Project.csv re: TrackingMethod

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#161]
I am getting a validation error in the data set's uploaded data for 4 rows in project.csv that says "Project.csv
	Row #3/Row #4/Row#5/Row#7
		TrackingMethod
			Field's value is not empty while it should be"--in other words, it is complaining when the TrackingMethod value is not empty for programs that are not Emergency Shelters. Is this something you would consider changing in your data set, so that we don't need to manually correct for this as we import? Thanks for your consideration.

**Comment by dburgstrom** [comment]
Hi Michelle, yes, we can change that and should have the updated test kit out later today.

Thanks

**Comment by MichelleNevius** [comment]
Closing, because issue #164 references this as still being an issue for ProjectID 942, but resolved for the other programs. Thanks.
