### ISSUE TITLE
5/8 Test Kit contains blank OperatingStartDate

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#162]
The HMIS CSV spec does not allow null in Project OperatingStartDate.  ProjectID 942 in the sample data set is missing this date.
![Screen Shot 2020-05-11 at 9 26 01 AM](https://user-images.githubusercontent.com/1346876/81566858-7743c280-9369-11ea-99ec-e18f4abf6c86.png)

**Comment by MichelleNevius** [comment]
Thanks for reporting that, Elliot. I'm about to report another 2 issues with that same record, as per our software's import validator.

**Comment by dburgstrom** [comment]
Yes, thank you. I will fix that with the next update.

**Comment by eanders** [comment]
Fixed
