### ISSUE TITLE
User.csv file in sample data set does not contain DateUpdated data

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#163]
The HMIS CSV spec does not allow nulls in the DateUpdated column (for any table) but the User.csv file is missing this data.
![Screen Shot 2020-05-11 at 9 26 42 AM](https://user-images.githubusercontent.com/1346876/81566979-a5290700-9369-11ea-8a82-d21a00805971.png)

**Comment by dburgstrom** [comment]
Thank you for noticing this. This should be fixed and I'll upload a new version Thur. AM at the latest, maybe sooner.

**Comment by eanders** [comment]
Fixed
