### ISSUE TITLE
5/8 Test Kit Project.csv, contains  OperatingStartDate, TrackingMethod and OrganizationID error

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#164]
Hi, for the same record that is pointed out in issue #162 with blank operating start date, my validator is finding TrackingMethod is not empty and should be, and that OrganizationID Field's value '-1' does not have a matching entry in Organization.csv.

**Comment by dburgstrom** [comment]
Thank you for reporting this. I will have this corrected for the next test kit upload.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.
