### ISSUE TITLE
5/8 Test kit Inventory.csv, error on InventoryStartDate and InventoryEndDate formats

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#165]
Hi, These records have the error '2017-08-01 00:00:00' is not a valid value for InventoryStartDate. InventoryStartDate must contain a date in the format yyyy-mm-dd. 
and '2025-08-01 00:00:00' is not a valid value for InventoryEndDate. InventoryEndDate must contain a date in the format yyyy-mm-dd.
Could you investigate, please, and if possible alter the next data set so that they are just dates, not dates and times? Thanks!

**Comment by dburgstrom** [comment]
Thank you for noticing this. I have corrected this and it will be fixed on the next upload.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.
