### ISSUE TITLE
Sample Code 5.17 Set HHAdultAge issue

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#167]
Good morning,
In sample Code 5.17 set HHAdultAge for 55, it wrote 'when min(n.ActiveAge) between 64 and 65 then 55', according to specification, it should be 'when min(n.ActiveAge) between 55 and 65 then 55'?
Thanks.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
This is confusing, but they are effectively the same thing.
The value 64 indicates _Age Group 55-64_ and the value 65 means _Age Group 65+_.
Sorry about that...

**Comment by 2008zjqc** [comment]
Hi Molly,
Thanks for your response. We are saying corresponding sample code, the 'Between' condition is incorrect when set value 55. Please double check. Thanks.
