### ISSUE TITLE
6.14 Living Situation references list value 24 instead of 25

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#169]
Section 6.14 has 2 routines that look at what specs say is:  LivingSituation in (4,5,6,7,15,25)

The code for these however is showing: hn.LivingSituation in (4,5,6,7,15,24)
Looks like 'deceased' made its way in there insead of 'Long-term care facility or nursing home'

**Comment by michelleogburn** [comment]
@MollyMcEvilley , just a reminder the spec also needs to be updated for this one.

![image-20200515-122005](https://user-images.githubusercontent.com/20728145/82961794-39eb5180-9f73-11ea-8e20-81f286b86e40.png)

![image-20200515-122005](https://user-images.githubusercontent.com/20728145/82961725-12948480-9f73-11ea-916c-0294ecb2a23c.png)

![image-20200515-122134](https://user-images.githubusercontent.com/20728145/82961843-58e9e380-9f73-11ea-878c-fd5502a9ef72.png)
