### ISSUE TITLE
6.12 and 7.6 - DateDeleted = 0 used in the insert query

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#170]
Hello

Both sections of the code mentioned in the subject line contain an insert statement into sys_TimePadded table; and in both of those the same codtition is present:

>  6.12  Get Last Inactive Date
> (...)
> insert into sys_TimePadded (HoHID, HHType, Cohort, StartDate, EndDate)
> (...)
> inner join **hmis_Services bn** on bn.EnrollmentID = hhid.EnrollmentID 
> 		and bn.DateProvided <= rpt.ReportEnd
> 		and bn.RecordType = 200 and **bn.DateDeleted = 0**

and 

> 7.6  Last Inactive Date for Exit Cohorts
> (...)
> insert into sys_TimePadded (HoHID, HHType, Cohort, StartDate, EndDate)
> (...)
> inner join **hmis_Services bn** on bn.EnrollmentID = possible.EnrollmentID 
> 		and bn.DateProvided <= cd.CohortEnd
> 		and bn.RecordType = 200 and **bn.DateDeleted = 0**
> 

In both cases, the DateDeleted field is a date (or datetime, or timestamp - depending on the implementation) field that can't be '0', but it can be 'null'. In fact in all other places in the code (counted 17 so far), the condition looks like this (just one example from 7.1 section):

> and coc.**DateDeleted is null**

Since at least some implementations do recognize a difference between '0' and 'null', and even don't allow comparisons between integers and dates - please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
That's so bad I would not have expected it to run... thanks very much for pointing it out -- I have corrected the code.
