### ISSUE TITLE
7.1 hmis_Exit is left joined, but not used

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#171]
In the only query in 7.1 section, there is a line that joins hmis_Exit table with the tlsa_HHID:

> update hhid
> 	set hhid.ExitCohort = cd.Cohort
> 	from tlsa_HHID hhid
> 	inner join lsa_Report rpt on rpt.ReportEnd >= hhid.EntryDate
> 	**left outer join hmis_Exit hx** on hx.EnrollmentID = hhid.EnrollmentID
> (...)

This join statement does nothing by itself - left outer joins don't limit the number (or content) of the returned/affected rows. The hmis_Exit table content is not used anywhere else in the query, neither for data source nor for conditional statements. The specification document also does not mention that this table is needed for anything. Looks like the only thing it does there is slowing the process down - the join statements are on the "greedy" side in terms of system resources. 

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Removed the join -- thank you.
