### ISSUE TITLE
9.1 illogical/wasteful comparison

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#172]
In the 9.1 insert query, there is a condition statement that looks like this:

> or left(c.SSN,1) >= '9'

I assume this is supposed to find SSH numbers that start with '9'; if that's the case, then it's unneccessary waste of resources since 1) system needs to convert strings into digits and 2) is looking for a condition that can never be met (no single digit can be greater than 9).

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Thanks for pointing that out!  I changed the ">= '9'" to "= '9'".
