### ISSUE TITLE
9.1 Ambiguous where clause

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#173]
The final where clause in the insert statement looks like this:

> where x.ExitDate is null or x.ExitDate >= cd3.CohortStart
>	and n.DateDeleted is null 

Without having the order of actions clearly defined, some implementations can and do resolve the "and" opeartion first and only then the result is used for the "or" operation. This will cause the the records where ExitDate is null to be always included, even when DateDeleted is not null.

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Thanks -- I added parentheses.
