### ISSUE TITLE
9.3 Unnecessary update query

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#175]
The lsa_Report.ReportDate column is of type datetime and initially populated in step 3.2 (with full date and time information). This seems obvious since the column cannot be null and thus have to be populated by the very first (and each subsequent, if any) insert statement. However the 9.3 query is updating this value, even though it already exists and there is little to no chance of it changing during the course of running the entire code. On top of that, the last update query drops the time information entirely, making this value less precise and thus the update query if not detrimental then at least redundant.

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Per the specs, the ReportDate should be set at the end.

I changed the create statement for lsa_Report to allow NULL values and removed the code to set it at the beginning of the process in 3_1 LSAReport Parameters....

**Comment by MollyMcEvilley** [comment]
3.1 used getdate() to set the value and 9.3 also uses getdate(), so I can't explain why you were seeing only a date in 9.3 but a date and a time in 3.1.
