### ISSUE TITLE
5.14 sample data issue with a couple of records in IncomeBenefits.csv

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#178]
Hi, please look at the 2 records for enrollment ID 172594. Our import validator (which counts the header row as a record/row number) finds these errors: In row 8236 the InformationDate ('2015-02-02') does not match the exit date ('2015-02-19') and in row 8237 There should be no more than one record per EnrollmentID with a DataCollectionStage of 3. The first record can be found in Row #8236.
Please let me know if you need more info. Thanks!

**Comment by dburgstrom** [comment]
Thank you. Should be fixed in latest upload.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.
