### ISSUE TITLE
5.14 sample data kit, issue with a couple of records in EmploymentEducation.csv

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#179]
Hi, our import validator has found 2 errors in this csv. The first is with EmploymentEducationID= __3otee where our validator rejects it because The InformationDate ('2015-02-02') does not match the exit date ('2015-02-19'). The second error is related, in that later in the file, in what we consider row 8531, we are told "There should be no more than one record per EnrollmentID with a DataCollectionStage of 3. The first record can be found in Row #2" . The row this is referencing has    EmploymentEducationID = 4517031__3otee and for both of these records the EnrollmentID is 172594.

**Comment by dburgstrom** [comment]
Thank you. Should be fixed in latest upload.

**Comment by MichelleNevius** [comment]
FY 2020 HMIS CSV Data 2020_05_14 - PM was imported into our database with no validation errors. I'm closing this issue.
