### ISSUE TITLE
4_1 Get Project Records for Export.sql - code issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#180]
This section of the code is missing a critical restriction: `hp.ProjectID = coc.ProjectID`

https://github.com/HMIS/LSASampleCode/blob/5dc9565cef55bcce71552c68884d98168feab0d0/4_1%20Get%20Project%20Records%20for%20Export.sql#L19-L46

![image-20200508-104936](https://user-images.githubusercontent.com/20728145/82015539-d50b2f80-9633-11ea-989d-9ffba9218db2.png)

**Comment by MollyMcEvilley** [comment]
Yikes -- not a minor detail.
