### ISSUE TITLE
Sample Test Results Assumption Question

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#183]
Are the sample results files being validated against the sample data set with something other than the sample code?

I wanted to confirm some assumptions about the test kit.  Apologies in advance for a long and somewhat pedantic question.

Generally tests are written to confirm that code is functioning as expected.  Take the following example:

Data:
Client A - Enrollment A 1/1/2020 - 2/1/2020
Client A - Enrollment B 1/5/2020 - 2/1/2020
Client B - Enrollment C 1/1/2020 - 2/1/2020

Tests:
Test for count of enrollments open on 1/10/2020 should return 3
Test for counts of clients enrolled on 1/1/2020 should return 2

In this scenario, the tests would be written without knowledge of how the code worked, and then they would pass if the code returned the correct numbers, confirming the code was counting things as expected.

Knowing the complexity of the LSA calculations, I was hoping we could all get a better understanding about how the sample results are being generated.  With each iteration of the sample HMIS data set, are the results being validated to confirm that each category contains the expected number, or is the result set just the results of running the sample data through the sample code?

**Comment by MollyMcEvilley** [comment]
The result set is just what is produced by the sample code when run on the sample data.
