### ISSUE TITLE
LivingSituation list correction from 24 to 25

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#185]
Recently, there was an issue reported with LivingSituation options being used in one query, where the list originally ended with the option 24 but should end with 25. This one line was reported, but it turns out exactly the same list of options is used in multiple other places. Exactly 6 times the list ends with 25, but in 7 other places the list - otherwise identical - ends with 24. Please explain or correct; any reply will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
See issue #181
