### ISSUE TITLE
Sample Data Kit source vs result: SSNMissingOrInvalid seems impossibly high

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#186]
The SSNMissingOrInvalid count logic in 9.2 query is simple: select count(distinct n.PersonalID) from dq_Enrollment n where n.SSNValid = 0.

The dq_Enrollment.SSNValid calculation in 9.1 is slightly more complex, yet still quite straightforward: when some specific conditions for c.SSN (which comes from hmis_client, aka client.csv) are met, the value is 0; else 1 (intentionally skipping null since it's not relevant here). The only catch here is that it counts enrollments, not clients; which needs to be kept in mind.

After only those two steps, **the expected result is SSNMissingOrInvalid = 2801**, at least that's the number in the sample result file. However: when running the SQL with all the SSNValid conditions directly on the content of the **client.csv file**, the result is **651**, and when running the same on the **client.csv joined with enrollment.csv** (using personalid), the number jumps up to only **1744**. 

That means the "expected" result of 2801 should be impossible, even when all the other conditions are disregarded (which is a safe assumption to be made since those other conditions can only bring the number down, not up).

Please explain or correct; any reply will be highly appreciated.

**Comment by dburgstrom** [comment]
Thank you for pointing this out. I discovered that the code I ran was on hashed SSNs and names in our database. This caused an extremely high number in the LSAReport for SSNMissingOrInvalid calculation. I re-ran the code from last week on unhashed names and socials and obtained 603 for this variable instead. I will re-run with any updated code that may come this morning on unhashed data and upload today.

**Comment by MollyMcEvilley** [comment]
We are stuck with a really high number in this column for the test kit, I think -- if @dburgstrom runs the sample code on unhashed data, the output in the test kit won't be consistent with the sample data... The test data was obfuscated rather than hashed last year, which does make it easier to reference records IMHO, but the SSNs were all invalid.

**Comment by MichelleNevius** [comment]
Thanks! We are getting expected (high, but matching) value of 603.
