### ISSUE TITLE
6.12 Ambiguous where clause

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#187]
In the "insert into sys_TimePadded" query in 6.12 section, both sub-queries contain the same join statement:

```
inner join tlsa_HHID hhid on hhid.HoHID = hh.HoHID and hhid.ActiveHHType = hh.HHType
		and hhid.Active = 1 or hhid.ExitDate < rpt.ReportStart
```

Without having the order of actions clearly defined, some implementations can and do resolve the "and" opeartion first and only then the result is used for the "or" operation. This will cause the the records where  hhid.ExitDate < rpt.ReportStart to always meet the condition, even when hhid.HoHID = hh.HoHID is not true.

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Thank you!
