### ISSUE TITLE
Exit Destination (32): discrepancy between spec and code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#188]
@MollyMcEvilley for exit_destination = 32:

- In spec, LSA value = 11
- in sample code, ExitDesc = 10
![image-20200515-112737](https://user-images.githubusercontent.com/20728145/82586429-60148a00-9b4c-11ea-9dd7-ce2cb8cdf979.png)

**Comment by michelleogburn** [comment]
@MollyMcEvilley 
Similar problem with livingsituation

spec:
![image-20200515-124505](https://user-images.githubusercontent.com/20728145/82589624-445fb280-9b51-11ea-8d6c-8659a4bb20e2.png)

code:
Missing from 
- ESTLivingSit
- RRHLivingSit
- PSHLivingSit
![image-20200515-124438](https://user-images.githubusercontent.com/20728145/82589828-93a5e300-9b51-11ea-8060-4ec4f405c42f.png)

![image-20200515-124740](https://user-images.githubusercontent.com/20728145/82589868-a3252c00-9b51-11ea-920a-a46ebf63f591.png)

![image-20200515-124745](https://user-images.githubusercontent.com/20728145/82589876-a8827680-9b51-11ea-9315-b0878e05e54a.png)

**Comment by bayboos** [comment]
The "livingsituation problem" is not exactly similar - while the exit_destination = 32 have different output in specs vs code, the LivingSituation = 32 case is completely missing from the code (the translation from 2 to 4 is actually in the specs, just 5 lines below the highlighted one). But in both cases the question remains the same: which one is correct?
