### ISSUE TITLE
4.22 LSAHousehold: Default should be -1 not 0 for HHChronic, Vet, Disability, FleeingDV and Parent

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#19]
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L1412-L1498

In the above, when setting HHChronic, HHVet, HHDisability, HHFleeingDV and HHParent the else statement sets the value to 0 when the conditions are not met. However the spec says they should be -1.
![image](https://user-images.githubusercontent.com/44095973/47118964-7054dc80-d226-11e8-8d58-4493827df1b1.png)
![image](https://user-images.githubusercontent.com/44095973/47119004-8a8eba80-d226-11e8-8b43-e3c2d64a1483.png)

The data dictionary needs to be updated as well as it has 0 as a valid value for these fields, rather than -1.

**Comment by tcalder** [comment]
Note that it appears that 0 is still a valid value for HHVet in LSAExit (from 4.44):

![image](https://user-images.githubusercontent.com/44095973/47119164-0f79d400-d227-11e8-89a6-c9652cf59ec6.png)

And the Reference Populations expects HHVet = 0  in section 4.47 & 4.48, which means all the joins to reference population would fail for the non-vet population.

What we are currently doing is just exporting the 0's as -1. That keeps the logic of LSACalculated in tact and gets the correct values for the export.

**Comment by MollyMcEvilley** [comment]
As of today, the specs will be locked to changes -- HUD will take what's there, regardless of any potential errors in the specs... But this is going to be updated in the specs to match the LSA Dictionary (and the code).  For HHVet, HHDisability, HHFleeingDV, HHParent, and HHChronic, values should be either 1 or 0.
