### ISSUE TITLE
Question about ClientLocation

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#190]
@MollyMcEvilley 

![image-20200519-102948](https://user-images.githubusercontent.com/20728145/82595151-f7cca500-9b59-11ea-8db2-2f76e216fbaa.png)

hmis_EnrollmentCoC has an [InformationDate] column. Please confirm there can be more than 1 record per EnrollmentID with DateDeleted = NULL.

If yes, what hmis_EnrollmentCoC should we use - the most recent by InformationDate, or any?

This would be relevant in situations where there are two or more records in hmis_EnrollmentCoC for the same EnrollmentID **with different CoCCode**. As of now, the sample code checks that there is at least one record with the needed CoCCode regardless if it is the most recent data or not.

![image-20200519-103130](https://user-images.githubusercontent.com/20728145/82595654-d324fd00-9b5a-11ea-9ca6-618fe37bf55b.png)

**Comment by bayboos** [comment]
> Please confirm there can be more than 1 record per EnrollmentID with DateDeleted = NULL

This has to be true since HUD does allow a change of the CoC during one enrollment (but only in multi-CoC projects, which are also allowed).

> the sample code checks that there is at least one record with the needed CoCCode regardless if it is the most recent data or not

And this may be correct/intentional, since it's the enrollment record that actually counts and there is just one. However it would be nice to have this confirmed.

**Comment by MollyMcEvilley** [comment]
There can absolutely be more than one EnrollmentCoC record per EnrollmentID.  

For selection into tlsa_HHID, the only requirement is that the household was in ReportCoC for some part of the enrollment.

For identification of ACTIVE clients and households in step 5.1, the most recent record of EnrollmentCoC.CoCCode must be the ReportCoC.
