### ISSUE TITLE
Sample LSA export 2020_05_21.zip missing APR - Permanent Housing, project type = 3 from some files

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#194]
For the sample test kit expected LSA output, the files project.csv, projectcoc.csv, funder.csv and inventory.csv are lacking the records associated with APR - Permanent Housing, project type = 3.

**Comment by dburgstrom** [comment]
Hi Michelle. Thank you for bringing this to my attention. It seems that I re-labeled this project's CoC code in the test kit but not the data that was sent to the sample code. I have fixed this and verified that the APR - Permanent Housing project appears there now.

**Comment by MichelleNevius** [comment]
Hi David, Thanks for checking into it. Do you know when the revised zipped export files will be made available to us? Thanks!

**Comment by dburgstrom** [comment]
Yes, I should provide that tomorrow, after Molly makes any updates to the sample code.

**Comment by MichelleNevius** [comment]
Great, thanks!

**Comment by MichelleNevius** [comment]
The 5/28 sample lsa export is good; thanks!
