### ISSUE TITLE
Sample LSA export has different LSAHousehold.csv values than expected

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#195]
LSAHousehold.csv - the first difference we have noticed is the fact that in our LSA output, some households have PSHStatus = 11 while the sample output don’t have ANY of those. The condition for PSHStatus = 11 is (as described in the specs): the earliest entry date before report start date and the latest exit date = null (meaning: there is an active enrollment at the report’s end date).

**Comment by MichelleNevius** [comment]
It seems like those households have enrollments in the “missing” “Permanent Housing” program, which makes sense since it’s the only PSH program in the test data kit. And that in turn directly influences the number of distinct output lines reported in almost all of the output files.

**Comment by dburgstrom** [comment]
Hi Michelle. After following up on the previous, related issue, I see 17 entries in LSAHousehold with PSHStatus=11, instead of zero.

**Comment by MichelleNevius** [comment]
The 5/28 sample lsa export now has PSHStatus =11; thanks! 17 entries from our output, too. I think we are looking like a match on this table, so closing this.
