### ISSUE TITLE
3.6.	Household Types (tlsa_HHID) - age issue in Sample Code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#196]
@MollyMcEvilley 
![image-20200522-144735](https://user-images.githubusercontent.com/20728145/82962133-2bea0080-9f74-11ea-8596-9683dc26e5ac.png)

As shown above, 18 is not allowed in AgeGroup codes

To be consistent with spec.. `between 18 and 65` should be replaced with `between 21 and 65`.
![image-20200522-144634](https://user-images.githubusercontent.com/20728145/82962245-87b48980-9f74-11ea-9096-2b1975315ca6.png)

**Comment by MollyMcEvilley** [comment]
The code here and elsewhere uses 'between 18 and 65' instead of 'between 21 and 65' because the output  is the same (there are no values of 18, 19, or 20) and it is easier to understand without consulting the LSA Dictionary.  Added a comment to this effect in the code.
