### ISSUE TITLE
3.6.	Household Types (tlsa_HHID) - spec question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#198]
@MollyMcEvilley 
Why does the spec refer to "**three exit** cohort periods" if we calculate data for only 2 exit cohorts ("-1" and "-2")?
![image-20200525-095144](https://user-images.githubusercontent.com/20728145/82962902-5ccb3500-9f76-11ea-98b7-990103e3ad9c.png)

**Comment by MollyMcEvilley** [comment]
There are 3 exit cohorts: -2, -1, and 0.  That last one includes households who exited in the first six months (for a year-long report) of the active report period.
