### ISSUE TITLE
HDX reports invalid value for VALID value

### ISSUE THREAD

**Issue by thomas-powers** [abtassociates/LSASampleCode#20]
LSAHousehold.csv > ESTLivingSit values of 15 & 16 are reported as invalid values.
LSAPerson.csv > HHParent value of 2 is reported as invalid value.
LSACalculated.csv > Cohort values of 10 & 11 are reported as invalid values.

**Comment by tcalder** [comment]
We are getting these issues as well:
LSAHousehold:
1. HHChronic = -1
2. HHDisability = -1
3. HHFleeingDV = -1
4. HHParent = -1
5. HHVet = -1
* Note this may be valid if the spec is changed, as talked about today.

LSAPerson:
1. HHParent = 2

LSACalculated:
1.	Cohort: 10,11,12,13
2.	Population: 28

**Comment by MollyMcEvilley** [comment]
(Values in LSAHousehold for HHVet, HHChronic, HHDisability, HHFleeingDV, and HHParent should be 0 and not -1 -- this was an error in the specs that has been updated for consistency with the LSA Dictionary and sample code.) 

Passed the other issues on to the HDX developers.
