### ISSUE TITLE
3.6. Household Types (tlsa_HHID) - ExitHHType question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#200]
Hi @MollyMcEvilley 

Would you confirm the highlighted sections below are correct? There is not much said in the spec about ExitHHType but our developer has a feeling that some conditions for ExitAge and ExitHHType must be similar.

![image-20200525-101505](https://user-images.githubusercontent.com/20728145/82965472-0e6d6480-9f7d-11ea-9d99-bbb9fbbaeea1.png)

It would be great if instructions could be added to the spec as it was done for other calculations... to prevent "inconsistent" questions in the future.

Our 2 cents. :)

**Comment by MollyMcEvilley** [comment]
It wasn't incorrect, but it was more complicated than necessary.  Updates have been made in both the code and the specs.
