### ISSUE TITLE
5.3.	Get Active Clients for LSAPerson - question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#201]
Per spec:
![image-20200526-114718](https://user-images.githubusercontent.com/20728145/82965706-baaf4b00-9f7d-11ea-9ce0-85d27cb91921.png)

Per sample code:
![image-20200526-114844](https://user-images.githubusercontent.com/20728145/82965718-cb5fc100-9f7d-11ea-9631-6d29cb5824d9.png)

Why is `n.EntryDate <= rpt.ReportEnd` restriction used if there is no way to have `tlsa_Enrollment` with `EntryDate > ReportEnd`? There are several similar instances in the sample code.

**Comment by MollyMcEvilley** [comment]
Although it is not required, it makes the relationship between lsa_Report and tlsa_Enrollment explicit rather than implicit.
