### ISSUE TITLE
Spec: 6.14 Living Situation references list value of 24 instead of 25

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#204]
Hi @MollyMcEvilley 

I think my comment was missed. This needs to be fixed in the spec as well.

https://github.com/HMIS/LSASampleCode/issues/169#issuecomment-634345016

**Comment by nataliesus-dev** [comment]
Hi @MollyMcEvilley 
Few more places to fix
![image](https://user-images.githubusercontent.com/64896441/83766305-ebca0280-a684-11ea-86a1-5d342bcc7198.png)

**Comment by MollyMcEvilley** [comment]
Thank you!  I hope there was some massive benefit to changing all of those numbers, because it sure did break a lot of things...
