### ISSUE TITLE
3.5 Issues - tlsa_Enrollment - [ActiveAge] sample code issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#205]
@MollyMcEvilley 
in a follow up to https://github.com/HMIS/LSASampleCode/issues/193, there is one thing we'd like to clarify.

The following code **excludes** enrollments exited before ReportStart - that is against the Spec where it is said that all enrollments must participate

`inner join tlsa_Enrollment n on n.EntryDate <= rpt.ReportEnd 
and (n.ExitDate is null or n.ExitDate >= rpt.ReportStart)`

Our developer thinks `and (n.ExitDate is null or n.ExitDate >= rpt.ReportStart)` needs to be removed to make it work for all enrollments, and then `n.ExitDate < rpt.ReportStart` validation in `case` block will make sense.

**Comment by MollyMcEvilley** [comment]
That's a really good clarification -- I'm sorry I misunderstood the first time around.  Thank you!
