### ISSUE TITLE
5.15.1 sample code issue - HHTypeEST used instead of AHAREST

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#207]
Acc to specification, AdultEST/RRH/PSH values are determined by using (among others) AHAR[x] values. In the sample code, 5.15.2 and 5.15.3 queries do follow this rule, however 5.15.1 query (setting AdultEST) uses HHTypeEST instead.

It does seem like copy-paste error, but to be safe: please explain or correct. Any reply will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
You are correct -- this was a copy-paste error.
