### ISSUE TITLE
5.16.3 sample code issue - HoHAdult used instead of HoHPHS

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#208]
Acc to specification,5.16. AHARHoHEST/RRH/PSH values are determined by using (among others) AHAR[x] and HoH[x] values. In the sample code, 5.16.1 and 5.16.2 queries do follow this rule, however 5.16.3 query (setting AHARHoHPSH) uses HoHAdult instead of HoH[x].

It does seem like copy-paste error, but to be safe: please explain or correct. Any reply will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
You are correct -- this was a copy-paste error.
