### ISSUE TITLE
Follow up to #190 - 3.3.1 Question about ClientLocation

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#209]
We understood your response to this issue. However, the update to 3.3.1 results in only the most recent ClientLocation being used and is now in conflict with the spec:

![image-20200602-144229](https://user-images.githubusercontent.com/20728145/83653838-204c9a00-a571-11ea-9ecc-31a6fb6d5e0f.png)

If this was done intentionally, the spec needs to be updated.

**Comment by MollyMcEvilley** [comment]
Agh.  I changed it in response to the earlier issue.  Once I changed it, I realized why I should NOT have changed it -- I responded to the issue but forgot to change it back.  Thank you!

**Comment by MollyMcEvilley** [comment]
Definitely not intentional -- thank you!
