### ISSUE TITLE
4.23 HH AdultAge... again...

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#21]
Our developer has identified a further issue with this section.
The **Specs** show:
![4 23adultagespecs](https://user-images.githubusercontent.com/20728145/47193641-e3368400-d308-11e8-84a7-3cea68bd6809.png)

The **code** currently is:
`	--CHANGE 10/5/2018 - more corrections to HHAdultAge
set lp.HHAdultAge = coalesce((select
			--HHTypes 3 and 99 are excluded by the CASE statement
			case when max(n.AgeGroup) >= 98 then -1
				when max(n.AgeGroup) <= 17 then -1
				when min(n.AgeGroup) between 18 and 25
					and max(n.AgeGroup) between 25 and 55 then 25
				when max(n.AgeGroup) = 21 then 18
				when max(n.AgeGroup) = 24 then 24
				when min(n.AgeGroup) between 64 and 65 then 55
				else -1 end
		from sample_code.active_Enrollment n
		where n.PersonalID = lp.PersonalID and n.HHType in (1,2)), -1)`

So, we are to take data from active_Enrollment instead of active_household.

In the test kit, there is the following household:

|PersonalID|Adult or Child|activeHousehold.HouseholdID|activeHousehold.HHAdultAge|tmp_person.HHAdultAge|
|-----------|-------------|------------|-------------|------------|
|19526|Adult|777433|24|24|
|190529|Child|777433| |-1|
|190534|Child|777433| |-1|
|190536|Child|777433| |-1|
|19526|Adult|830119|24|24|
|190529|Child|830119| |-1|
|190534|Child|830119| |-1|
|190536|Child|830119| |-1|

This is an issue because
Notes from **AAQs_LSA_10.11.2018** state:
b) 4.22 sets HHAdultAge for individual HMIS HouseholdIDs (i.e., for every enrollment). 

- For CO households, UN households, and any AC household with a member of unknown age, the value should always be -1.
- If all adults are 22 or under, the value should be 18.
- If all adults are 24 or under, the value should be 24.
- If all adults are 55 or older and the HHType is AO (1), the value should be 55.
- If there's at least one adult older than 24 and at least one adult under 55, the value should be 25.

4.23 sets HHAdultAge for tmp_Person based on HHAdultAge values for all HMIS HouseholdIDs in which they were served.

- If at least one HMIS HouseholdID has an HHAdultAge of 18, set the value to 18 in tmp_Person.
- If no HouseholdID has a value of 18 but there's a 24, set it to 24.
- If no HouseholdID has a value of 18 or 24 but there's a 55, set it to 55.
- If not HouseholdID has a value of 18,24, or 55, but there's a 25, set it to 25.
- Otherwise, set it to -1. 

However,
tmp_person.HHAdultAge should be based on all activeHousehold.HHAdultAge, so the correct value for children should be 24, correct?

**Comment by michelleogburn** [comment]
Newbie, here is the github extract

https://github.com/MollyMcEvilley/LSASampleCode/blob/55aaa6846446678c70ad6612ed861aaf8686ab9c/LSASampleCode.sql#L1504-L1516

**Comment by MollyMcEvilley** [comment]
Newbie... :)

In the hopes that this is the final final final correction to HHAdultAge issues:  YES -- tmp_Person.HHAdultAge should be set based on active_Household and NOT active_Enrollment.  Correction committed today: https://github.com/MollyMcEvilley/LSASampleCode/commit/c570369c4c3ea3075a0ddfa2ca8a676dfb439a83
