### ISSUE TITLE
3.5 tlsa_Enrollment - [Exit1Age/Exit2Age] issues in spec and sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#210]
This was previously mention in #193 . However it was a comment on the main issue and was missed. My mistake... (https://github.com/HMIS/LSASampleCode/issues/193#issuecomment-632418031) The first issue was fixed, but the second was missed.

Issue #2: "EntryDate > CohortEnd" issue in both Spec and Sample Code
It seems there is an issue in `or EntryDate > CohortEnd`. Shouldn't it be `or ExitDate > CohortEnd`?
![image-20200521-104907](https://user-images.githubusercontent.com/20728145/82619542-113a1500-9b8b-11ea-9142-aebe5a02ebb0.png)

**Comment by MollyMcEvilley** [comment]
I have made corrections in the specs and sample code consistent with:
- If ExitDate < CohortStart, it's an enrollment that might be used for System Path and the age used should be the age at entry.  
- If EntryDate >= CohortStart, the age used should be the age at entry (regardless of whether the exit is in the cohort period or it's a 'future' enrollment that might be relevant in looking at returns.
- The 'EntryDate > CohortEnd' in the Priority 1 row of the specs is entirely redundant.
