### ISSUE TITLE
5.8.3 confusing code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#213]
![image-20200528-104721](https://user-images.githubusercontent.com/20728145/83656334-40318d00-a574-11ea-9e70-12e83732678e.png)

What is the purpose of

`hn.EnrollmentID in 
			(select top 1 earliest.EnrollmentID
			 from hmis_Enrollment earliest
			 where earliest.EnrollmentID = chn.EnrollmentID 
			 order by earliest.DateToStreetESSH asc)`

the same enrollment is selected. Also, not sure why `order by earliest.DateToStreetESSH asc` is used.

**Comment by MollyMcEvilley** [comment]
I have no idea why that was there... Thank you for pointing it out.
