### ISSUE TITLE
5.9. ch_Episodes - discrepancy in Spec and Sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#216]
It is clearly stated that episodes must be calculated for _only HoH/adults_

![image-20200603-091635](https://user-images.githubusercontent.com/20728145/83657777-285b0880-a576-11ea-9e7a-9d7738fa7d4c.png)

**Sample Code:**
There is no HoH/adult restriction when episodes are counted. Also, in the comments Molly mentioned that code works for any person.

![image-20200603-091815](https://user-images.githubusercontent.com/20728145/83657960-6c4e0d80-a576-11ea-9e40-5248551a70b2.png)

What should we do with this discrepancy between Sample Code and Spec?

**Comment by MollyMcEvilley** [comment]
There is no conflict -- the dates referenced are in ch_Include, and PersonalIDs in ch_Include are already limited to HoH/Adults.
