### ISSUE TITLE
5.10 Discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#218]
**Sample Code**
![image-20200603-132117](https://user-images.githubusercontent.com/20728145/83658422-0a41d800-a577-11ea-9a61-d266e85bf4b2.png)

**Spec**
![image-20200603-132311](https://user-images.githubusercontent.com/20728145/83658489-1cbc1180-a577-11ea-9e49-94af91449c03.png)

1. We want to confirm 365 days is ok.  What about a leap year?
2. Both spec and sample code must have either 364 or 365 . One of the resources must be updated.

**Comment by MollyMcEvilley** [comment]
Updates in both the specs and the code to use 1 year instead of x# of days.
