### ISSUE TITLE
5.4. LSAPerson Demographics - issues in sample code, revisiting

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#222]
Follow-up to #202 
**Issue 2 was missed earlier**
Spec:
Instructions to calculate `DVStatus` for `tlsa_Person` include `CurrentlyFleeing`

![image-20200526-130631](https://user-images.githubusercontent.com/20728145/82965945-7e301f00-9f7e-11ea-90e1-48b6acc3a97d.png)

But this was already calculated in DVStatus in step 3.4.

![image-20200526-133752](https://user-images.githubusercontent.com/20728145/82965997-9dc74780-9f7e-11ea-8e40-01be58e80a57.png)

Why not re-use it? The sample code looks correct. But spec is different.

**Comment by MollyMcEvilley** [comment]
Revised the specs logic for DVStatus and for DisabilityStatus, which had a similar issue.  (Commit forthcoming.)
