### ISSUE TITLE
5.10.8 - Questions

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#225]
Hi @MollyMcEvilley 

**Question 1**
Please confirm **CHTimeStatus** = 3 should be replaced with **CHTimeStatus** = 99 for cases described in 5.10.8.
![image-20200608-112440](https://user-images.githubusercontent.com/20728145/84117026-bf481a80-a9e5-11ea-8a55-60b3fdbb3ebd.png)

**Question 2**
In the sample code you use `chn.CH = 1` restriction that is not mentioned in the spec.
![image-20200608-112804](https://user-images.githubusercontent.com/20728145/84117163-ed2d5f00-a9e5-11ea-8c60-7bfdf32b8473.png)

**Question 3**
Please confirm we must compare with real `hmis_Enrollment.EnrollDate` rather than adjusted `rlsa_Enrollment.EntryDate
![image-20200608-113149](https://user-images.githubusercontent.com/20728145/84117279-2239b180-a9e6-11ea-91fe-e50a8fe641f1.png)

The spec refers to third `ch_Enrollment` table.
![image-20200608-113242](https://user-images.githubusercontent.com/20728145/84117351-3f6e8000-a9e6-11ea-86d1-c5d0a8b5af42.png)

BTW, there are 4 places in the spec that refer to `ch_Enrollment` but it is never mentioned in the sample code. This looks really suspicious.

**Comment by MollyMcEvilley** [comment]
I re-wrote some of the business logic in 5.10 with the intention of making this clearer -- there's no intentional change to the logic other than to remove the obsolete reference to ch_Enrollment.
