### ISSUE TITLE
Sample LSA export from 6/4 issue: HHParent column in the lsa_Exit.csv file

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#227]
Hi. I am not able to reopen issue #206, but I think the output that was meant to address that still does not. Please see #206

**Comment by dburgstrom** [comment]
Hello. I looked and think that it does. This is the file I opened and checked. I saw 203 rows with "1" marked for HHParent and 281 rows marked with "0". 
![image](https://user-images.githubusercontent.com/64597095/84181074-88f6b380-aa56-11ea-88cb-c1bd08340e94.png)

**Comment by dburgstrom** [comment]
One more picture, just to be sure.
![image](https://user-images.githubusercontent.com/64597095/84181257-a75caf00-aa56-11ea-8103-3141a0175c9c.png)

**Comment by MichelleNevius** [comment]
Hi David. When Meradith distributed, it had that title with 06_04 in the title, and that 10:53 time... but when I open the zip and see the LSAExit.csv, I see 967 records that are HHParent=0. My row total sum is 1787, so I'm not sure where my disconnect is....

**Comment by MollyMcEvilley** [comment]
Corrected so the join is on _HouseholdID_ rather than the HoH _EnrollmentID_ for household characteristics **HHParent**, **HHFleeingDV**, and **HHDisability** .

**Comment by dburgstrom** [comment]
173 records with HHParent=1 in the latest export now.
