### ISSUE TITLE
5.14 AHARRRH and AHARPSH - discrepancy but not issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#231]
@MollyMcEvilley This issues is the first in a series of smaller issues

**Spec**
![image-20200610-112115](https://user-images.githubusercontent.com/20728145/84410412-d4c66b80-abc2-11ea-8891-4e00e5c9f343.png)

**Sample Code**
![image-20200610-112121](https://user-images.githubusercontent.com/20728145/84410767-f0317680-abc2-11ea-9b88-5f8184870c5a.png)

Different restrictions for `MoveInDate` for both AHARRRH and AHARPSH

**Comment by michelleogburn** [comment]
@MollyMcEvilley , would you do a brief write up of what you discussed in the meeting on 7/2?

**Comment by michelleogburn** [comment]
@MollyMcEvilley , would you do a brief write up of what you discussed in the meeting on 7/2?

**Comment by MollyMcEvilley** [comment]
The specs note that MoveInDate must be <= ReportEnd.  
n.MoveInDate (tlsa_Enrollment) is _only_ non-NULL if the value is <= ReportEnd, so the explicit comparison isn't needed in the code -- only a check for a non-NULL value.
