### ISSUE TITLE
5.17 HHAdultAge - issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#232]
This one is a bit more urgent @MollyMcEvilley 

**Spec**
![image-20200610-151639](https://user-images.githubusercontent.com/20728145/84411720-3d154d00-abc3-11ea-8c92-484735935401.png)

**Sample Code**
![image-20200610-151649](https://user-images.githubusercontent.com/20728145/84411936-5918ee80-abc3-11ea-8320-5d7d582eaa0a.png)

**Issue**
55 vs 64. Either Spec or Sample Code must be updated.

**Comment by MollyMcEvilley** [comment]
This is similar to the 'between 18 and 24' vs. 'between 21 and 24' issue -- given the values that exist in tlsa_Enrollment, the outcome is the same regardless of how it is phrased.
