### ISSUE TITLE
5.14, 5.15, 5.16 - Spec refers to not used field

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#234]
Sections:
- 5.14
- 5.15
- 5.16

have `EntryDate` in the Relevant Data Source list. But neither instructions for programming nor sample code use `EntryDate`.

![Capture 2020-06-11 at 9 19 50](https://user-images.githubusercontent.com/20728145/84412888-be211400-abc4-11ea-8e91-15b00fda51d8.png)

Also, 5.16 has `ActiveAge` in the Relevant Data Source list. But neither instructions for programming nor sample code use `ActiveAge` in 5.16 I believe it was a copy/paste issue.

**Comment by MollyMcEvilley** [comment]
Corrected!
