### ISSUE TITLE
5.18 - question about sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#239]
**Spec**
![image-20200611-100356](https://user-images.githubusercontent.com/20728145/84415505-b6af3a00-abc7-11ea-86e7-b653362c200a.png)

**Sample Code**
![image-20200611-100444](https://user-images.githubusercontent.com/20728145/84415630-e5c5ab80-abc7-11ea-9dc3-10a1eaca49c9.png)

Why not limit use 

- `where … and hhid.HHChronic = 1`
- `where … hhid.HHVet = 1`

It would be more obvious and similar to what is said in the spec.

If it makes sense, then it affects code for:

- `HHChronic`
- `HHVet`
- `HHDisability`
- `HHFleeingDV`
- `HHParent`

in steps 5.18.2, 5.18.4, 5.18.6.

**Comment by michelleogburn** [comment]
@MollyMcEvilley , would you do a brief write up of what you discussed in the meeting on 7/2?

**Comment by MollyMcEvilley** [comment]
This is a style difference that doesn't impact report output.  If your developers prefer to do it differently, that's totally fine.
