### ISSUE TITLE
HMIS CSV Data 2020_05_14 HealthAndDV.csv issue

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#240]
Hi Molly and Jules,
Here are the issues I mentioned on the LSA office hour call in HealthAndDV.csv.
1a:Issues with data collection stage: GeneralHealthStatus,DentalHealthStatus,MentalHealthStatus should only has collection stage 1 and 3. There are a brunch records with stage 2.

1b: PregnancyStatus,DueDate should only has collection stage 1 and 2. There are records with stage 3.

Please advise on how to handle with these. Thank you. 

Best,
Chen

**Comment by cwanska** [comment]
@MollyMcEvilley I'm digging back into a few of the old issues here. Should this be put on hold for next year or closed or...?

**Comment by MollyMcEvilley** [comment]
I'm going to go ahead and close it.  This can't really be addressed from the LSA angle -- it's a data exchange issue.
