### ISSUE TITLE
6.4 - issue in Sample Code (xMoveIn = [10, 20] are not allowed)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#242]
Hi @MollyMcEvilley 

**Spec**
![image-20200612-142149](https://user-images.githubusercontent.com/20728145/84605939-5681f780-ae56-11ea-8004-442be5f442c7.png)

**Sample Code**
![image-20200612-142211](https://user-images.githubusercontent.com/20728145/84605948-6a2d5e00-ae56-11ea-8cda-9a0a5a92599f.png)

**Issue**
The sample code uses codes 10 and 20 that are not allowed in the spec.

**Comment by MollyMcEvilley** [comment]
Corrected — thank you!
