### ISSUE TITLE
2020.04.20  LSA Data Dictionary FY2019 --question on RelationshipToHoH1

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#244]
Hi. This workbook, on its Columns page, has RelationshipToHoH1 defined as:
The total number of EnrollmentIDs where:
• The enrollment was active in ReportCoC during the report period; and
• Client was 18 or older or identified as a head of household (RelationshipToHoH = 1) at entry; and
• The enrollment does not have an informational value for RelationshipToHoH.

Issue: the age and hoh status do not seem to relate to specs. 

According to the LSA specification, clients counted in the RelationshipToHoH1 column have to meet two conditions, both refering to the dq_Enrollment table: Status1 is not null and RelationshipToHoH is not between 1 and 5. 

Status1 is an “age group status” for cohort 1, indicating the age group for clients who were active during report’s selected date range. By the specs, it can only be null when client does not belong to this cohort (i.e. discharged before report’s start date) because all other “unexpected” data combinations are represented as 0.

RelationshipToHoH is exactly what it sounds like - a value directly copied from enrolment.csv file. Values 1 trough 5 are all the available options in the CSV export; thus the requirement of having this value “not between 1 and 5” means it has to be empty - either because the actual value stored in AWARDS is not recognized by CSV, or because it’s completely missing (i.e. no household record).

Can you explain the field's definition on the 2020.04.20  LSA Data Dictionary FY2019, please? Thanks!

**Comment by MollyMcEvilley** [comment]
That has to be a copy/paste error... I overlooked adding the LSA Dictionary to GitHub, but am adding it now with a correction.

To confirm:  It should count any enrollment in relevant project types that was active in the report period and does not have a valid value for _RelationshipToHoH_ in HMIS.
