### ISSUE TITLE
6.19. ReturnTime - missing instructions in the spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#249]
The sample code uses the following mapping to insert data into `lsa_household.ReturnTime`
![image-20200618-103719](https://user-images.githubusercontent.com/20728145/85041752-36488600-b13f-11ea-9f38-bc498be6b688.png)

However, there is no mention in the spec for 6.19 about this mapping.

**Comment by MollyMcEvilley** [comment]
The logic for this is defined in section 6.9 of the specs.
