### ISSUE TITLE
5.14, 5.15, 5.16 RRH - issue with move-in date for RRH

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#251]
While one problem was fixed in #229 , another problem was created.

According to spec, `MoveInDate <= ReportEnd` is a mandatory restriction.
![image-20200619-091758](https://user-images.githubusercontent.com/20728145/85573926-28857b80-b5eb-11ea-9ca5-ac65e548f01d.png)

But with the last update, `MoveInDate <= ReportEnd` was deleted from the sample code. The code needs to be repaired.

**Comment by michelleogburn** [comment]
Resolved! Thank you.

**Comment by MollyMcEvilley** [comment]
thank you!
