### ISSUE TITLE
7.4 AC3Plus - issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#257]
Sample code differs from Spec

**Spec**
![image-20200622-132537](https://user-images.githubusercontent.com/20728145/85748861-373c6300-b6bd-11ea-9894-b5a012d8193c.png)

**Sample Code**
AC3Plus is the number of project stays, not 1 or 0
![image-20200622-132705](https://user-images.githubusercontent.com/20728145/85749099-681c9800-b6bd-11ea-964f-e368e1e09bdd.png)

**Comment by MollyMcEvilley** [comment]
Corrected -- commit forthcoming.
