### ISSUE TITLE
7.1 - code discrepancy

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#258]
**Spec**
![image-20200623-105720](https://user-images.githubusercontent.com/20728145/85749306-97cba000-b6bd-11ea-9d27-a5e218fed1e6.png)

**Sample Code**
![image-20200623-105802](https://user-images.githubusercontent.com/20728145/85749379-a9ad4300-b6bd-11ea-8fe3-a46c73a86311.png)

**Discrepancy**
Spec uses `<` but sample code uses `<=` for `EntryDate`

**Comment by MollyMcEvilley** [comment]
Code corrected - commit forthcoming.
