### ISSUE TITLE
7.1 - missing part in sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#259]
**Spec**
![image-20200623-115900](https://user-images.githubusercontent.com/20728145/85749760-fa24a080-b6bd-11ea-9a8e-91fd1fd314db.png)

**Sample Code**
![image-20200623-120017](https://user-images.githubusercontent.com/20728145/85749855-0c9eda00-b6be-11ea-8026-306a5dd6e4ca.png)

**Issue**

Sample code is missing:
`[Other].EntryHHType = qx.ExitHHType or ([Other].CohortPeriod = qx.CohortPeriod and [Other].ExitHHType = qx.ExitHHType)`

**Comment by MollyMcEvilley** [comment]
The code is correct here -- the reference to CohortPeriod in the specs is obsolete (there is no such column) -- so I've updated the specs.  (Commit forthcoming.)
