### ISSUE TITLE
6.2/6.8

### ISSUE THREAD

**Issue by k-adunn** [abtassociates/LSASampleCode#263]
Wanted some clarification around this issue:
In section 6.2, there are no details on computing AC3Plus. Though there is a note which says “Note: If HHChild = 3 and HHType = 2, the household is counted in the AC Households with 3 or More Children population” . In section 6.8, the spec says “If there is any active HouseholdID for the HoHID where ActiveHHType = HHType and AC3Plus = 1 and ProjectType is consistent with the project group, set the value for EST/RRH/PSHAC3Plus to 1. Otherwise, set to 0”.

Please clarify, what should be the value of AC3Plus in LSAHousehold file in this scenario.

**Comment by MollyMcEvilley** [comment]
Added clarification to the specs in section 6.8:

> **EST/RRH/PSHAC3Plus**
> For records in tlsa_Household where **HHType** = 2 and **HHChild** = 3, set **EST/RRH/PSHAC3Plus** to 1 Iif there is any active **HouseholdID** in tlsa_HHID for the **HoHID** where **ActiveHHType** = 2 and AC3Plus = 1 and ProjectType is consistent with the project group.  For all other records, set to 0.
