### ISSUE TITLE
6.19. lsa_Household columns definition issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#264]
The spec states:
![image-20200618-104446](https://user-images.githubusercontent.com/20728145/85824636-216a8480-b735-11ea-95a2-a3920da53a80.png)

This means that some of the columns in lsa_Household may have NULL values.

But the sample code shows all columns are "NOT NULL" - thus, it is not possible to store null values. They are automatically converted to 0.
![image-20200618-104955](https://user-images.githubusercontent.com/20728145/85824763-6098d580-b735-11ea-9ff0-330364587c8a.png)

Specs likely need to be updated.

**Comment by MollyMcEvilley** [comment]
I am confused by this part:
![image](https://user-images.githubusercontent.com/6156815/87044400-74781900-c1c4-11ea-9c4a-917b602f82fd.png)
The statement in the specs means exactly the opposite -- **none** of the columns in lsa_Household may have NULL values.  

Am I missing something?
