### ISSUE TITLE
6.14 moved text in the spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#265]
Text has shifted into the margin

![image-20200619-114150](https://user-images.githubusercontent.com/20728145/85824830-8faf4700-b735-11ea-9aa8-7c726d691051.png)

Same problem found in 3.1
![image-20200619-123328](https://user-images.githubusercontent.com/20728145/85824891-b2d9f680-b735-11ea-8b21-3a9af5687e4d.png)

**Comment by MollyMcEvilley** [comment]
Thank you... I have no idea how that happens, but I fixed it.  (Commit forthcoming)
