### ISSUE TITLE
7.3 - issues in spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#268]
![image-20200622-104135](https://user-images.githubusercontent.com/20728145/85825516-44963380-b737-11ea-8682-5dffc35feeaf.png)

### Issues

- There is no tlsa_**ExitDate** field
- `tlsa_Exit.HHType` and tlsa_Exit.Cohort` are not listed in Source tables and schema

**Comment by MollyMcEvilley** [comment]
Thank you!  Correct - commit forthcoming
