### ISSUE TITLE
7.4 - HHVet question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#269]
There is only one record in `hmis_Client` per each `PersonalID`, correct? In this case, not sure why MAX() is used.

![image-20200622-124534](https://user-images.githubusercontent.com/20728145/85825704-c4bc9900-b737-11ea-85fb-01d47708a166.png)

**Comment by michelleogburn** [comment]
And a follow-up to the above

For each `ex` there can be more than 1 `hh` record. Can it affect update? Maybe second highlighted block should be reworked.


![image-20200622-125213](https://user-images.githubusercontent.com/20728145/85825790-01889000-b738-11ea-987c-887e4a6f86ca.png)

**Comment by MollyMcEvilley** [comment]
MAX is used because there's only one veteran status per person, there may be more than one person in a household & this applies to all household members.
