### ISSUE TITLE
6.9.3 ReturnTime - issue in sample code - follow-up

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#270]
The following was not resolved by #247 

![image-20200616-140625 (1)](https://user-images.githubusercontent.com/20728145/86544450-d5110880-bedb-11ea-96ca-e6d83f8b3a9d.png)

### Issue 1
According to spec, ReturnTime depends on period of days. Sample Code used difference in days.

I.e. if category = 31 days, then:

- spec: ReturnTime = 60
- sample code:  ReturnTime =31

### Issue 2
Also, not sure why in sample code ReturnTime = -1 for `ESTStatus IN ( 11, 12 ) OR RRHStatus IN ( 11, 12 ) OR PSHStatus IN ( 11, 12 )`. There is no mention in Spec.

Further, some text was added, since #247 was submitted, in spec for `FirstEntry`
![image-20200703-140230](https://user-images.githubusercontent.com/20728145/86544500-3e911700-bedc-11ea-8a67-1819de3ae348.png)

Developer's concern is that this text was added for FirstEntry but in sample code there is no ESTStatus IN ( 11, 12 ) OR RRHStatus IN ( 11, 12 ) OR PSHStatus IN ( 11, 12 ) restriction for FirstEntry .

Instead, this restriction in sample code appears for Stat and ReturnTime. And there is no clue about this restriction for Stat and ReturnTime in the spec.

Maybe Molly wanted to add her note not under FirstEntry section by under Logic part? Could you please ask Molly to double-check?

**Comment by MollyMcEvilley** [comment]
Issue 1 - The grouping is done in the sample code in step 6.19.

Issue 2 - Any household who has an active enrollment with an entry date to the start of the report period (xStatus in (11,12) has an active enrollment that is "part of a period of continuous engagement with the continuum that began prior to the report period" -- which is the definition of **Stat** = 5.  I moved this language from **FirstEntry** to **Stat**.  (commit forthcoming)
