### ISSUE TITLE
8.2.	Get Average Days for Length of Time Homeless by System Path - SystemPaths 8 and 9 were mistakenly omitted last year

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#271]
1. SystemPaths 8 and 9 were mistakenly omitted last year
2. SystemPath list was incorrect last year

![image-20200505-134851](https://user-images.githubusercontent.com/20728145/86544648-79e01580-bedd-11ea-9f13-26faf66412ac.png)

After reviewing previous changes, our developer thinks restrictions should be fixed for row = 8.

### Spec
It looks like row 8 also should be updated adding [8,9] to the list:
![image-20200630-091207](https://user-images.githubusercontent.com/20728145/86544684-bdd31a80-bedd-11ea-9651-c2e1a907c391.png)

### Sample Code
![image-20200630-092327](https://user-images.githubusercontent.com/20728145/86544690-cfb4bd80-bedd-11ea-9c4d-21fd8480de8e.png)

**Comment by MollyMcEvilley** [comment]
SystemPath 8 is PSH only and SystemPath 9 is ES/SH & PSH Only, so 'Days Housed in RRH' is not relevant.
