### ISSUE TITLE
7.7 - specs do not define logic for SystemPath = -1 in LSAExit

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#277]
### Spec
![image-20200624-104123](https://user-images.githubusercontent.com/20728145/86545068-cb3dd400-bee0-11ea-971a-73596e54ab55.png)

### Sample Code
![image-20200624-104159](https://user-images.githubusercontent.com/20728145/86545097-0c35e880-bee1-11ea-8403-a331cdb9eb50.png)

### Issue
Spec uses `SystemPath = -1` that is not in the spec allowed list.

**Comment by MollyMcEvilley** [comment]
I changed the title of the issue because the problem was not that the code was doing something it shouldn't, but that the specs omitted the logic for when SystemPath is n/a... that is corrected now.
