### ISSUE TITLE
7.7.1 and 7.7.2 - these steps are not documented in the spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#278]
### Spec step 7.7.1
![image-20200624-104940](https://user-images.githubusercontent.com/20728145/86545255-769b5880-bee2-11ea-89d1-6a2bce87ceae.png)

There is not any documentation for this sub-step in the spec.

### Spec step 7.7.2
![image-20200624-104805](https://user-images.githubusercontent.com/20728145/86545276-9b8fcb80-bee2-11ea-9f16-476598189eab.png)

There is no any documentation for this sub-step in the spec.

**Comment by MollyMcEvilley** [comment]
https://github.com/HMIS/LSASampleCode/commit/90fa8686e9ef09a7862fa892ce32cb9c0189eb8c

The issue re: 7.7.1 was addressed in the commit above.  

Step 7.7.2 is not required -- the same output would be achieved by skipping it and going on with 7.7.3 -- but it's consistent with the logic and it saves a whole lot of processing. I'm adding additional comments to the code to explain why it's there...
