### ISSUE TITLE
8.1 - sample code question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#282]
Our developer is not sure about the highlighted code below.

`SystemPath can be (1,3,5,7,9,10)` only if `ESDays > 0`. `SystemPath = 12` is possible but we have absolute `ESDays > 0` restriction.

`or pop.SystemPath is null` is already checked in `inner join`. Why do we need to duplicate it in main `where`?

![image-20200626-125457](https://user-images.githubusercontent.com/20728145/86549443-7f952580-bef4-11ea-94e4-a28f0a6b46ae.png)

**Comment by MollyMcEvilley** [comment]
This is sample code.  At this stage, I am not going to make changes unless the code is wrong.  Developers are free to modify the code.
