### ISSUE TITLE
8.1 - "rounded to the nearest whole number" missing in the sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#283]
### Spec
![image-20200626-132957](https://user-images.githubusercontent.com/20728145/86549507-af442d80-bef4-11ea-8438-b7066361885a.png)

### Sample Code
![image-20200626-132850](https://user-images.githubusercontent.com/20728145/86549537-c1be6700-bef4-11ea-9700-b406dea855d0.png)

### Issue
There is no"`rounded to the nearest whole number`" in the sample code.

**Comment by MollyMcEvilley** [comment]
Added language to the specs in sections 8.1-8.8 to specify that it's okay to use the result of a db 
AVG or AVERAGE function that returns an integer when provided with integer parameters.
