### ISSUE TITLE
8.1 SystemPath - issue either in the spec or in sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#284]
### Spec
![image-20200626-133711](https://user-images.githubusercontent.com/20728145/86549655-0d711080-bef5-11ea-879e-05c8c262303f.png)

### Sample Code
![image-20200626-134351](https://user-images.githubusercontent.com/20728145/86549688-1eba1d00-bef5-11ea-8f59-160392f58d19.png)

If the spec is OK, then there is an issue in the sample code because `lsa_Calculated.SystemPath = -1` only for `pop.SystemPath is null`, in other cases `lsa_Calculated.SystemPath` = [1,3,5,7,9,10,12] because of `lh.SystemPath = pop.SystemPath`.

What are we missing?

**Comment by MollyMcEvilley** [comment]
There are records in ref_Populations where SystemPath is NULL (8.1) and where it is not NULL (8.2).
The sample code above performs the requirements defined by both 8.1 and 8.2.  The (forthcoming) commit that references this issue corrects the Step numbers as set -- they are 8.1 and 8.2 -- which may have clarified this if it had been correct in the first place.
