### ISSUE TITLE
8.5 - question about SystemPath usage in sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#286]
Most records in sample code related to Section 8 have `SystemPath = pop.SystemPath or pop.SystemPath is null` restriction.

![image-20200629-093431](https://user-images.githubusercontent.com/20728145/86550291-e3205280-bef6-11ea-8f05-f6784cf6628b.png)

Our developer is curious when we should and shouldn't have this restriction.

|Section 8 steps with ”SystemPath = pop.SystemPath or pop.SystemPath is null”|Section 8 steps without ”SystemPath = pop.SystemPath or pop.SystemPath is null”|
|----|----|
|8.1|8.5 (tlsa_Exit)|
|8.2|8.8 (tlsa_Exit)|
|8.3|  |
|8.4|  |
|8.6 (tlsa_Exit)|  |
|8.7 (tlsa_Exit)|  |

Please advise

**Comment by MollyMcEvilley** [comment]
SystemPath should appear in the WHERE clause where it's relevant.  It isn't relevant to 8.5 or 8.8 because all records in ref_Populations where pop.Core = 1 have a NULL value for SystemPath.
