### ISSUE TITLE
8 - duplicate '.' in the spec - Typo

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#289]
The next text has two periods.
![image-20200629-095907](https://user-images.githubusercontent.com/20728145/86552938-3c3fb480-befe-11ea-9f27-54c10702b9d6.png)

This occurs in:
Sections:

- 8.5
- 8.6
- 8.7
- 8.8

**Comment by MollyMcEvilley** [comment]
Thank you!  This was corrected for v1.0.
