### ISSUE TITLE
8.7 - SystemPath issues in both sample code and spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#290]
### Spec
![image-20200629-101302](https://user-images.githubusercontent.com/20728145/86553065-87f25e00-befe-11ea-9516-e5dff356cf08.png)

### Sample Code
![image-20200629-101339](https://user-images.githubusercontent.com/20728145/86553093-9771a700-befe-11ea-8dd0-5e0e8485a88d.png)

### Issues
Our developer thinks there are several issues.
**1. Spec:** `SystemPath = <>-1` - Possible issue, because it includes `SystemPath = [1..12]` that are already used for `ReportRow = [24..25]

Also, she is not sure if it is a value scenario because, according to the spec, `tlsa_Exit`.`SystemPath can only be [1..12]

![image-20200629-102102](https://user-images.githubusercontent.com/20728145/86553281-2088de00-beff-11ea-821b-1586c8f62a38.png)

**2. Sample Code:** `coalesce(pop.SystemPath, 0) + 23` - wrong code. Because according to spec, `lx.SystemPath` should be used, and also if `lx.SystemPath` is not between 1 and 12 then `ReportRow` must be hardcoded to 36.

**3. Sample Code** after the second issue, above, is fixed, please be sure to check `pop.SystemPath` that is used in `group by` - perhaps this also should be reworked.

**Comment by MollyMcEvilley** [comment]
I should not have combined 8.6 and 8.7 in the sample code and I have split them into separate steps.
The specs in both sections were unclear -- particularly for 8.7 -- and I've made edits to address that.

- ReportRow 23 is the average days by population, regardless of SystemPath, and the value for SystemPath in LSACalculated is always -1.
- ReportRow 36 is the average days for all LSAExit SystemPaths that are not -1.  Regrettably, the value in LSACalculated.SystemPath for the this row is ALSO -1.
