### ISSUE TITLE
8.9 - question about HHChronic

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#291]
### Sample Code
![image-20200629-113127](https://user-images.githubusercontent.com/20728145/86553505-cccac480-beff-11ea-9b45-726ab8b2afd4.png)

### Spec
![image-20200629-113149](https://user-images.githubusercontent.com/20728145/86553520-deac6780-beff-11ea-82c0-24791c5a6f76.png)

There is no `HHChronic` in the spec. How do we know that `HHChronic` should be included in conditions for `ref_populations` in the sample code? Please advise.

**Comment by MollyMcEvilley** [comment]
HHChronic isn't relevant -- deleting it from the sample code.
