### ISSUE TITLE
8.9 - discrepancy in tlsa_CohortDates usage

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#292]
### Sample Code
![image-20200629-114240](https://user-images.githubusercontent.com/20728145/86553701-5084b100-bf00-11ea-917b-db46c524b8bd.png)

### Spec
![image-20200629-114310](https://user-images.githubusercontent.com/20728145/86553723-609c9080-bf00-11ea-8579-9bd7465e707b.png)

### Issue
There is no mention in the spec about `or (n.ExitDate = cd.CohortStart and n.MoveInDate = cd.CohortStart)`.

A similar discrepancy appears in:

- 8.9
- 8.10.1
- 8.10.2
- 8.11
- 8.12.1
- 8.12.2
- 8.13
- 8.14.1
- 8.14.2

**Comment by MollyMcEvilley** [comment]
Corrections to the specs and to the code for 8.9-8.18 to reflect that a bednight is counted for RRH when the MoveInDate occurs on the ExitDate.
