### ISSUE TITLE
Section 8 - question about bed-nights

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#294]
Several sub-sections use `hmis_services`.
![image-20200629-150012](https://user-images.githubusercontent.com/20728145/86554018-47481400-bf01-11ea-9b3c-5b5476c6a531.png)

Our developer wonders if we must also check that `bn.DateProvided` is provided within project stay as it is done in step 5.8 as a result of one of our previous issue tickets:
![image-20200630-124505](https://user-images.githubusercontent.com/20728145/86554098-82e2de00-bf01-11ea-92d4-4698dac78ef6.png)

**Comment by MollyMcEvilley** [comment]
I am uncertain about the wisdom of having added this in the first place... We can't account for every possible instance of invalid data -- and a bednight that falls outside the range of an enrollment is invalid per the requirements of the data dictionary.  I am inclined to specify instead that in systems that allow the creation of invalid data, reporting procedures must filter it out...  

Flagging this for discussion on the call.

**Comment by MollyMcEvilley** [comment]
Leaving as is for now in the master branch.  I did create a tlsa_BedNight branch that addresses this by retrieving potentially relevant bed nights only once using the criteria you pointed out.  (It's primarily intended as a performance improvement, but it does impact this issue.)

**Comment by MollyMcEvilley** [comment]
Added a paragraph in section 3.3 HMIS Data Requirements and Assumptions per office hours conversation.
`Reporting procedures must exclude data which is inconsistent with the HMIS Data Standards and HMIS CSV Specifications.  Business logic for addressing a limited number of data issues is defined below, but it is not possible to anticipate or enumerate all of the potential inconsistencies.  In systems that – for whatever reason – allow users to create records that do not meet all criteria defined for HMIS data, it is the responsibility of developers to design reporting procedures such that they exclude this data.  `
