### ISSUE TITLE
8 - question about popID usage in sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#296]
### Spec
Almost each subsection of 8 has `HouseholdType and Population` table in the spec with `PopID` value. 

i.e.
![image-20200630-095247](https://user-images.githubusercontent.com/20728145/86554318-216f3f00-bf02-11ea-9e79-4b541d50ebb5.png)

### Sample Code

The interesting thing is that in the sample code:
**8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.14** - there is not a single restriction by PopID
8.9, 8.10, 8.12 - `pop.PopID between 0 and 10` in `where` condition
8.11 - `pop.PopID in (0,1,2,3,4,5,7,8,9,10)` in `where` condition
8.13 - `(pop.PopID in (3,6) or pop.popID between 145 and 148)` in `where condition
8.15, 8.16 - `pop.PopID in (0,1,2)` in `where` condition
8.17, 8.18 - `pop.PopID in (3,6)` in `where` condition

### Issue
Because half of the sub-steps have `PopID` restriction, it makes me think that subsections **8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.14** that do have tables with `PopID` in the spec, have issues in the sample code. And sample code must be updated with `PopID` restrictions.

**Comment by MollyMcEvilley** [comment]
There are other ways to limit the populations that are included -- for example, 8.1 and 8.2 use LOTH = 1 and the records in ref_Populations LOTH = 1 are the populations relevant to these sections.  8.3 to 8.5 use Core = 1, which correlates to the appropriate PopIDs.
