### ISSUE TITLE
**5.8.3 - sample code issue with project stays selection**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#299]
### Spec
![image-20200630-135840](https://user-images.githubusercontent.com/20728145/86555911-9fcde000-bf06-11ea-91ca-1667f7431a19.png)

### Sample Code
![image-20200630-135902](https://user-images.githubusercontent.com/20728145/86555938-b411dd00-bf06-11ea-9a1a-5268635bd8ca.png)

### Differences between sample code and spec:
1. Sample code doesn't have `ProjectType not in (1,8)` for:
a. `(hn.PreviousStreetESSH = 1 and hn.LengthOfStay in (10,11))`
b. `(hn.PreviousStreetESSH = 1 and hn.LengthOfStay in (2,3) and hn.LivingSituation in (4,5,6,7,15,25))`
2. Sample Code **doesn't have** any `MoveInDate` logic but spec has;
3. Spec has `ESSHStreetDate < EntryDate` restriction only for `ProjectType in (1,8,2)`. But sample code uses it for all project types
4. Spec logic is a bit confusing, `in ES/SH` is a mandatory restriction only for `LivingSituation in (1,18,16)`. Please confirm/correct.

![image-20200630-140407](https://user-images.githubusercontent.com/20728145/86556446-39e25800-bf08-11ea-940a-46aad9588f25.png)

**Comment by MollyMcEvilley** [comment]
1.a. and 1.b.  - regretfully updated the sample code (really hate it that ES/SH don't collect PreviousStreetESSH and are therefore potentially missing ESSHStreetTime if they spent 2 days with their sister before entry)

2. and 3.  - It's easier to express the criteria for using EntryDate vs MoveInDate in English than it is in SQL.  Everything before EntryDate is counted in 5.8.3.  Everything between entry and move-in for RRH is counted in 5.8.4.  

4. Updating spec to add ProjectType in (1,8) to the list shown above.

**Comment by MollyMcEvilley** [comment]
Re: this issue and issue #438, updates to the specs to regroup the criteria and to the code to more closely mirror the way the logic is expressed in the specs.  (Commits forthcoming)
