### ISSUE TITLE
5.8.4 - where does it belong?

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#300]
Does 5.8.4 in the sample code belong to `ES/SH/Street Dates from 3.917 Living Situation`? What part exactly? If it is for the highlighted section:

![image-20200701-100428](https://user-images.githubusercontent.com/20728145/86556613-aa897480-bf08-11ea-84cb-a7cfbd2273ca.png)

When there are several issue in sample code:
Project Type restriction is missing
for `MoveInDate is NULL and ExitDate is null`, **ESSHStreetDate** <= **LastActive** but in the sample code it is "<" instead of "<=".

**Comment by MollyMcEvilley** [comment]
Updating the code so this is all consistent -- now using < (LastActive + 1 day)  in the code, so it is effectively <= LastActive.

ESSHStreetDate <= ExitDate - 1 day (specs) is the same as ESSHStreetDate < ExitDate, (code) so i didn't change that.
