### ISSUE TITLE
**8.13 - discrepancy. Either spec or sample code has issues**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#301]
### Spec
![image-20200706-083916](https://user-images.githubusercontent.com/20728145/86663957-19b3a700-bfa3-11ea-92a8-54aa0141e153.png)

### Sample Code
![image-20200706-083840](https://user-images.githubusercontent.com/20728145/86664064-34861b80-bfa3-11ea-997a-81d2515a87d0.png)

### Issues
1. `pop.PopID not between 24 and 34` is always `true` because of `and (pop.PopID in (3,6) or pop.popID between 145 and 148)`. 
In other words, `(cd.Cohort <> 1 or pop.PopID not between 24 and 34)` means the same as `(cd.Cohort <> 1 or TRUE)` so it is always “true” condition. As it is a part-of-or-condition, then

`(
	(cd.Cohort <> 1 or pop.PopID not between 24 and 34)
	or
	(latest.Age is not null)
)`

is always TRUE. So it can be simply removed from the sample code.
2. Our developer is also curious about why `cd.Cohort <> 1` and `latest.Age is not null` are checked because she cannot find a corresponding description in the spec. Please advise.

**Comment by MollyMcEvilley** [comment]
Those are very weird anomalies -- possibly copy/paste errors.  Deleting everything after the last 'and' on the far left.
