### ISSUE TITLE
*9.1 - hmis_Project.OperatingEndDate is not used*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#303]
![image-20200706-092241](https://user-images.githubusercontent.com/20728145/86667599-a6ac2f80-bfa6-11ea-9665-c979599d2cd5.png)

`OperatingEndDate` is listed in `Relevant Data` section in the spec.

### Issue

1. **Spec:** `OperatingEndDate` is not used in `Record Selection` logic 
![image-20200706-092436](https://user-images.githubusercontent.com/20728145/86667847-e2df9000-bfa6-11ea-9752-450704882ff3.png)
2. **Sample Code:** `OperatingEndDate` is not used for Step 9.1
![image-20200706-092633](https://user-images.githubusercontent.com/20728145/86667974-086c9980-bfa7-11ea-8e16-9dba7484b6a3.png)
3. Or maybe the issue is that `OperatingEndDate` is listed under `Relevant Data` section in the spec?

**Comment by MollyMcEvilley** [comment]
OperatingEndDate is not relevant.  I'm not going to make any changes to the v1 Working Draft version of the specs because the OperatingEndDate wasn't listed in there -- but I am going to close this issue with today's version of the doc.

**Comment by michelleogburn** [comment]
Fixed in LSA Programming Specifications FY2019 v1 Working Draft.docx
