### ISSUE TITLE
9.1 - "EntryDate <= CohortEnd" usage in Sample Code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#304]
### Spec

According to the spec, **EntryDate** <= **CohortEnd** where Cohort = 20.

![image-20200706-094240](https://user-images.githubusercontent.com/20728145/86669001-09ea9180-bfa8-11ea-99ca-a17546fb74b4.png)

### Sample Code
![image-20200706-094715](https://user-images.githubusercontent.com/20728145/86669070-1cfd6180-bfa8-11ea-8c9a-555ea503285b.png)

### Issues in Sample Code
1. missing `n.EntryDate <= cd3.CohortEnd` where Cohort = 20
2. incorrect `n.EntryDate <= cd1.CohortEnd` restriction. This restriction eliminates enrollments started after `cd1CohortEnd` but active for Cohort = 20

After further checking, our developer found `CohortEnd` for Cohort = 1 and Cohort = 20 and they are the same. So `n.EntryDate` restriction doesn't impact the results. But it would be great to follow the spec and use the restriction for Cohort = 20.

**Comment by MollyMcEvilley** [comment]
Cohort 1 and Cohort 20 have identical CohortEndDates -- it's in the join to cd1, so the limitation already exists and it isn't necessary to repeat in the join to cd3 or in the where clause.
