### ISSUE TITLE
9.1 - CoCCode issues in Sample Code - critical

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#306]
### Spec
![image-20200706-101021](https://user-images.githubusercontent.com/20728145/86674617-b67b4200-bfad-11ea-8ad4-2d3274d5ffa2.png)

### Spec
![image-20200706-100939](https://user-images.githubusercontent.com/20728145/86674701-cc890280-bfad-11ea-92ae-c41e2103c3d7.png)

### Issue in Sample Code

_CoCCode_ should be completely revised and fixed because:
* _CoCCode_ is a part of MoveInDate logic now that it is checked for only ProjectType = [3,13]
* _CoCCode_ is left join nested query
* `"EnrollmentCoC record where InformationDate <= CohortEnd"` restriction is missing

**Comment by MollyMcEvilley** [comment]
Added joins to lsa_Report and hmis_EnrollmentCoC to check for a record <= ReportEnd (which is the same as CohortEnd for cd1 and cd3).
