### ISSUE TITLE
9.1 - question about HoH restriction

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#307]
### Section 3.3

![image-20200706-102819](https://user-images.githubusercontent.com/20728145/86676588-9f3d5400-bfaf-11ea-9105-b68efeb4174f.png)

In section 3.3 it is said that only valid enrollments must be included in the LSA (_Household has only one HoH, and HoH's Client Location = CoC selected_).

I wonder if this logic is TRUE for all LSA tables including section 9.1?

Want to confirm what we should do in section 9.1 with households:

1. without HoH.
2. with multiple HoHs
3. where HoH exited before HH member's enroll date

There is a `CoCCode` restriction for project stays selected in 9.1 so the developer wonders if we should also use "valid enrollments" logic that was described in section 3.3.

**Comment by MollyMcEvilley** [comment]
No, the logic for the DQ section differs because we want to identify the invalid data rather than exclude it.
