### ISSUE TITLE
4.27 has a chance to pull incorrect row for RRHMoveIn, PSHMoveIn

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#31]
I was comparing intermediate file results and noticed something.
Active enrollment PersonalID = 9039 has two records; one with a move in date and one without.  I kept getting a null returned because of active enrollment.HouseholdID 788626.  The subquery is correct in finding the two records in active enrollment for HoHID = 9039.  Since there are two records to return, I believe getting the record with the move in date is a crap shoot on how sql decides to order those.  Something will need to be added in order for a move in date to "win" that sort order.

(This is just one example FYI)

**Comment by MollyMcEvilley** [comment]
The code was prioritizing enrollments with no MoveInDate over enrollments with a MoveInDate in setting the status... If there was any enrollment without a MoveInDate, it was setting RRH/PSHMoveIn to 0 (no move-in).  It wasn't really a crap shoot, but it was wrong -- it should set the status based on the most recent MoveInDate if any exist, and only set the status to 0 if there is no MoveInDate for any enrollment.

![image](https://user-images.githubusercontent.com/6156815/47395191-a21ce600-d6f3-11e8-9608-e060713c1276.png)

[Corrected](https://github.com/MollyMcEvilley/LSASampleCode/commit/1aaaf6893ca779bc452b1fff172d6c5b8278782e).

**Comment by jbloescw** [comment]
I updated the code as it's shown.  I still get two rows returned and it is prioritizing the one that comes back with a NULL for both the RRHMoveIn and NULL for PSHMoveIn.  The problem happens once the left outer join is complete.  You can see that it's being set to a 10 now, but the NULL records win the sort order.
![image](https://user-images.githubusercontent.com/44415627/47438832-cf5ba980-d770-11e8-924b-f169055d83bb.png)

I ended up using the ROW_NUMBER function only select the latest move in date record.  Doing this only returns the one record with the latest move in date, even if it's null.  My intermediate file results now match with the HUD provided ones.
![image](https://user-images.githubusercontent.com/44415627/47441972-12208000-d777-11e8-9491-bad13af3aac4.png)
