### ISSUE TITLE
9.1 - SSNValid issues in Sample Code and Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#313]
### Spec
![image-20200706-132552](https://user-images.githubusercontent.com/20728145/86688209-be8dae80-bfba-11ea-9094-93ecaca521a1.png)

### Sample Code
![image-20200706-132626](https://user-images.githubusercontent.com/20728145/86688281-ce0cf780-bfba-11ea-98d9-b754819c120f.png)

### Issues
1. Sample code has `SSNDataQuality` condition, but spec doesn't
2. There is no condition for `SSNDataQuality = null` neither in spec nor in sample code so in some cases it can be mistakenly counted as **SSNValid = 1** and it can be a reason why `SSNDataQuality` is checked in `SSNMissingOrInvalid` 
![image-20200706-133543](https://user-images.githubusercontent.com/20728145/86688642-217f4580-bfbb-11ea-81ef-6e7f54547fe1.png)
3. Our developer thinks `c.SSN = ' '` can be removed from sample code because such an SSN will be counted as SSNValid = 0 because of `LEN(c.SSN) <> 9`
4. Sample code has SSN compared with `123456789` but there is no such rule in the spec

**Comment by bayboos** [comment]
For #4 (and some other conditions present in the code, but not in the specs) - those are "hidden" under the "SSA guidelines" phrase used in the specs. Those "guidelines" are more complex and more specific, but this code allows to rule out the vast majority of invalid SSN numbers.

**Comment by MollyMcEvilley** [comment]
1.  The line above your specs screenshot says:
`SSNValid is null for any client record where SSNDataQuality in (8,9).`
2.  We don't care if SSNDataQuality is NULL -- in SSNNotProvided, we're counting SSNs that were omitted for a reason (8,9).  In SSNMissingOrInvalid, we're counting SSN's that are not valid under the rules.  Everything else counts as valid.
3.  (Not changing this, but point taken.)
4.  Updated the specs.
