### ISSUE TITLE
7.6.1 comparing start and end dates in the "prior" subquery

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#314]
In the 7.6.1. query, the "prior" subquery contains this condition check:

`and dateadd(dd, 6, hhid.ExitDate) >= hhid.EntryDate) is null`

Since both EntryDate and ExitDate are coming from the same source (a row in tlsa_HHID table), ExitDate + "6 days" seems to always be greater than (or equal to) EntryDate. Unless the intended condition was to compare ExitDate from the "**prior**" table (which is in fact another row from the tlsa_HHID table, but can - and probably should - be different from the "hhid" one):

`and dateadd(dd, 6, prior.ExitDate) >= hhid.EntryDate) is null`

Please correct or explain; any answer will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
yes, the ExitDate is supposed to come from prior.  THANK YOU!
