### ISSUE TITLE
9.2 - question about distinct EnrollmentID

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#315]
Both spec and sample code use `distinct EnrollmentID`
![image-20200706-123457](https://user-images.githubusercontent.com/20728145/86799775-2843a200-c027-11ea-969c-5a7e4ab14580.png)

Why is `distinct` used? There is no way to insert duplicate Enrollments in the `dq_Enrollment` table. What are we missing?

FYI: `distinct EnrollmentID` is used for:

- NoCoC
- AdultHoHEntry1/3
- ClientEntry1/3
- ClientExit1/3
- HoHPermToPH1/3
- DisablingCond1/3
- LivingSituation1/3
- LengthOfStay1/3
- HomelessDate1/3
- TimesHomeless1/3
- MonthsHomeless1/3
- DV1/3
- Destination1/3
- MoveInDate1/3

**Comment by MollyMcEvilley** [comment]
Habit.  An extra DISTINCT doesn't cost anything when values are already unique and indexed -- a missing DISTINCT can be disastrous.
