### ISSUE TITLE
9.2 - SSNNotProvided - Spec may require update

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#316]
### Sample Code
![image-20200706-131123](https://user-images.githubusercontent.com/20728145/86800614-11ea1600-c028-11ea-96ec-9e8466210635.png)

### Spec
![image-20200706-131241](https://user-images.githubusercontent.com/20728145/86800671-21695f00-c028-11ea-8a5e-b79a0d926538.png)

### Differences

- Sample Code uses `SSNValid is null` restriction. That is logical so no need to connect **hmis_Client** table and check SSNDataQuality again - it is already stored in `SSNValid`.
- If prev comment makes sense, then SSNNotProvided table should be changed similar to `UnduplicatedClient1/3` section table structure.

**Comment by MollyMcEvilley** [comment]
I missed closing this issue, but this change has been made in the current version of the specs.
