### ISSUE TITLE
*9.2 - SSNMissingOrInvalid - Spec should be corrected*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#317]
### Sample Code
![image-20200706-131923](https://user-images.githubusercontent.com/20728145/86801706-2da1ec00-c029-11ea-8f9b-1e16e72b3aaf.png)

### Spec
![image-20200706-132010](https://user-images.githubusercontent.com/20728145/86801797-43afac80-c029-11ea-9492-9b82d2612b5d.png)

### Issue
**Either spec or sample code has an issue** because `SSNValid = 0` in sample code covers not only `SSNDataQuality NOT in (8,9) or is NULL` but also in all other SSN issues:

![image-20200707-093724](https://user-images.githubusercontent.com/20728145/86802093-82ddfd80-c029-11ea-89f3-3e2470df9d7a.png)

**Comment by MollyMcEvilley** [comment]
I missed closing this at the time the update to the specs was made, but the hmis_Client rows have been removed from the table in the specs -- only the SSNValid column in dq_Enrollment is required to identify these records.  (This is consistent with the code.)

![image](https://user-images.githubusercontent.com/6156815/89586499-cfc21900-d80d-11ea-9ecf-c1478ba12a21.png)
