### ISSUE TITLE
*9.2 - Race1/3 issue in the Spec*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#318]
### Spec
![image-20200707-095752](https://user-images.githubusercontent.com/20728145/86802431-e10ae080-c029-11ea-9659-5a7b6dfddb7a.png)

### Sample Code
![image-20200707-095824](https://user-images.githubusercontent.com/20728145/86802501-f122c000-c029-11ea-9b72-d044d4e7e488.png)

### Issue
There is no Race column in hmis_Client table.

**Comment by MollyMcEvilley** [comment]
This has been addressed in the specs document:
![image](https://user-images.githubusercontent.com/6156815/89586605-0e57d380-d80e-11ea-8af5-354e61e78795.png)
