### ISSUE TITLE
4.17 Get ES/SH/Street Episodes

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#32]
Our developer found a major issue in the query that counts CH episodes. According to spec:

> Each record in ch_Episodes represents an uninterrupted series of ES/SH/Street dates identified in the previous step.

In the sample upload file chTime.csv, PersonalID=86363. The dates are:
2015-09-09 00:00:00
2016-10-24 00:00:00
2016-10-25 00:00:00
2017-04-04 00:00:00
2017-04-05 00:00:00
2017-04-06 00:00:00
2017-04-07 00:00:00
2017-04-08 00:00:00
2017-04-09 00:00:00
2017-04-10 00:00:00
2017-04-11 00:00:00
2017-04-12 00:00:00
2017-04-13 00:00:00
2017-04-14 00:00:00
2017-04-15 00:00:00
2017-04-16 00:00:00

Reviewing these dates, we would expect this to be calculated as 3 episodes: 1 day, 2 days and 13 days. However, after the sample code processes this data, chEpisodes.csv returns:

|PersonalID|episodeStart|episodeEnd|episodeDays|
|-------|--------|--------|--------|
|86363|2015-09-09 00:00:00|2016-10-25 00:00:00|413|
|86363|2016-10-24 00:00:00|2016-10-25 00:00:00|2|
|86363|2016-10-24 00:00:00|2016-10-25 00:00:00|13|

To fix this issue we can replace:
`inner join sample_code.ch_Time e on e.PersonalID = s.PersonalID  and e.chDate > s.chDate`

with:
`inner join sample_code.ch_Time e on e.PersonalID = s.PersonalID  and e.chDate >= s.chDate`

**Comment by MollyMcEvilley** [comment]
thank you!
