### ISSUE TITLE
9.1 - Status1 issues in Sample Code and Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#321]
### Spec
![image-20200706-135724](https://user-images.githubusercontent.com/20728145/87119264-59dc8900-c232-11ea-9971-775c43c6b457.png)

### Sample Code
![image-20200706-135507](https://user-images.githubusercontent.com/20728145/87119303-72e53a00-c232-11ea-81b5-a9cf4e8717dc.png)

### Issues

1. **Spec:** missing `or c.DOBDataQuality is null` restriction
2. **Spec:** `when x.ExitDate < cd1.CohortStart then null` is not listed in allowed restrictions
3. **Sample Code:** `<= n.EntryDate` is used, but in the Spec it is said to compare with `the later of EntryDate or CohortStart (AgeDate)`
4. A bit curious about `DOBDataQuality in (8, 9)` and `DOBDataQuality not in (1, 2)`. `DOBDataQuality not in (1, 2)` already includes `DOBDataQuality in (8, 9)` and also includes `DOBDataQuality = 99`.

**Comment by MollyMcEvilley** [comment]
1.  Specs:  Added _DOBDataQuality_ is NULL condition to specs for **Status1** and **Status3**.
2. Specs:  Added _ExitDate_ < **CohortStart** --> NULL value for **Status1**
3. Code:  I updated the code to check for ages >= 105 at both _EntryDate_ and **CohortStart** and count DOB as unknown if either are true.   If there is any difference, the age will be higher at the later of the two dates, so regardless of whether _EntryDate_ or **CohortStart** is later, counting the DOB as unknown if either condition is met effectively uses the later of the two dates.  (This was already the case in the check for age >= 18 for adults.) 
4. Specs and Code:  Redundant?  Redundant.  I streamlined these in both the specs and code.

Will close issue with forthcoming commits.
