### ISSUE TITLE
9.1 - Status3 issues in Sample Code and Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#322]
### Spec
![image-20200706-151041](https://user-images.githubusercontent.com/20728145/87119482-f737bd00-c232-11ea-91eb-6ee906c68e3c.png)

### Sample Code
![image-20200706-151051](https://user-images.githubusercontent.com/20728145/87119493-09196000-c233-11ea-9905-9c56ede779d1.png)

### Issues

1. **Spec:** missing `or c.DOBDataQuality is null` restriction
2. **Sample Code:** `<= n.EntryDate` is used, but in the Spec it is said to compare with `the later of EntryDate or CohortStart (AgeDate)`
3. A bit curious about `DOBDataQuality in (8, 9)` and `DOBDataQuality not in (1, 2)`. `DOBDataQuality not in (1, 2)` already includes `DOBDataQuality in (8, 9)` and also includes `DOBDataQuality = 99`.

**Comment by MollyMcEvilley** [comment]
Addressed in the commits shown above -- see notes for #321.
