### ISSUE TITLE
*9.2 - "inner join lsa_Report rpt on rpt.ReportStart >= n.ExitDate or n.ExitDate is null" issue in Sample Code*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#329]
### Issue
Instead of 

`inner join lsa_Report rpt on rpt.ReportStart >= n.ExitDate or n.ExitDate is null`

must be

`inner join lsa_Report rpt on rpt.ReportStart <= n.ExitDate or n.ExitDate is null`

7 places should be fixed:

1. `DisablingCond1`
2. `LivingSituation1`
3. `LengthOfStay1`
4. `HomelessDate1`
5. `TimesHomeless1`
6. `MonthsHomeless1`
7. `DV1`

Follow-up question: Why do we need `lsa_Report` at all? We already have `Status1 is not null` restriction to select only enrollments active within `Cohort = 1`

**Comment by MollyMcEvilley** [comment]
The follow-up question was a very salient one... the joins to lsa_Report may have been leftover code from last year or something I wrote before creating the Status1 column -- regardless, they're not necessary and I deleted them.
