### ISSUE TITLE
4.19 Updated Selected CHTime and CHTimeStatus Values

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#33]
Looks like we've found another discrepancy between spec and code

The spec reads:

> For clients who do not meet CH time criteria, the LSA distinguishes between clients whose data appear to be complete and those that do not. 
• Set CHTimeStatus = 99 where (CHTime in (0,270) or CHTimeStatus = 3) and for any ch_Enrollment whereDateToStreetESSH > EntryDate 
• LivingSituation in (8,9,99) or is null
• LengthOfStay in (8,9,99) or is null
• ProjectType in (1,8) and DateToStreetESSH is null
• LivingSituation in (1,16,18) and DateToStreetESSH is null
• LengthOfStay in (10,11) and (PreviousStreetESSH is null or (PreviousStreetESSH = 1 and DateToStreetESSH is null))
• LivingSituation in (4,5,6,7,15,24) and LengthOfStay in (2,3) and (PreviousStreetESSH is null or (PreviousStreetESSH = 1 and DateToStreetESSH is null))
• TimesHomelessPastThreeYears in (8,9,99) or is null
• MonthsHomelessPastThreeYears in (8,9,99) or is null

Why

> where (CHTime in (0,270) or CHTimeStatus = 3)

In code sample:
https://github.com/MollyMcEvilley/LSASampleCode/blob/1aaaf6893ca779bc452b1fff172d6c5b8278782e/LSASampleCode.sql#L1235-L1237

ChTime also can be 365, but in spec: 0-270, condition CHTime <> 400 also includes 365. 
Why is CHTimeStatus not in (1,2), instead of CHTimeStatus = 3 as it is in the spec?

And part two... in spec:

> • Set CHTimeStatus = 99 where (CHTime in (0,270) or CHTimeStatus = 3) and for any ch_Enrollment where DateToStreetESSH > EntryDate 
• LivingSituation in (8,9,99) or is null

It seems "DateToStreetESSH > EntryDate" is a mandatory condition, but the code sample reads:
https://github.com/MollyMcEvilley/LSASampleCode/blob/1aaaf6893ca779bc452b1fff172d6c5b8278782e/LSASampleCode.sql#L1219-L1220

**Comment by MollyMcEvilley** [comment]
Aligned the code with the specs in the WHERE clause (CHTime in (1,270) or CHTimeStatus = 3).  This is equivalent to 'where CHTime <> 400 and CHTimeStatus not in (1,2)' and will not result in any change to final output, but there's no point in the inconsistency / confusion.

'DateToStreetESSH > EntryDate is not a mandatory condition... There is a formatting issue / missing return in the specs that will be corrected today.  This:
![image](https://user-images.githubusercontent.com/6156815/47420611-d8d31a80-d74c-11e8-80e7-7871a4ff761c.png)
Should look like this:
![image](https://user-images.githubusercontent.com/6156815/47420719-189a0200-d74d-11e8-9a70-c0a5eabe8ce6.png)
