### ISSUE TITLE
Errors in one of the latest code changes

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#331]
Hello

It seems like there are two errors in one of the code changes comitted latey:

https://github.com/HMIS/LSASampleCode/commit/6f29414d351d9104aa3c44cefd0fd2f70c12789b#diff-ce68a17fa8dc377d26c1dc13d6d5ccd7

In this commit:
- the note about code changes refer to seps 7.7.1-7.7.3 while in fact the edited steps are 7.7.3-7.7.5; and
- while step 7.7.3 had the joined table's alias edited in both the update part and the join clause (from **pshpre** to **psh**), setps 7.7.4 and 7.7.5 had the alias changed in the join clause only (update part was left unchanged) causing SQL errors.

**Comment by MollyMcEvilley** [comment]
see #359
