### ISSUE TITLE
7.6.2.a - TrackingMethod issue in Sample Code

### ISSUE THREAD

**Issue by kmaschi** [abtassociates/LSASampleCode#332]
In step 7.6.2.a, tlsa_HHID enrollments not related to night-by-night ES, the sample SQL checks for equality where TrackingMethod equals three. This will exclude any rows where TrackingMethod is null which appears to be an error.

https://github.com/HMIS/LSASampleCode/blob/90fa8686e9ef09a7862fa892ce32cb9c0189eb8c/7_1%20to%207_8%20LSAExit.sql#L269-L284

In the HMIS specification tracking method is only required when the HMIS project's type equals one, otherwise nulls are allowed. These nulls are carried over into the tlsa_HHID table.

The written LSA specifications appear to indicate that this step should include all enrollments that are not night-by-night ES.

![image](https://user-images.githubusercontent.com/20146449/87340838-a2d45c00-c516-11ea-899c-73929d15d5ea.png)

It appears as though this condition should factor in nulls, for example:
`possible.TrackingMethod <> 3 OR possible.TrackingMethod IS NULL`

**Comment by MollyMcEvilley** [comment]
This is a good catch -- thank you.
