### ISSUE TITLE
***3.5 tlsa_Enrollment - [Exit1Age/Exit2Age] issues in spec and sample code***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#333]
This is a follow-up to #221 following the recent update to the specs.

The first two rows for **Exit1Age/Exit2Age** were changed.
![image-20200710-124711](https://user-images.githubusercontent.com/20728145/87544338-1ed7bc80-c65b-11ea-83ba-01d605168c68.png)

The sample code is:
![image-20200710-125028](https://user-images.githubusercontent.com/20728145/87544394-36af4080-c65b-11ea-9b16-c2aaa9604a45.png)

The issue is that the sample code still uses `n.ExitDate < cd.CohortStart` but the spec was corrected.

**Comment by MollyMcEvilley** [comment]
This has been corrected in the commit referenced above.
![image](https://user-images.githubusercontent.com/6156815/89600859-0f4e2c80-d831-11ea-8b76-8a9a134928fb.png)
