### ISSUE TITLE
***5.10  - needs corrections***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#334]
This is a follow-up to #252 

The spec was created but now it is:
![image-20200714-095152](https://user-images.githubusercontent.com/20728145/87544987-2481d200-c65c-11ea-9dc1-67663c8c6488.png)

Since it is hard to compare with Sample Code, our developer put each scenario in a table:
![image-20200714-102747](https://user-images.githubusercontent.com/20728145/87545110-5430da00-c65c-11ea-8c9f-15292d3f284c.png)

Assuming the spec is correct, then **there are now issues in the sample code**. Sigh...

**1. row=393**. Instead of `hn.LengthOfStay in (2,3)` must be `hn.LengthOfStay in (10,11)`
**2. row=394**. `or hn.PreviousStreetESSH not in (0,1)` is not mentioned in the spec so this restriction must be removed
**3. row=395**. Instead of `hn.LengthOfStay in (10,11)` must be `hn.LengthOfStay in (2,3)`
**4. row=396**. `or hn.PreviousStreetESSH not in (0,1)` is not mentioned in the spec so this restriction must be removed
#### Illustration for issues 1-4
![image-20200714-111819](https://user-images.githubusercontent.com/20728145/87545619-1b453500-c65d-11ea-8c94-83b33dbb224f.png)

**5. row =398**. `LivingSituation in (1,16,18)` must be with mandatory `ProjectType is not in (1,8)`
**6. row=400**. Instead of `and hn.LengthOfStay in (2,3)` must be `and hn.LengthOfStay in (10,11)`
**7. row=402**. Instead of `and hn.LengthOfStay in (10,11)` must be `and hn.LengthOfStay in (2,3)`
#### Illustration for issues 5-7
![image-20200714-110915](https://user-images.githubusercontent.com/20728145/87546010-b4744b80-c65d-11ea-8d05-cb74c375ea7d.png)

**Comment by MollyMcEvilley** [comment]
These are magnificent tables.

Notes to self for review still in progress -- so far, in every case, it appears that the code is correct and the specs should be updated.
1.  Updating specs, which are wrong.  The code is correct -- HMIS LengthOfStay values are counter-intuitive -- 10 and 11 are 0-6 days, while 2 and 3 are 7-89 days.
2.  Updating specs -- the code is more completely correct -- a NULL value would be wrong and so would any value that is not 0 or 1.
3.  Same as 1.
4.  Same as 2.
5.  Updating specs -- the code is correct -- if LivingSituation is in (1,16,18), project type is not relevant.
6.  Same as 1.
7.  Same as 1.
![image](https://user-images.githubusercontent.com/6156815/89602954-fdbb5380-d835-11ea-81f6-36b8c06f0475.png)

**Comment by MollyMcEvilley** [comment]
Edits to the specs shown above have been committed.  (https://github.com/HMIS/LSASampleCode/commit/8a4e004ee774bcda70f6cd2064e749ad4bf70cdc)
