### ISSUE TITLE
**7.4 - HHVet follow-up, one issue missed**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#336]
This is a follow-up to #269 

This was overlooked:
![image-20200710-094820](https://user-images.githubusercontent.com/20728145/87546702-d15d4e80-c65e-11ea-8e30-0d31f03923fa.png)

Our developer agrees that in `inner join` more than 1 client in Household can be selected. So single `tlsa_Exit` record will be update as many times as many enrollments are selected in `inner join`.

But

```
(select max(case when c.VeteranStatus = 1 then 1 else 0 end)
			from hmis_Client c
			where c.PersonalID = hh.PersonalID)

```
is selected one time per each update. It is only for one client and max() is completely useless in this case. 

And the issue is that after query is executed `tlsa_Exit` will have `VeteranStatus` from last found Household member, not the max() of all HH members,

So she thinks:

- either `inner join` logic should be reworked to return 1 row with max(VeteranStatus) of HH members, and in this case each `tlsa_Exit` record will be updated only once
- or `HHVet` should be reworked to:

```
HHVet = GREATEST( HHVet, (select case when c.VeteranStatus = 1 then 1 else 0 end
			from hmis_Client c
			where c.PersonalID = hh.PersonalID))
```

**Comment by MollyMcEvilley** [comment]
This might be a difference in flavors of SQL?  SQL Server would benefit from but doesn't have a GREATEST function -- the MAX function returns the max veteran status of all clients in the household and not individually for each client record.
