### ISSUE TITLE
***7.7 - issues in dates comparison, follow-up***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#337]
This is a follow-up to #256 

The first issue still exists because:

- in spec there is `EntryDate > tlsa_Exit.LastInactive`
- but in sample code `ExitDate > ex.LastInactive`

**Comment by MollyMcEvilley** [comment]
This is a confusing discrepancy, but ultimately, it won't make any difference -- all enrollments in the system path for exiters will have an exit date, and if any part of the enrollment is after **LastInactive**, all of the enrollment is after **LastInactive**.
