### ISSUE TITLE
*9.2 - MoveInDate3 - issues in Sample Code*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#338]
### Spec
![image-20200708-120145](https://user-images.githubusercontent.com/20728145/87547562-2188e080-c660-11ea-865e-94b9927c244d.png)

### Sample Code
![image-20200708-120726](https://user-images.githubusercontent.com/20728145/87547591-31a0c000-c660-11ea-9ade-d65ff3399f5f.png)

### Issues

1. For MoveInDate3 we should use Cohort = 20. Cohort = 20 is period between [ReportStart - 3 years] and [Report End]. It is completely incorrect to use `x.ExitDate >= rpt.ReportStart` for MoveInDate3 in Sample Code.
2. In the spec it is said `Between CohortStart and CohortEnd` so `x.ExitDate < rpt.ReportEnd` should be replaced with `x.ExitDate <= rpt.ReportEnd`

### Question
Why do you use `coalesce(…, 0)` for `MoveInDate1` and `MoveInDate3`? We do not need it for `COUNT()`. Also, there is no `coalesce()` for other parameters calculated in 9.2

**Comment by MollyMcEvilley** [comment]
Thank you.  All good points. Commit forthcoming.
![image](https://user-images.githubusercontent.com/6156815/93491009-2fb0e280-f8d7-11ea-8afa-8bf166b6303c.png)
