### ISSUE TITLE
*Section 7 - DateDeleted restriction is missing in Sample Code*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#343]
DateDeleted restriction is missing for:

- step = 7.1 - `hmis_EnrollmentCoC` in nested query in Left Join
- step = 7.3 - `hmis_EnrollmentCoC`

**Comment by MollyMcEvilley** [comment]
This might have been a dupe or I might have forgotten to close it when I added the DateDeleted restrictions... but it has been addressed.
