### ISSUE TITLE
*5.14 - AHARRRH - issue in sample code*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#344]
### Spec
![image-20200710-084917](https://user-images.githubusercontent.com/20728145/87550393-d7a1f980-c663-11ea-839e-cd8cfe045a41.png)

### Sample Code
It was reported that sample code was fixed:
![image-20200710-085042](https://user-images.githubusercontent.com/20728145/87550498-f1dbd780-c663-11ea-9171-b1b245f1f2e0.png)

but in fact the issue wasn’t fixed because `ExitDate = ReportStart and MoveInDate = ReportStart` is still missing in the code.
![image-20200710-085140](https://user-images.githubusercontent.com/20728145/87550587-10da6980-c664-11ea-9a86-1d7943ebe3dc.png)

**Comment by MollyMcEvilley** [comment]
In 5.14.1 (in screenshot above), the AHAREST value is set based solely on ES/SH/TH enrollments, so the conditions specific to RRH aren't relevant.

The correction was only needed for 5.14.2, 5.15.2, 5.16.2 (AHARRRH, AdultRRH, AHARHoHRRH, respectively).  I checked to confirm that those statements were corrected on 7/2/2020.

(If I'm misunderstanding something, please re-open this issue.)
