### ISSUE TITLE
7.7 - question about 365 days for SystemPath = -1

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#349]
This is the updated spec for 7.7:
![image-20200714-142112](https://user-images.githubusercontent.com/20728145/87552010-f99c7b80-c665-11ea-94eb-0da3e8c9faed.png)

Previously for section 5.10 365 days were replaced with 1 year
![image-20200714-142246](https://user-images.githubusercontent.com/20728145/87552080-0f11a580-c666-11ea-8e7f-304278d95cae.png)

For section 7.7, should 365 days and not 1 year be used?

**Comment by MollyMcEvilley** [comment]
Yes -- the specs and the code match so no change...
