### ISSUE TITLE
4.13 Get Chronic Homelessness Date Range for Each HoH/Adult - code problem

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#35]
A restriction seems to be missing.

According to spec:

> LastActive – For each record in tmp_Person where HoHAdult > 0:

In the code we see:
https://github.com/MollyMcEvilley/LSASampleCode/blob/b20ecb8fe54394498b739d006e2cf36a881e8c03/LSASampleCode.sql#L1005-L1007

However, tmp_Person.LastActive also should be calculated only for HoHAdult > 0. Now it is calculated for **all** clients in tmp_Person.

**Comment by MollyMcEvilley** [comment]
To align with the specs, making the changes to the code listed below.

- Move SET of **HoHAdult** and **Age** from section 4.11 to 4.12 (no change to intermediate or final output)
- Move SET of **LastActive** from section 4.11 to 4.13 (change to intermediate output only -- LastActive  will no longer be set for non-HoH children).
