### ISSUE TITLE
*7.1 - issue with Projects limitation for LSAScope = 1*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#350]
![image-20200715-123431](https://user-images.githubusercontent.com/20728145/87552249-497b4280-c666-11ea-94f8-d5e510519dcf.png)

Here are project type restrictions:

- **Project-Focused** are also only ES, SH, TH, RRH, and PSH
- **Systemwide** includes ES, SH, TH, RRH, PSH, and also OPH
- for **qualifying exits (section 7.1)** only continuum ES, SH, TH, RRH, or PSH projects are used;

Thus, for **qualifying exits if we run Systemwide version we must exclude OPH project stays**.

There is a note in the Spec that introduces this section. **But there is no project stay restriction in the sample code**, only `and (rpt.LSAScope = 1 or p.ProjectID is not null)`.

**Comment by MollyMcEvilley** [comment]
There aren't any OPH project stays in tlsa_HHID, so that shouldn't be an issue.
