### ISSUE TITLE
7.1 - missing requirement for CoCCode

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#353]
Last one, @MollyMcEvilley , until it isn't ;)

### Spec
![image-20200715-124958](https://user-images.githubusercontent.com/20728145/87552997-4896e080-c667-11ea-87c1-863c982e9ab4.png)

### Sample Code
![image-20200715-125040](https://user-images.githubusercontent.com/20728145/87553037-58aec000-c667-11ea-9e71-4a3a6776ffa4.png)

I wonder if `coc.InformationDate <= hhid.ExitDate` restriction should be added to the selected block?

**Comment by MollyMcEvilley** [comment]
See issue #294 -- I don't think that such a record could possibly be construed as valid HMIS data.  We cannot incorporate every possible type of invalid data into the specs and/or sample code.

**Comment by MollyMcEvilley** [comment]
Closing this per call last week
