### ISSUE TITLE
7.7.4 Sample code Issue

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#354]
Good morning,
In sample code 7.7.4 the following part:
'left outer join tlsa_HHID psh on psh.ProjectType = 3
			and psh.HoHID = ex.HoHID and psh.EntryDate <= qx.ExitDate and psh.ExitDate > ex.LastInactive
			and (psh.ActiveHHType = ex.HHType)'

should the condition is psh.Exit1HHType=ex.HHType?
According to the report spec corresponding section, for Exit Cohort=-1, need to use Exit1HHType.
Please take a look. Thank you. 

Best,
Chen

**Comment by MollyMcEvilley** [comment]
Thank you!  This was addressed in a commit on 7/13/2020, but I neglected to close the issue at that time.

![image](https://user-images.githubusercontent.com/6156815/91461080-96059080-e856-11ea-8ed4-ffacd84587f3.png)
