### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by k-adunn** [abtassociates/LSASampleCode#355]
1.	sysStatus is set to 4 if ProjectType = 8 (safe haven) or project type 1 and tracking method is 0. The code only sets sysStatus to 7 when ProjectType = 8. Is this correct?
2.	This would affect ESDays, ESTDays, SystemDaysNotPSHHoused, SystemHomelessDays, and TotalHomelessDays on 6.15. Should Safe Haven days be counted on those?
3.	Enrollment – 11/1/17 – 11/30/17. Report range 10/1/18 – 9/30/19. Should this Household be counted in LSAExit?

**Comment by k-adunn** [comment]
Additional question: Re: 6.14/6.15 Does this mean 3.917 days is doubled?

**Comment by MollyMcEvilley** [comment]
I apologize -- there were edits to 6_1 to 6_19 LSAHousehold.sql, but I didn't make them in the master branch. Forthcoming commit addresses the issues in the master branch code.

- 6.13.1 - Dates should be inserted to sys_Time with sysStatus = 4 for Safe Haven and Entry-Exit ES. There was a bug in the sample code -- it omitted the Safe Haven project type in this step -- that is addressed in the forthcoming commit.  (This step also inserts dates for TH / **sysStatus** = 3).
- 6.13.2 - Individual bednights in night-by-night ES are inserted to sys_Time with **sysStatus** = 4.
- 6.15 - Safe Haven dates (and all dates with **sysStatus** = 4) should be included in all of the counts that you mentioned (ESDays, ESTDays, SystemDaysNotPSHHoused, SystemHomelessDays, and TotalHomelessDayESDays).  This will happen with the sample code now that the Safe Haven project type is included in 6.13.1.
- 6.14.2 - Dates that are AFTER **LastInactive** AND on or after DateToStreetESSH AND prior to the EntryDate for the associated enrollment AND that aren't already in sys_Time are inserted to sys_Time with **sysStatus** = 7.  This is regardless of project type.
- If the report period is 10/1/2018-9/30/2019, then the cohort period for cohort (-1) is 10/1/2017-9/30/2018.  A household with an exit on 11/30/2017 would be included in cohort -1 (as long as the exit meets other criteria).
