### ISSUE TITLE
hmis_Services - question about project stay restriction

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#356]
This is related to #262 

@MollyMcEvilley wrote:

> I added a note to the specs section 6.12 to clarify that a BednightDate must be valid (i.e., fall between EntryDate and ExitDate if there is one) in order to be relevant

`7.6.2.b` doesn't have a restriction that `bn.DateProvided` must be between EntryDate and ExitDate. Don't we need a restriction?
![image-20200720-102410](https://user-images.githubusercontent.com/20728145/87960959-e6c0e700-ca69-11ea-9200-d2cbed7de373.png)

Also, there is no `bn.DateProvided between EntryDate and ExitDate` restriction in many places in section 8.

**Comment by michelleogburn** [comment]
@MollyMcEvilley , I suspect this issue will be similar to others... there is an expectation that the data should be valid before getting to this point. Correct?

**Comment by MollyMcEvilley** [comment]
yes -- although there is a branch that would address this concern to discuss on today's call...
