### ISSUE TITLE
***5.8.5 - issue in sample code***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#357]
A very important `AND PersonalID = e.PersonalID` restriction is missing
![image-20200720-125021](https://user-images.githubusercontent.com/20728145/87961221-44edca00-ca6a-11ea-887e-96ad4f7da42c.png)

**Comment by MollyMcEvilley** [comment]
As we talked about on the call, the highlighted section selects records that don't meet the criteria for inclusion and the line directly above it says to select only the PersonalIDs that aren't in that list... So unless I'm missing something (certainly possible), I think the code is doing what it's supposed to do.
