### ISSUE TITLE
5.8.5 - issue with 7-days period - Sample code problem

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#358]
Issue in sample code: must be +7 instead of -7
![image-20200721-102106](https://user-images.githubusercontent.com/20728145/88084782-c06a7c80-cb39-11ea-876e-0607be1ca5b3.png)

**Comment by MollyMcEvilley** [comment]
I think this is doing what it's supposed to...

The code is building a list of gaps of less than 7 days between ESSHStreetDates.

ch_Include s (for start) gets ESSHStreetDates where there is NOT another one the next day (PersonalID is not in the list of PersonalIDs in the subclause).

ch_Include e (for end)  gets ESSHStreetDates where there IS an s.ESSHStreetDate in the seven days before (-7).

For each s that falls less than 7 days before than an e, the dates between the two are counted as ESSHStreetDates.
