### ISSUE TITLE
4.19 Follow-up

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#36]
An additional question about 4.19... hot off the presses:

Spec shows 

> (CHTime in (0,270) or CHTimeStatus = 3) 

but code sample has 
https://github.com/MollyMcEvilley/LSASampleCode/blob/b20ecb8fe54394498b739d006e2cf36a881e8c03/LSASampleCode.sql#L1241

So, should we exclude CHTime=0?

**Comment by michelleogburn** [comment]
Just noticed this was commented on by someone else:
https://github.com/MollyMcEvilley/LSASampleCode/commit/7e642bf3266e1c4475296449fe9a57e650fea6db

**Comment by MollyMcEvilley** [comment]
Thank you!
