### ISSUE TITLE
7.4 Set HHVet sample code issue

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#360]
Good afternoon,

The current version, there is an issue in section 7.4 when set HHVet value for Household with multiple members. To be more specific:
update ex
	set HHVet = (select max(case when c.VeteranStatus = 1 then 1 else 0 end)
			from hmis_Client c
			where c.PersonalID = hh.PersonalID)
.....
inner join (....
		) hh on hh.HouseholdID = ex.QualifyingExitHHID and hh.ExitCohort = ex.Cohort

hh is using HouseholdID to link, but when set HHVet it using PersonID, even if there this a Max function, it won't work here. If there are more than one member in the household, it will just set HHVet for one member randomly.
Please take a look at this part. Thank you.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
Thank you, Chen.  I would not ever have found this one without your help and Michelle's.
