### ISSUE TITLE
***7.5 - discrepancy with EnrollmentCoC usage***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#361]
Follow up to #275 . A fix for the issue caused new problems

### New Issue 1
In the spec the restriction is

![image-20200724-123327](https://user-images.githubusercontent.com/20728145/88755308-b9350700-d115-11ea-8956-8fa1f939e228.png)

so `tlsa_Exit.HHType` is compared with `ActiveHHType`/`Exit1HHType`/`Exit2HHType` by `tlsa_Exit.Cohort
`
But in sample code this block has many issues:

- two cases use `last.ExitCohort` to compare
- qx and last fields are mixed

![image-20200724-123712](https://user-images.githubusercontent.com/20728145/88755573-509a5a00-d116-11ea-93f1-b411a91811b7.png)

### New Issue 2
The spec reads:
![image-20200724-124304](https://user-images.githubusercontent.com/20728145/88755624-6c056500-d116-11ea-9a74-958362f41ad5.png)

So it is assumed:

- first - select project stays that much all conditions and then 
- second - choose the most recent one

But the sample code uses different logic than the spec:
![image-20200724-124503](https://user-images.githubusercontent.com/20728145/88755706-9bb46d00-d116-11ea-8fab-3dcc3d06da10.png)

**Comment by MollyMcEvilley** [comment]
This has been re-written (commits forthcoming).  Section 7.5 in both the specs and the code were updated to address a few different issues, but most relevant to this -- to align the business logic for LSAExit system engagement status with LSAHousehold.  (It isn't necessary that the most recent _EnrollmentCoC_=**ReportCoC**.)
