### ISSUE TITLE
**8.9 - discrepancy in tlsa_CohortDates usage**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#363]
This revisits #292 and raises a question about which version of the specs is the authority at this point.

In the comments on #292 you commented:

> Corrections to the specs and to the code for 8.9-8.18 to reflect that a bednight is counted for RRH when the MoveInDate occurs on the ExitDate.

However, we haven't been able to find the corrections in the spec.

The code has been highlighted, but it is not documented in the spec.

In the spec there is a restriction by move-in date but it is a bit different and relates to `ProjectType in (3,13)` but in the sample code move-in date restriction for `ProjectType = 13` only. What is about `ProjectType = 3`? 

![image-20200727-090256](https://user-images.githubusercontent.com/20728145/88756644-08306b80-d119-11ea-8ef1-3eda96146e45.png)

**Comment by michelleogburn** [comment]
@MollyMcEvilley which version of the specs should we be using as the authority? It is getting super tiresome to check several versions.

**Comment by MollyMcEvilley** [comment]
ProjectType 3 is in there --the line of code that you highlighted in green above just adds ExitDate for RRH if the ExitDate = MoveInDate.  That isn't relevant for PSH.
![image](https://user-images.githubusercontent.com/6156815/90693114-44507b00-e244-11ea-8265-5a1c1e01dc74.png)


I deleted the 'working draft' bad idea -- the most current version will always be here: https://github.com/HMIS/LSASampleCode/blob/master/LSA%20Programming%20Specifications%20FY2019.docx
