### ISSUE TITLE
**8.5 - question about SystemPath usage in sample code**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#366]
Follow up to #286 

@MollyMcEvilley comments on #286:

> SystemPath should appear in the WHERE clause where it's relevant. It isn't relevant to 8.5 or 8.8 because all records in ref_Populations where pop.Core = 1 have a NULL value for SystemPath.

First of all, the question was about SystemPath restriction in ON clause, not in WHERE clause.

Secondly, from Molly’s feedback it looks like if `Core = 1` is used, then `SystemPath` shouldn’t be checked.

But what is about steps:

- `8.3`
- `8.4.1`
- `8.4.2`

These steps also have `pop.Core = 1` and, at the same time, `(lh.SystemPath = pop.SystemPath or pop.SystemPath is null)`. Does it mean that `SystemPath` should be removed from ON clause in these steps also?

**Comment by MollyMcEvilley** [comment]
> Does it mean that **SystemPath** should be removed from ON clause in these steps also?

It means that **SystemPath** COULD be removed from the join criteria in those steps without making any difference in the output.
