### ISSUE TITLE
4.22 One more spec problem.

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#37]
Sorry, I missed this question from the developer. We are assuming the code is correct in this case. Let us know if we should go with the specs.

The specs read:

> HHChronic
HHChronic = 1 if HHType is in (1,2,3) and the head of household or any adult in the household is reported in LSAPerson with:
• DisabilityStatus = 1; and
• CHTime = 365; and
• CHTimeStatus in (1,2)
Otherwise, HHChronic = -1.

However, in the sample code:
https://github.com/MollyMcEvilley/LSASampleCode/blob/b20ecb8fe54394498b739d006e2cf36a881e8c03/LSASampleCode.sql#L1422-L1429

The condition:
`or (lp.CHTime = 400 and lp.CHTimeStatus = 2) then 1`
is not included in the spec

**Comment by MollyMcEvilley** [comment]
The code is definitely correct in this case. The specs aren't going to change but I can't see the utility in making the sample code wrong to match, so I added a note explaining why they differ.
