### ISSUE TITLE
***8.6 - LSAExit Criteria issues for PopID = 91, 92, 93 (spec)***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#372]
**Spec**
![image-20200730-124330](https://user-images.githubusercontent.com/20728145/89006895-88430680-d2bc-11ea-9f68-e5a90936a914.png)

### Issues

- “LSAExit Criteria” is completely wrong for rows 91, 92, 93 (second selected section).
- I believe second selected section should be completely removed as we aleady have a correct logic for rows 91, 92, 93 (first selected section)

**Comment by MollyMcEvilley** [comment]
Will fix (delete second selected section).
