### ISSUE TITLE
***8.6 - critical issue with PopID***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#373]
### Spec
Here is a part of `PopID` for 8.6 section
![image-20200730-113241](https://user-images.githubusercontent.com/20728145/89007044-cdffcf00-d2bc-11ea-93de-fefd472dceac.png)

### Sample Code
![image-20200730-113349](https://user-images.githubusercontent.com/20728145/89007070-dd7f1800-d2bc-11ea-80a8-c51a715ecab1.png)

### Issue
In sample code only `PopID between 0 and 4` are used. Other `PopID` from the spec are simply ignored.

**Comment by MollyMcEvilley** [comment]
The specs are correct here -- I will update the code.
