### ISSUE TITLE
***8.7: SystemPath issue in sample code***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#374]
### Spec
![image-20200730-132253](https://user-images.githubusercontent.com/20728145/89007179-2040f000-d2bd-11ea-80a5-e14e1ad16202.png)

### Sample Code
![image-20200730-132446](https://user-images.githubusercontent.com/20728145/89007206-2f27a280-d2bd-11ea-90f8-f7bb5ecea2ca.png)

`and (lx.SystemPath = pop.SystemPath or pop.SystemPath is null)` should be used in ref_Populations JOIN

**Comment by MollyMcEvilley** [comment]
Will fix

**Comment by nataliesus** [comment]
Also, in the spec popId = 0 .. 4
![image](https://user-images.githubusercontent.com/28144855/91554384-af323e00-e937-11ea-8cb9-f9bfce6fe49b.png)
but in the sample code `pop.ReturnSummary = 1 AND pop.SystemPath IS NULL` is used and much more popIds are selected.

**Comment by MollyMcEvilley** [comment]
Added **SystemPath** criteria to the join and limited to popIDs 0 to 4.

@MollyMcEvilley
MollyMcEvilley committed 7 days ago
commit d161f2d47dee78daee0ea475dc0a5f2f14e5ef9d
