### ISSUE TITLE
***8.4 - ReportRow = 14 issue***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#376]
### Spec
![image-20200730-110318](https://user-images.githubusercontent.com/20728145/89007840-62b6fc80-d2be-11ea-8928-a8ce8cdb4c06.png)

### Sample Code
![image-20200730-110651](https://user-images.githubusercontent.com/20728145/89007865-72364580-d2be-11ea-9615-a006676dd609.png)

### Issue
`RRHStatus > 2` is a mandatory restriction for ReportRow = [12, 13, 14] in Sample Code.

But in Spec ### RRHStatus restriction is only for ReportRow = [12, 13].

Shouldn't be ### RRHStatus restriction for ReportRow = 14 in Spec?

**Comment by MollyMcEvilley** [comment]
Yes, the code is correct and the specs need the `RRHStatus > 2 `restriction for row 14!
