### ISSUE TITLE
4.23 LSAPerson HHAdultAge

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#38]
https://github.com/MollyMcEvilley/LSASampleCode/blob/b20ecb8fe54394498b739d006e2cf36a881e8c03/LSASampleCode.sql#L1505-L1518

Looks like there is a typo calculating HHAdultAge in the second condition for joining it says `or (hh.HHType = 2 and hh.HHAdultAge between 18 and 24))`

But it should be `hh.HHAdultAge between 18 and 25` Otherwise it would eliminate households who have adults 25 and up, and have  children.

**Comment by tcalder** [comment]
note from tmpPerson intermediate file, that there are no persons with HHAdultAge = 25

**Comment by MollyMcEvilley** [comment]
HHAdultAge is just used to identify populations of interest, and 25 only applies to the AO Non-veterans 25+ population -- there isn't an equivalent AC population.
