### ISSUE TITLE
** section 8 - question about LSACalculated.Value = 0 **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#386]
![image-20200730-084504](https://user-images.githubusercontent.com/20728145/89144361-5de28a80-d502-11ea-8143-6b4af9b780e0.png)

It is not obvious, by the spec, that we must generate each row regardless of calculated “Value” even if no `tlsa_Household` record that matches the criteria is found. 

I want to confirm it with Molly, because now if i.e. there is no record in `tlsa_Household` table with `ESDays > 0`, then no record with `ReportRow = 1` will be inserted in `LSACalculated` table.

![image-20200730-084743](https://user-images.githubusercontent.com/20728145/89144431-a0a46280-d502-11ea-8a00-2ef84cbdd180.png)

But the spec states that “a report row is required in LSACalculated”.
![image-20200730-090026](https://user-images.githubusercontent.com/20728145/89144495-cd587a00-d502-11ea-827e-85219591d1a7.png)

So, is it a correct behavior that some ReportRows maybe not included in `LSACalculated.csv`? Will `LSACalculated.csv` pass LSA validation?

...and a follow up question:
![image-20200730-100738](https://user-images.githubusercontent.com/20728145/89144572-fbd65500-d502-11ea-9abc-ae5ddeb55627.png)

if `ESDays = 0`, then should `LSACalculated.csv` have ~348 records ( for each combination `pop.PopID, pop.HHType, pop.SystemPath` ) with Value = 0?

**Comment by MollyMcEvilley** [comment]
Adding notes to the specs to clarify that records in LSACalculated are only generated when **Value** > 0.
