### ISSUE TITLE
* 8.6: PopID = 11 issue *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#387]
### Spec
![image-20200730-122633](https://user-images.githubusercontent.com/20728145/89144718-6091af80-d503-11ea-9e39-259c981cca67.png)

### Sample Code
`ref_Populations` table has `PopID = 11` with:

- PopName = “Household with 3+ Children” (**note, in the Spec there is “AC“ prefix**)
- AC3Plus = 1
- HHChild = 3

### Issue
The spec doesn’t have `HHChild = 3` as and additional “LSAExit Criteria” condition.

**Comment by MollyMcEvilley** [comment]
There is an HHChild column in tlsa_Household but not in tlsa_Exit / there is an AC3Plus column in tlsa_Exit but not in tlsa_Household.  The code uses the same records in ref_Populations and only references the relevant columns.
