### ISSUE TITLE
Help with ch_Time queries

### ISSUE THREAD

**Issue by thomas-powers** [abtassociates/LSASampleCode#39]
Hi there,

I do not know if others are having this problem, but my queries to populate the ch_Time table (4.16) are horrible on some of my CoCs. One of our CoCs generate a ch_Exclude table with 16,834,030 records. The ch_Time queries are taking hours to complete and often getting stuck and not continuing. 

Is anyone else having this problem? Do these numbers seem realistic? Thanks!

**Comment by thomas-powers** [comment]
My queries (these are in Postgres, mind you):

insert into ch_Time (PersonalID, chDate)
select distinct lp.PersonalID, cal.theDate
from tmp_Person lp
inner join ch_Enrollment chn on chn.PersonalID = lp.PersonalID
left outer join Services_csv bn on bn.EnrollmentID = chn.EnrollmentID
	and cast(bn.RecordType as INT) = 200 
	and CAST(bn.DateProvided as DATE) between lp.CHStart and lp.LastActive
inner join ref_Calendar cal on 
	cal.theDate >= coalesce(chn.StartDate, cast(bn.DateProvided AS DATE))
	and cal.theDate < coalesce(chn.StopDate, bn.DateProvided::DATE + INTERVAL '1 day') 
left outer join ch_Exclude chx on chx.excludeDate = cal.theDate
	and chx.PersonalID = chn.PersonalID
where chn.ProjectType in (1,8) and chx.excludeDate is null;

insert into ch_Time (PersonalID, chDate)
select distinct lp.PersonalID, cal.theDate
from tmp_Person lp
inner join ch_Enrollment chn on chn.PersonalID = lp.PersonalID
inner join Enrollment_csv hn on hn.EnrollmentID = chn.EnrollmentID 
	and cast(hn.EntryDate as DATE) > lp.LastActive - INTERVAL '1 year'
inner join ref_Calendar cal on cal.theDate >= cast(hn.DateToStreetESSH AS DATE) 
	and cal.theDate < coalesce(chn.MoveInDate, chn.StopDate)
left outer join ch_Exclude chx on chx.excludeDate = cal.theDate
	and chx.PersonalID = chn.PersonalID
left outer join ch_Time cht on cht.chDate = cal.theDate 
	and cht.PersonalID = chn.PersonalID
where chx.excludeDate is null
	and cht.chDate is null
	and (chn.ProjectType in (1,8)
	    -- Thomas 7/27/18 - Changes from 7/9/18 doc
		or cast(hn.LivingSituation AS INTEGER) in (1,18,16)
		-- End changes
		or (cast(hn.PreviousStreetESSH AS INTEGER) = 1 and cast(hn.LengthOfStay AS INTEGER) in (10,11))
		or (cast(hn.PreviousStreetESSH AS INTEGER) = 1 and cast(hn.LengthOfStay AS INTEGER) in (2,3)
			and cast(hn.LivingSituation AS INTEGER) in (4,5,6,7,15,24) ) 

insert into ch_Time (PersonalID, chDate)
select gap.PersonalID, cal.theDate
from (select distinct s.PersonalID, s.chDate as StartDate, min(e.chDate) as EndDate
	from ch_Time s 
	inner join ch_Time e on e.PersonalID = s.PersonalID and e.chDate > s.chDate 
		and e.chDate - INTERVAL '7 days' <= s.chDate
	where s.PersonalID not in 
		(select PersonalID 
		from ch_Time 
		where chDate = s.chDate + INTERVAL '1 DAY')
	group by s.PersonalID, s.chDate) gap
inner join ref_Calendar cal on cal.theDate between gap.StartDate and gap.EndDate
left outer join ch_Time cht on cht.PersonalID = gap.PersonalID 
	and cht.chDate = cal.theDate
where cht.chDate is null;

**Comment by eanders** [comment]
@thomas-powers without digging in too deeply, do you have indexes on the various tables you are selecting from?  Postgres has some restrictions on which indexes it uses that don't apply to SQL Server.  Specifically it will only use one index per table.  You may find some multi-column indexes will help significantly.

**Comment by thomas-powers** [comment]
@eanders 
Hi there. Thanks for responding.
Here is my creation SQL. 

CREATE TABLE ch_Time(
	PersonalID varchar(32) NOT NULL,
	chDate date NOT NULL
);

CREATE INDEX ch_Time_PersonalID_idx ON ch_Time USING HASH(PersonalID);
CREATE INDEX ch_Time_chDate_idx ON ch_Time USING HASH(chDate);

**Comment by eanders** [comment]
I was thinking more about the indexes on `tmp_Person` `ch_Enrollment` `Services_csv` `ref_Calendar` `ch_Exclude` etc.  Anything involved in a join should be indexed, and if you have a where that checks multiple columns, you'll probably want to setup multi-column indices.  

If you haven't been using a tool to analyze the explain for the select portion of your insert intos you should check out http://tatiyants.com/pev/#/plans/new.  It does a decent job of giving you a sense of what's causing slowness.

Basically you'd put 
```EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) 
select distinct lp.PersonalID, cal.theDate
from tmp_Person lp
inner join ch_Enrollment chn on chn.PersonalID = lp.PersonalID
left outer join Services_csv bn on bn.EnrollmentID = chn.EnrollmentID
and cast(bn.RecordType as INT) = 200
and CAST(bn.DateProvided as DATE) between lp.CHStart and lp.LastActive
inner join ref_Calendar cal on
cal.theDate >= coalesce(chn.StartDate, cast(bn.DateProvided AS DATE))
and cal.theDate < coalesce(chn.StopDate, bn.DateProvided::DATE + INTERVAL '1 day')
left outer join ch_Exclude chx on chx.excludeDate = cal.theDate
and chx.PersonalID = chn.PersonalID
where chn.ProjectType in (1,8) and chx.excludeDate is null;
```

into `explain.sql` and then run `psql -qAt -f explain.sql > analyze.json`.

**Comment by MollyMcEvilley** [comment]
I'm going to flag this as 'help wanted' and close it out as an issue.  (I think GitHub is pretty excellent but wish there were non-issue conversation threads.)
