### ISSUE TITLE
* 8.11 - "HHChronic" should be removed from sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#391]
This issue is similar to #291 

@MollyMcEvilley  resolved it for section 8.9 with the comment:

> HHChronic isn't relevant -- deleting it from the sample code.

We think 8.11 should also be fixed in the same way.

**Comment by MollyMcEvilley** [comment]
This was a valid issue but is no longer because the AHAR team asked to add CH populations to these counts... the specs have been updated accordingly.
