### ISSUE TITLE
** 8.14: PopID = [147, 148] -HHAdultAge issue **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#392]
### Spec
![image-20200803-151502](https://user-images.githubusercontent.com/20728145/89262312-4976be80-d5e4-11ea-9c4f-af045bfabe99.png)

### Sample Code 7 ref_Population
![image-20200803-151624](https://user-images.githubusercontent.com/20728145/89262395-5e535200-d5e4-11ea-9467-e982e1dff559.png)

### Issue
Either spec of sample code has an issue because of `HHAdultAge`

**Comment by MollyMcEvilley** [comment]
ref_Populations is correct here -- counts include people whose ActiveAge is in the age ranges for the population and:
1. It _**is**_ limited to parenting youth households (HHParent and HHAdultAge criteria).
2. It is **_not_** limited to HoH.   

![image](https://user-images.githubusercontent.com/6156815/90793296-91326100-e2d9-11ea-9a11-696d806d56a5.png)
