### ISSUE TITLE
** 8.14: PopID = [112, 128, 144] DVStatus/HHFleeingDV issue **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#394]
### Spec
![image-20200803-145111](https://user-images.githubusercontent.com/20728145/89262910-2ef11500-d5e5-11ea-95c6-f40de3952a49.png)

### Sample Code
![image-20200803-145214](https://user-images.githubusercontent.com/20728145/89262937-3ca69a80-d5e5-11ea-9b1a-b11cd986cc54.png)

### Issue
Either spec or sample code should be updated.

The same issue also appears for PopID = 128 and 144.

**Comment by MollyMcEvilley** [comment]
The specs are correct here and I've updated the code accordingly -- these are counts by personal characteristics and not household characteristics.
