### ISSUE TITLE
* 8.14: PopID = 111 issue *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#395]
### Spec
![image-20200803-144745](https://user-images.githubusercontent.com/20728145/89263130-8a230780-d5e5-11ea-8124-222251d554eb.png)

### Sample Code
![image-20200803-144826](https://user-images.githubusercontent.com/20728145/89263161-97d88d00-d5e5-11ea-8e20-8fc5286377ed.png)

### Issue
Spec should be updated: instead of `DisabilityStatus = 2` should be `DisabilityStatus = 1`

**Comment by MollyMcEvilley** [comment]
correcting for PopIDs 111 and also for 143 -- thank you!

(Commit forthcoming)
