### ISSUE TITLE
* 8.14 - "Maximum ActiveAge" issue/question(?) *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#396]
### Spec
Spec has `Maximum ActiveAge` restriction for PopID = 24...34

### Sample Code
Uses `ActiveAge` without max

### Issue
It is a bit confusing seeing `Maximum` in the spec

**Comment by MollyMcEvilley** [comment]
The `max(ActiveAge)` is in the `latest` subquery.
![image](https://user-images.githubusercontent.com/6156815/90640736-5c051080-e1fe-11ea-90d1-34f5102b39b6.png)
