### ISSUE TITLE
Step 4.19

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#40]
(AAQ 129300) We have checked the updated code posted on both vendor hub and GitHub, we noticed the code for set CHTime = 400, CHTimeStatus = 2 part the table has been switched to 'Ch_enrollment', but while set CHTime = coalesce(lp.CHTime, 0), CHTimeStatus = 99 part, it is still using 'active_Enrollment', but in the report specification it mentioned that 'Set CHTimeStatus = 99 where (CHTime in (0,270) or CHTimeStatus = 3) and for any ch_Enrollment where....'. So our question is the 'Active_Enrollment' is kept here by purpose? Please advise.

**Comment by MollyMcEvilley** [comment]
The code in step[ 4.19 has been updated](https://github.com/HMIS/LSASampleCode/blob/2a462caf9b8f0d1ee97d5da0b5f34fc23e6b1736/LSASampleCode.sql#L1265-L1293) to align with the specs.

https://github.com/HMIS/LSASampleCode/blob/2a462caf9b8f0d1ee97d5da0b5f34fc23e6b1736/LSASampleCode.sql#L1265-L1293
