### ISSUE TITLE
** 8.13 - "ActiveHHType" is missing in the spec **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#401]
![image-20200803-113904](https://user-images.githubusercontent.com/20728145/89265182-f5baa400-d5e8-11ea-8d85-42d9b121f52b.png)

Sample code uses "`ActiveHHType`" restriction that is not used in the spec.

**Comment by MollyMcEvilley** [comment]
See issue #432.  Updated the specs in sections 8.1-8.18 to explicitly state relationships between LSACalculated.HHType value and Active/Exit1/Exit2HHType columns in tlsa_HHID.
