### ISSUE TITLE
** 8.11 - "Active = 1" restriction is missing in the spec but exists in sample code **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#402]
### Sample Code
![image-20200803-104652](https://user-images.githubusercontent.com/20728145/89265342-2d295080-d5e9-11ea-8609-6d8f7e3f004b.png)

### Issue
Spec has `“in tlsa_Enrollment where Active = 1”` restriction for section 8.10. 

There is no “`Active = 1`” restriction in the spec for section 8.11. At the same time, sample code has “`Active = 1`” restriction. 

Either spec or sample code should be fixed.

Also it is interesting that sections 8,9 and 8,10 it is “n.Active” but for section 8.11 it is “hhid,Active“ so different tables are used.

**Comment by MollyMcEvilley** [comment]
The results produced by the sample code are consistent with the logic defined by the document.
