### ISSUE TITLE
ref_Calendar table - questions about unused columns

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#403]
### Question 1: Several columns are not used in LSA
![image-20200723-113433](https://user-images.githubusercontent.com/20728145/89369791-f5c3ae00-d693-11ea-8e26-1f60aa3df3ba.png)

We cannot find column usage for:

- `month_name`
- `day_name`
- `fy`

Do we really need them or are they for information only?

### Question 2: After FY calendar days
![image-20200723-113826](https://user-images.githubusercontent.com/20728145/89369917-463b0b80-d694-11ea-8dcd-cb3f53f8a786.png)

The LSA report doesn’t work with days after FY end date (in this year it is 9/30/2019). Why do we use `2022-09-30` as a last calendar day? Is this on purpose avoid the need to update it during the next two fiscal years? Can we use the current FY end date as last calendar date in our LSA implementation? Please advise.

**Comment by MollyMcEvilley** [comment]
Feel free to delete any parts of the table that aren't useful to you!  This includes any and all dates after `ReportEnd `-- your guess about avoiding the need to update is correct.  (I have a ref_Calendar table in every DB I create and use it for a variety of purposes.)
