### ISSUE TITLE
** 8.21 - ExitDate issue in sample code **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#404]
### Spec
![image-20200804-145922](https://user-images.githubusercontent.com/20728145/89370056-a6ca4880-d694-11ea-9852-30982b160084.png)

### Sample Code
![image-20200804-150100](https://user-images.githubusercontent.com/20728145/89370082-b8135500-d694-11ea-9c9e-ad8932986d29.png)

The sample code is missing restrictions for _ExitDate_

**Comment by MollyMcEvilley** [comment]
This correction was committed on 8/6 without noting that it closed this issue -- but it has been addressed.
