### ISSUE TITLE
* 8.21: lsa_Project is not used in the sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#406]
### Spec
The spec states that `lsa_Project` should be used to limit project stays for section 8.21.
![image-20200804-143758](https://user-images.githubusercontent.com/20728145/89370854-9024f100-d696-11ea-8a7d-d7c1c7445d43.png)

![image-20200804-144306](https://user-images.githubusercontent.com/20728145/89370868-9b781c80-d696-11ea-825c-f14ffaab5747.png)

### Spec
`lsa_Project` is not used at all. It can be a problem for the program-based LSA version.
![image-20200804-143842](https://user-images.githubusercontent.com/20728145/89370966-e09c4e80-d696-11ea-9c1c-a488174da0c9.png)

**Comment by MollyMcEvilley** [comment]
Not limited to ProjectIDs in Project.csv

**Comment by michelleogburn** [comment]
Issue #496 duplicates this issue and is more complete with some additional comments. Closing this as a duplicate.
