### ISSUE TITLE
* 8.21: lsa_Project is not in the schema *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#407]
### Spec
The spec states "_ProjectIDs_ are limited to _ProjectIDs_ listed in Project.csv." That is why `lsa_Project must be included in the schema.

![image-20200804-143443](https://user-images.githubusercontent.com/20728145/89371149-599ba600-d697-11ea-83ef-c10ee5ce1ff5.png)

**Comment by MollyMcEvilley** [comment]
This has been corrected in the current version -- I failed to note that a commit last week closed this issue.
