### ISSUE TITLE
Step 4.22 HHAdultAge

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#41]
(AAQ 129385) We have a question regarding 4.22 Set HHAdultAge, in the report specification it mentioned that ‘(all other households)=25’, but in the sample code ‘and max(n.AgeGroup) between 25 and 55 then 25   ……   else -1 end ’ In sample code, all the others are set as ‘-1’. There is inconsistency, please let us know which one to follow.
Also in the sample ' min(n.AgeGroup) between 18 and 25  and max(n.AgeGroup) between 25 and 55 then 25', so if in one household there is only one adult memeber age=34, it will be conside as 'else' which in the sample it will set as '-1' in the report spec. it will set as '25'. You may use householdID='829167' and PID='230162'.

**Comment by MollyMcEvilley** [comment]
The specs are correct and the code in 4.22 to set HHAdultAge in active_Household has been updated accordingly.  There is also an update in 4.24-25 related to HHAdultAge in tmp_Household.  (see [GitHub issue #59](https://github.com/HMIS/LSASampleCode/issues/59)) to align with the specs:
https://github.com/HMIS/LSASampleCode/blob/001943f66ad36c26158098e2fc4059914b630915/LSASampleCode.sql#L1517-L1533
