### ISSUE TITLE
** 8.20: ContinuumProject and EnrollmentCoC restrictions in the spec **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#410]
### Spec
![image-20200804-130513](https://user-images.githubusercontent.com/20728145/89371441-3e7d6600-d698-11ea-899c-3c0864da66d7.png)

### Sample Code
![image-20200804-130637](https://user-images.githubusercontent.com/20728145/89371461-4dfcaf00-d698-11ea-9d84-91ca4d58c7ef.png)

Sample code indeed calculates `Value` as `EnrollmentIDs in hmis_Enrollment` but `hmis_Enrollment` is joined by `tlsa_Enrollment.EnrollmentID` .

1. `tlsa_Enrollment` is used as main table so the is no need to check  `ContinuumProject = 1` in sample code and use `ContinuumProject` restriction in the spec unless _we shouldn’t use_ `tlsa_Enrollment` _in section 8.20 at all._
2. Spec has `EnrollmentCoC.CoCCode `restriction but sample code doesn’t use `EnrollmentCoC` table. Shouldn’t the spec be corrected?

**Comment by MollyMcEvilley** [comment]
Joining to tlsa_Enrollment limits the enrollments to those in ReportCoC _and_ to those in projects where ContinuumProject = 1.  The specs are more explicit but the code accomplishes the same thing.
