### ISSUE TITLE
* 8.19: redundant ContinuumProject and EnrollmentCoC restrictions in the spec *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#411]
### Spec (section 8.19)
![image-20200804-125744](https://user-images.githubusercontent.com/20728145/89371675-daa76d00-d698-11ea-85be-6325e55f4f4b.png)

### Sample Code
![image-20200804-125836](https://user-images.githubusercontent.com/20728145/89371695-ea26b600-d698-11ea-8dfd-46ed0f92710b.png)

The sample code uses `tlsa_Enrollment` that already incapsulates `ContinuumProject = 1` and `CoCCode` logic. Why all of a sudden we have `ContinuumProject = 1` and `CoCCode` restrictions in the Spec?

**Comment by MollyMcEvilley** [comment]
It's left over from before tlsa_Enrollment existed...
