### ISSUE TITLE
** 8.15 - ProjectType restriction is missing in sample code **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#415]
### Spec
According to the spec, 8.15 is required for LSAScope = 1 and should be days for Project Types = [1, 2, 3, 8, 13]

Reminder: LSAScope = 1 has Project Type universe = [1, 2, 3, 8, **9, 10**, 13]

![image-20200804-120527](https://user-images.githubusercontent.com/20728145/89372124-2575b480-d69a-11ea-8663-61a894879f71.png)

### Sample Code
![image-20200804-120208](https://user-images.githubusercontent.com/20728145/89372139-34f4fd80-d69a-11ea-8d9d-a1bb88faf85d.png)

Project Types = [1, 2, 3, 8, 13] are checked in `ref_Calendar` in LEFT JOINs. But because LSAScope = 1 has Project Type universe = [1, 2, 3, 8, **9, 10**, 13], the query is executed is for Project Types = [9, 10] also. As a result, ProjectIDs with Project Types = [9, 10] are inserted in `lsa_Calculated` table that is against the spec.

Please fix.

NOTE: other sections that also have this issue are:

- `8.16.1`
- `8.17`
- `8.18.1`
- `8.18.2`

**Comment by MollyMcEvilley** [comment]
Happily, there are no records for ProjectTypes 9/10 in tlsa_HHID and the code requires that hhid.Active = 1.
