### ISSUE TITLE
8.1) ref_Populations: "Unaccompanied" Youth household label question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#416]
### Spec
![image-20200728-143944](https://user-images.githubusercontent.com/20728145/89372338-be0c3480-d69a-11ea-8039-21b3af378af8.png)

### Sample Code
![image-20200728-143958](https://user-images.githubusercontent.com/20728145/89372367-d2503180-d69a-11ea-8e30-a8a853e08539.png)

There is no “**unaccompanied**“ text  In `ref_Populations` table for PopID = [1, 2].

**Comment by MollyMcEvilley** [comment]
I can confirm that they mean the same thing.
