### ISSUE TITLE
ref_Populations: "Core" question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#417]
This is a follow up to #296 . @MollyMcEvilley responded:

> use Core = 1, which correlates to the appropriate PopIDs.

May I ask the logic that is behind Core field? right now Core field has 3 possible values:

- null
- 0
- 1

In sample code only Core = 1 is used. As I understand, we should treat Core = null and Core = 0 the same as they are not used in sample code?

**Comment by MollyMcEvilley** [comment]
Only **Core** = 1 will ever be relevant in the code.  

It won't ultimately make any difference in the output so i'm not going to re-generate the script now, but I did update all of the 0s to NULL in my db -- so the next time there's a critical change to _1 Create Temp Reporting and Reference Tables.sql_, it will be consistent.
