### ISSUE TITLE
8.3: Redundant conditions to join ref_Populations table

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#419]
### Spec
![image-20200730-102703](https://user-images.githubusercontent.com/20728145/89372983-6a024f80-d69c-11ea-92a8-4f55e11885d5.png)

### Sample Code
![image-20200730-102625](https://user-images.githubusercontent.com/20728145/89373009-79819880-d69c-11ea-847b-98b5b278d8b2.png)

According to the spec, we only need to check:

- `PopID`
- `HHType`
- `HHAdultAge`
- `HHVet`

Not sure why other conditions are used:

- `HHDisability`
- `HHFleeingDV`
- `HHParent`
- `HHChronic`
- `HHChild`
- `Stat`
- `PSHMoveIn`
- `HoHRace`
- `HoHEthnicity`
- `SystemPath`

If it is decided to remove unused conditions from sample code, the following sections should all be corrected:

- `8.3`
- `8.4.1`
- `8.4.2`
- `8.5`
- `8.8`

**Comment by MollyMcEvilley** [comment]
Feel free to make any changes to the sample code that you'd like to for your own use -- I'm not going to make any changes to this.
