### ISSUE TITLE
** 8.15 - "Active = 1" issue **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#422]
### Spec
![image-20200804-081825](https://user-images.githubusercontent.com/20728145/89373647-15f86a80-d69e-11ea-8e94-12992a3aef95.png)

### Sample Code
![image-20200804-081931](https://user-images.githubusercontent.com/20728145/89373672-2577b380-d69e-11ea-9daa-d84d8e39cabd.png)

### Issue
In the spec it is said to use  `tlsa_HHID.Active = 1`.

But in the sample code `tlsa_Enrollment.Active = 1` is used.

Which one is correct?

**Comment by Ladvien** [comment]
It also looks like this is an issue in:
- 8.16.1
- 8.16.2

**Comment by MollyMcEvilley** [comment]
Code should use tlsa_HHID.Active... commit forthcoming.
