### ISSUE TITLE
Section 8: Double space in "Youth  18-21" population name (spec)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#423]
![image-20200804-094349](https://user-images.githubusercontent.com/20728145/89373746-5ce66000-d69e-11ea-9ffe-5468cb69adcb.png)

There is one extra space between “Youth” and '18“.

There are 14 places in `LSA Programming Specifications FY2019 v1 Working Draft.docx` to fix.

![image-20200804-094444](https://user-images.githubusercontent.com/20728145/89373806-7daeb580-d69e-11ea-9cf5-99f6a70fb378.png)

**Comment by MollyMcEvilley** [comment]
Thank you -- I turned off track changes to replace all 71 double spaces in the document with a single space.  Commit forthcoming.
