### ISSUE TITLE
** 8.21 - "enrollments active in the report period" issues in sample code **

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#426]
## Spec
![image](https://user-images.githubusercontent.com/6241517/89450834-d58e0080-d720-11ea-9696-1d59fcb0e27e.png)

## Sample Code
![image](https://user-images.githubusercontent.com/6241517/89450856-e0e12c00-d720-11ea-8282-fd7c0c25666d.png)

## Issues
1. Sample Code missing major restrictions for “active enrollment“ logic.
2. Also, there is an issue with ES NbN enrollments - bed-nights restriction is missing in both spec and sample code.

**Comment by MollyMcEvilley** [comment]
1.  Thank you -- corrected.
2.  The criteria here are intentionally very broad -- there is no bed-night restriction -- because we're looking for _any_ potential issues.  (Wicked stepmother vs. good fairy way of looking at data.) 
Commit forthcoming.

**Comment by Ladvien** [comment]
@MollyMcEvilley 

1. You bet.
2. Ah, good to know.  That helps clear things up.
