### ISSUE TITLE
** 8.21 - gray area in the spec **

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#427]
![image](https://user-images.githubusercontent.com/6241517/89450950-0b32e980-d721-11ea-9cf7-456e693639d3.png)

“Missing _Client Location_” is not the only reason why enrollment can be excluded from tlsa_Enrollment. Other reasons are:
- enrollment started before HoH’s enrollment
- EntryDate = ExitDate
- relationship_to_hoh is not between 1 and 5
- ES NbN enrollment doesn’t have valid bed-nights
- household doesn’t have any HoH
- household has more than 1 HoH client

The specs say that “_Missing Client Location_” **may** be a reason why enrollment is selected in section 8.21. So either the spec should be updated or other possible reasons must be included in the programming instructions and sample code.

**Comment by MollyMcEvilley** [comment]
There were a few points of confusion in that section and the concept of counting enrollments that maybe would have been included in the LSA if they weren't missing data isn't really the salient point... I rewrote some of section 8.21 in hopes of making the whole thing clearer.
