### ISSUE TITLE
* tlsa_Enrollment - contradictory logic in the spec *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#430]
In section “3.3. HMIS Household Enrollments (tlsa_HHID)” it states:
![image](https://user-images.githubusercontent.com/6241517/89451563-0884c400-d722-11ea-8cc9-edefd389a555.png)

That makes us think if HH member’s EntryDate < HoH EntryDate, then in the report HH member’s EntryDate should be adjusted to HoH EntryDate.

But then in section “3.4. HMIS Client Enrollments (tlsa_Enrollment)” enrollments with HH member’s EntryDate < HoH EntryDate are just ignored because of:
![image](https://user-images.githubusercontent.com/6241517/89451584-0e7aa500-d722-11ea-98a4-920c4e621620.png)

So why is there a separate paragraph in section 3.3. for HH member’s EntryDate < HoH EntryDate enrollments? Is this an issue?

**Comment by MollyMcEvilley** [comment]
This was a good one... thank you!

Specs section 3.3 requires that if a household member's EntryDate is prior to the HoH EntryDate, reporting should include the household member's enrollment, but must use the HoH value as the effective EntryDate.  Specs and code in section 3.4 were excluding the enrollments altogether and have been modified consistent with 3.3.
