### ISSUE TITLE
* 8.13 - spec uses "HHType" instead of "ActiveHHType" *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#432]
![image](https://user-images.githubusercontent.com/6241517/89452431-4209ff00-d723-11ea-98e8-cc5d016f9d22.png)

In sample code `tlsa_HHID.ActiveHHType` is used.

To avoid any confusion, should `HHType` column in the spec be renamed to `ActiveHHType` (similar to section 8.12)?

A few other sections should be updated as well:
- 8.14
- 8.17
- 8.18

**Comment by MollyMcEvilley** [comment]
Thanks for pointing this out.  Updated the specs in sections 8.1-8.18 to explicitly state relationships between LSACalculated.**HHType** value and **Active/Exit1/Exit2HHType** columns in tlsa_HHID.  Commit forthcoming.

**Comment by Ladvien** [comment]
Thanks, @MollyMcEvilley.  That seemed to cause more questions for us, though.

Could you check each of the 8.x sections applying the following concerns:

## Spec (after changes)
The specs now state to use ActiveHHType field. ActiveHHType field is only in tlsa_HHID table.

There is no `tlsa_HHID` table in the chart only:
![image](https://user-images.githubusercontent.com/6241517/89683490-3f8fdc80-d8be-11ea-94e7-e999d382e48c.png)

## Sample Code
Sample code wasn’t changed.  It uses `tlsa_Household.HHType` which contradicts the specs.
![image](https://user-images.githubusercontent.com/6241517/89683554-5fbf9b80-d8be-11ea-80b4-5be781fe3ff2.png)
