### ISSUE TITLE
5.5 - "(5.6)" numeration is missing on flow-chart

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#433]
![image](https://user-images.githubusercontent.com/6241517/89452730-bfce0a80-d723-11ea-9640-da7ee265e3aa.png)

Also, it looks like two sections (5.6) in the explanation text
![image](https://user-images.githubusercontent.com/6241517/89452749-c52b5500-d723-11ea-9bdd-29411d0b8798.png)

**Comment by MollyMcEvilley** [comment]
I am making these edits (commit forthcoming) -- thank you for pointing them out -- without tracking the changes or noting them specifically in the document revision history other than lumping them in with 'correction of typos throughout' (or something along those lines).
