### ISSUE TITLE
* 5.6 - “Relevant Data Source“ table issues (spec) *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#434]
![image](https://user-images.githubusercontent.com/6241517/89452903-058ad300-d724-11ea-8c60-2c08791c6074.png)

1. “Red” highlighted columns are not used in 5.6 logic and must be removed from “Relevant Data Source“ table
2. Sample code uses “tlsa_Person.HoHAdult > 0” restriction, HoHAdult is mentioned in the “Relevant Data Source“ table, but HoHAdult is not used in “Logic“ section.

**Comment by MollyMcEvilley** [comment]
Added HoHAdult > 0 to the specs and deleted the irrelevant rows in the relevant data section.  Commit forthcoming.
