### ISSUE TITLE
* 5.7 - "MoveInDate = ExitDate" question *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#436]
Recently, many sub-sections of section 8 were updated with `or ( ProjectType = 13 and MoveInDate = CohortStart and ExitDate = CohortStart)` condition.

Want to confirm we shouldn’t add similar restriction for sections 5.7 .. 5.10
![image](https://user-images.githubusercontent.com/6241517/89453356-be511200-d724-11ea-878c-4e0681c98814.png)

**Comment by MollyMcEvilley** [comment]
Unfortunately this is a good point...  :) Fortunately, it only affects section 5.7 -- we should add RRH ExitDates to ch_Exclude IF ExitDate = MoveInDate.  Commit forthcoming.

**Comment by Ladvien** [comment]
Thanks, @MollyMcEvilley! :)
