### ISSUE TITLE
* 5.7 - "ProjectType in (3,13) and MoveInDate is null" scenario confirmation *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#437]
## Spec
![image](https://user-images.githubusercontent.com/6241517/89453422-d9238680-d724-11ea-8b9d-401fc9b5a91f.png)

## Samples Code
![image](https://user-images.githubusercontent.com/6241517/89453433-dde83a80-d724-11ea-9981-739193680c6e.png)

Test case `ProjectType in (3,13) and MoveInDate is null`:
- spec has no rule to deal with such scenario so enrollment will be ignored
- the enrollment will be ignored in sample code because of `cal.theDate >= NULL`
Want to confirm there is no issue.

**Comment by MollyMcEvilley** [comment]
Happily, no issue.  We are only excluding (inserting dates into ch_Exclude for) time in TH and time housed in RRH/PSH.  If MoveInDate is NULL, the enrollment isn't relevant to this step.
