### ISSUE TITLE
** 7.2 - SAMPLE CODE - Ambiguity in reportable exit selection - detected using Sample Data Kit

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#439]
Hello

In the sample data kit, there is one HoH (personalid = '67620') with two enrollments. Both are almost identical: the same project type, exit date, destination and so on. The only significant difference is their entry date: 2017-04-03 vs 2017-05-16. This difference is significant for several reasons, thus it is important to make sure the correct one will be selected every time.

**PROBLEM**: in step 7.2, the relevant "order by" clause looks like this:

`order by case when qx.ExitDest between 1 and 6 then 2
                      when qx.ExitDest between 7 and 14 then 3
                      else 4 end asc, qx.ExitDate asc`

Again: all of the info used in this clause is IDENTICAL for both enrollments; **only the EntryDate is different, but not used**. 

The specs don't make this clear, basically focusing on the "last exit date" and ignoring the fact that there can be two enrollments with the same exit date.

Please advise. Any reply will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
I am inclined to note that if the existing criteria don't isolate a single enrollment, it doesn't really matter which one we use -- but it might as well be consistent.

Commits forthcoming:
- Adding `EntryDate desc` to the sort in the sample code and also, in the event that all other things are the same, `EnrollmentID desc`.  

- Adding notes to the specs consistent with the changes to the code.
