### ISSUE TITLE
* 8.12 - missing "tlsa_HHID.Active = 1" restriction in "Cohort" section in the spec *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#440]
![image](https://user-images.githubusercontent.com/6241517/89544972-61a73300-d7c8-11ea-9c32-e93023fc10d5.png)

Please duplicate `Active = 1` restriction in “Cohort“ section similar to section 8.9
![image](https://user-images.githubusercontent.com/6241517/89545011-6cfa5e80-d7c8-11ea-88b7-092d1fbfd6be.png)

**Comment by MollyMcEvilley** [comment]
Adding this to the specs although it isn't necessary in code because the date criteria for CohortStart and CohortEnd specify a subset of enrollments where Active = 1.
