### ISSUE TITLE
** 5.8.4 - issues in the sample code **

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#441]
![image](https://user-images.githubusercontent.com/6241517/89545115-8e5b4a80-d7c8-11ea-9ad4-06c0948c5d24.png)

`5.8.3` and `5.8.4` are used in sample code. 

Here is `5.8.4`
![image](https://user-images.githubusercontent.com/6241517/89545145-9a470c80-d7c8-11ea-977a-e1a73ce4863d.png)

1. The specs state to use `EntryDate > CHStart` restriction. Though, there is no such restriction for `5.8.4` in the sample code. 
2. The specs have restrictions for _LivingSituation_, _LengthOfStay_, _PreviousStreetESSH_, _ProjectType_.  But the sample code has _LivingSituation_ restriction only. What about _LengthOfStay_, _PreviousStreetESSH_, _ProjectType_?
3. Is it possible to combine `5.8.3` and `5.8.4` into one step like in the specs to avoid any confusion?

**Comment by MollyMcEvilley** [comment]
I was pushing a commit that addresses this while you were submitting the issue... :)  see #438
