### ISSUE TITLE
*** 7.6.1. - SAMPLE CODE - Ambiguity in prior episode selection - detected using Sample Data Kit

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#442]
Hello

In the sample data kit, there is one HoH (personalid = '73597') with five enrollments, spanning three cohorts.

**PROBLEM**: in step 7.6.1, the "prior" episode is being selected (actually: the existence of one is being checked by) using the following clause:

select top 1 prior.EnrollmentID 
			from tlsa_HHID prior
			where prior.HoHID = ex.HoHID and case ex.Cohort 
				when -2 then prior.Exit2HHType
				when -1 then prior.Exit1HHType
				else prior.ActiveHHType end = ex.HHType
			and dateadd(dd, 6, prior.ExitDate) >= hhid.EntryDate

Since this clause does not limit the relation between "prior" and "hhid" (or "current") records, it is possible that the "prior" one will actually be LATER than the "current" and still meet all the other criteria. Even more so, it is possible that the record from another cohort will be selected (especially when the "later" one is already being checked).

This was one of the direct causes of the results produced by our system being different from the sample data kit. I fixed it by adding the following two conditions:

`and prior.exitcohort = ex.cohort 
            and prior.entrydate < hhid.entrydate`

Please confirm that's the proper solution, or explain how this should actually be done otherwise. Any reply will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
That is the proper solution!  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/90769845-e3b25400-e2be-11ea-8fef-bb4eb67cf305.png)
