### ISSUE TITLE
*** 3.5 - [Exit1Age/Exit2Age] issues (FOLLOW-UP TICKET) ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#444]
Hey @MollyMcEvilley, this one is a follow-up ticket for:
- #333 
- #221 

I looks like new issues were introduced with last commit
## Spec
![image](https://user-images.githubusercontent.com/6241517/89681708-13269100-d8bb-11ea-8164-09c9c291c2f9.png)
## Sample Code
![image](https://user-images.githubusercontent.com/6241517/89681714-17eb4500-d8bb-11ea-87ba-6a93a0122845.png)
## Issue
`“ExitDate not between CohortStart and CohortEnd”` also describes scenario when `ExitDate is null`.

`ExitDate is null` scenario is missing is Sample Code.

**Comment by MollyMcEvilley** [comment]
That's okay here!  If the exit date is null, the enrollment doesn't meet the criteria for inclusion in an exit cohort and we have to use EntryAge.

**Comment by MollyMcEvilley** [comment]
Previous comment/close was incorrect.  Commit with code correction forthcoming.
