### ISSUE TITLE
**9.2 - Destination1/3 spec update **

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#449]
Hello @MollyMcEvilley, this is a follow up to #330.

Should the specs also be updated?

## Spec
![image](https://user-images.githubusercontent.com/6241517/89684791-c3e35f00-d8c0-11ea-83d5-2573ada075a9.png)

## Sample Code
![image](https://user-images.githubusercontent.com/6241517/89684775-b9c16080-d8c0-11ea-8590-31141719b06c.png)

## TODO
Spec should be updated:
- to include `n.Status1 is not null` logic
- to replace “ExitDate Destination1: > ReportStart Destination3:  is not NULL” with `ExitDate is not null`
- MoveInDate1/3 also needs correction
![image](https://user-images.githubusercontent.com/6241517/89684878-e2e1f100-d8c0-11ea-9685-47a5da160d4c.png)
- x.ExitDate was replaced with `n.ExitDate` for `MoveInDate1`. But `MoveInDate3` also should be updated.
![image](https://user-images.githubusercontent.com/6241517/89684914-f42afd80-d8c0-11ea-8c11-9600a58f9bdb.png)

**Comment by MollyMcEvilley** [comment]
Commit forthcoming with update to MoveInDate3 in sample code.
Commit forthcoming with update to specs (ExitDate >= ReportStart, not just >)

`ExitDate >= ReportStart  `( corrected specs) and `Status1 is not NULL and ExitDate is not NULL` (sample code) have the same result.
