### ISSUE TITLE
*** 8.* Truncation Instead of Rounding

### ISSUE THREAD

**Issue by jonrwads** [abtassociates/LSASampleCode#450]
When running this data for queries in 8.x.  The code is running an insert of a possible decimal into an integer field.  In SQL Server this is truncating the value and not rounding it making the result set incorrect.

Examples

Real raw data query sample set:
1,1,-1,0,0,9,1,1768,8.1/8.2
1,1,-1,1,0,9,1,1768,8.1/8.2
1,1,-1,1,4,9,1,1768,8.1/8.2
3.1666666666666667,1,-1,3,15,-1,1,1768,8.1/8.2
3.5,1,-1,3,16,-1,1,1768,8.1/8.2
3.5,1,-1,3,23,-1,1,1768,8.1/8.2

Sample Kit Data:
"1","1","-1","0","0","9","","1","12345","8.1/8.2"
"1","1","-1","1","0","9","","1","12345","8.1/8.2"
"1","1","-1","1","4","9","","1","12345","8.1/8.2"
"3","1","-1","3","15","-1","","1","12345","8.1/8.2"
"3","1","-1","3","16","-1","","1","12345","8.1/8.2"
"3","1","-1","3","23","-1","","1","12345","8.1/8.2"

Rounded Data:
"1","1","-1","0","0","9","","1","1802"
"1","1","-1","1","0","9","","1","1802"
"1","1","-1","1","4","9","","1","1802"
"3","1","-1","3","15","-1","","1","1802"
"4","1","-1","3","16","-1","","1","1802"
"4","1","-1","3","23","-1","","1","1802"

In PostgreSQL this does not truncate but rounds causing a mismatch.  Specs say it should round to nearest integer making the sample data incorrect as far as I can tell.

**Comment by MollyMcEvilley** [comment]
The specs have been updated in sections 8.1-8.8 to indicate that the result of a built-in DB avg or average function is sufficient to meet the requirement.

**Comment by MollyMcEvilley** [comment]
(I truly regret that the sample code can't account for differences in flavors of SQL. )
