### ISSUE TITLE
* 9.2 - "inner join lsa_Report rpt on rpt.ReportStart >= n.ExitDate or n.ExitDate is null" issue in Sample Code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#452]
This is a followup to #329 

@MollyMcEvilley responded:

> The follow-up question was a very salient one... the joins to lsa_Report may have been leftover code from last year or something I wrote before creating the Status1 column -- regardless, they're not necessary and I deleted them.

However, there are still some remaining.

1. **ClientExit1**. Both spec and sample code need to be updated  ![image-20200807-103505](https://user-images.githubusercontent.com/20728145/90100705-1b832f80-dcf2-11ea-93e8-d53944c6545d.png)
2. **MoveInDate3** 
![image-20200807-103714](https://user-images.githubusercontent.com/20728145/90100868-68670600-dcf2-11ea-8524-8323701c47fb.png)

**Comment by MollyMcEvilley** [comment]
The status column doesn't indicate anything about move-in or exit dates, so there is still a need to reference it when the period is relevant.

**Comment by MollyMcEvilley** [comment]
Status1 doesn't tell us anything about exit dates, so when there are criteria comparing exit dates to the report period, we still have to join to lsa_Report.
