### ISSUE TITLE
* 7.5 - missing "the most recent ExitDate" requirement in sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#453]
Follow-up to #274 

Unfortunately, the sample code was updated with a new issue.

Now the sample code reads:
![image-20200812-094027](https://user-images.githubusercontent.com/20728145/90101112-eaefc580-dcf2-11ea-86ff-a8287a84c8fc.png)

Box 1 - selects the most recent enrollment
Box 2 - checks if the most recent enrollment has a valid CoCCode

### Issue 1
Instead, rectangle 2 should be inside rectangle 1 to describe the logic requested by the spec:

> “select all enrollments that match all conditions from the spec, and then choose the most recent only”

![image-20200812-094557](https://user-images.githubusercontent.com/20728145/90101272-428e3100-dcf3-11ea-9028-e83cb6e7fe6f.png)

### Issue 2
There is an issue in the CASE statement:

- `last.Exit1HHType` is compared with `last.Exit1HHType`
- `last.ActiveHHType` is compared with `last.ActiveHHType`
- `last.ExitCohort` is used in both CASEs
- In the spec it is said “matches tlsa_Exit.**HHType** for the tlsa_Exit.**Cohort**” but in in the sample code different fields are used. So either spec or sample code should be corrected.
![image-20200812-094900](https://user-images.githubusercontent.com/20728145/90101457-91d46180-dcf3-11ea-8294-85cdbb6e462b.png)

**Comment by MollyMcEvilley** [comment]
Commits forthcoming:
1. Correction to the specs in section 7.5 to align with the logic for system engagement status in LSAHousehold (no requirement that the _most recent_ EnrollmentCoC record matches ReportCoC -- just that some part of it occurred in ReportCoC, which is covered by inclusion in tlsa_HHID.
2. Correction to the code consistent with correction to the specs.
3.  ALSO, per existing requirements in the specs, a correction to the code to match the prior enrollment's household type based on Cohort and HHType in tlsa_Exit.  (The value in **ExitCohort** for the prior enrollment is irrelevant.)
![image](https://user-images.githubusercontent.com/6156815/90774154-ff205d80-e2c4-11ea-8c5d-49afa6037c3b.png)
