### ISSUE TITLE
* 9.1 - question about HoH restriction *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#454]
This is a follow-up to #307 

Want to confirm what should we do in section 9.1 with households:

- without HoH
- with multiple HoHs
- where HoH exited before HH member’s enroll date

**Comment by MollyMcEvilley** [comment]
Households without exactly 1 HoH are counted in the **NotOneHoH1** and **NotOneHoH3** columns of LSAReport.
Enrollments are included in DQ reporting based on the relationship of their own individual entry/exit dates to the DQ cohort period.  There are no criteria for comparing household members' entry/exit dates with those for the HoH.
