### ISSUE TITLE
** 7.3 - question **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#459]
This is a follow-up to #335 

1. Why does sample code use `qx.ExitCohort` instead of `rn.ExitCohort` to choose between `rn.Exit2HHType` / `rn.Exit1HHType` / `rn.ActiveHHType`? ![image-20200817-102415](https://user-images.githubusercontent.com/20728145/90477482-544f4a00-e0e0-11ea-9ae2-7d2f92f8f5a4.png)
2. In the spec and schema it is said to use `tlsa_Exit.HHType` to compare with [Return] `Exit2HHType` / `Exit1HHType` / `ActiveHHType` : ![image-20200817-102928](https://user-images.githubusercontent.com/20728145/90477643-9c6e6c80-e0e0-11ea-898c-d641f33bd258.png) but in the sample code (that was updated recently) `tlsa_Exit.HHType` is not used at all. Either spec or sample code should be corrected.
3. Sample code is missing deleted restriction for `hmis_EnrollmentCoC`.
4. There is `group by qx.ExitDate` in the sample code. Why?

**Comment by MollyMcEvilley** [comment]
1.  The tlsa_HHID record for the return enrollment (rn) might not have an ExitCohort value -- that's only set for enrollments with an exit in a cohort period.  The ExitCohort value for the qualifying exit (qx) determines which [cohort-specific]HHType is relevant.  
2.  The tlsa_Exit.HHType will always be the same as the [cohort-specific]HHType in tlsa_HHID for the qx, so this is the same thing.
3.  Adding `and coc.DateDeleted is null` to the join (commit forthcoming).
4.  It won't run without it.
