### ISSUE TITLE
CHTime

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#46]
(AAQ 129394) When running the LSA for a transitional housing program, is the "approximate date homelessness started" factored into the calculation of CHTime?

**Comment by MollyMcEvilley** [comment]
For all project types, time between ApproximateDateStarted and EntryDate is factored into calculation of CHTime when the client was in ES/SH or on the street in that timeframe, based on the following criteria:

```
(chn.ProjectType in (1,8)
		or hn.LivingSituation in (1,18,16)		
		or (hn.PreviousStreetESSH = 1 and hn.LengthOfStay in (10,11))
		or (hn.PreviousStreetESSH = 1 and hn.LengthOfStay in (2,3)
			and hn.LivingSituation in (4,5,6,7,15,24) ) 
		)
```
