### ISSUE TITLE
** 7.4 - HHVet question **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#460]
This is a follow-up to #336 

@MollyMcEvilley wrote

> This might be a difference in flavors of SQL? SQL Server would benefit from but doesn't have a GREATEST function -- the MAX function returns the max veteran status of all clients in the household and not individually for each client record.

I am pretty sure there IS an issue in the code. Besides, we are not alone. Ticket from other vendor about the same issue. #360

**Comment by MollyMcEvilley** [comment]
Thanks for following up -- I would not have found this one on my own (like, ever).
