### ISSUE TITLE
*** 8.13 - "Population" issues ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#461]
This is a follow- up to #400 

@MollyMcEvilley responded:

> The specs edits shown above in the commit referenced above should address all but the last bullet...
> 
> The `Core = 1` (another example is `ReturnSummary = 1`) thingie is a shortcut for groupings that are used over and over. For this little oddball grouping of popIDs, it didn't make sense (to me, anyway) to create a column to identify them in the table rather than just listing them in the code.

The spec was fixed, but new issues were created:
![image-20200814-140552](https://user-images.githubusercontent.com/20728145/90478507-12bf9e80-e0e2-11ea-8c9d-efe27d2b40e3.png)

There is no record in ref_Populations table for:

- `PopID`= 146; Age = 24; HHAdultAge = 18
- `PopID`= 148; Age = 24; HHParent = 1; HHAdultAge = 18

**Comment by MollyMcEvilley** [comment]
Corrected the specs -- not possible to have a person over 21 in a household where HHAdultAge = 18.
![image](https://user-images.githubusercontent.com/6156815/90618487-146e8c80-e1de-11ea-8467-9bc76d85ed4c.png)
