### ISSUE TITLE
*** ref_Populations: missing scenarios after last update ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#464]
While many issues were fixed in the `ref_Populations` table with the last update, there are some remaining and new issues.

1. (8.1) - no record in `ref_Populations` with: `PopID = 3 AND HHType = 99 AND HHVet = 1` **AND SystemPath = null**. The records exist for SystemPath = [1 .. 12] ![image-20200814-111057](https://user-images.githubusercontent.com/20728145/90479508-a6459f00-e0e3-11ea-9e38-2f9d8ebdb47e.png)
2. (8.1) - no record in `ref_Populations` with: `PopID = 6 AND HHType = 2 AND HHChronic = 1` ![image-20200814-111711](https://user-images.githubusercontent.com/20728145/90479622-cffec600-e0e3-11ea-9277-7bd02690097a.png)

**Comment by MollyMcEvilley** [comment]
I might be missing something but I think the records are there.
1. Created by the INSERT statement on line 649 in _1 Create Temp Reporting and Reference Tables.sql_.:
![image](https://user-images.githubusercontent.com/6156815/90615057-8e504700-e1d9-11ea-9ae0-0fe488845102.png)
2. Created by the INSERT statement on line 717 in _1 Create Temp Reporting and Reference Tables.sql_.:
![image](https://user-images.githubusercontent.com/6156815/90615489-3534e300-e1da-11ea-94a4-4c3a5370a4cb.png)
