### ISSUE TITLE
* 5.7 - "MoveInDate = ExitDate" question *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#468]
This is a follow-up to #436 

Confirm Sample code was changed.

But I have doubts about  `cal.theDate = chn.MoveInDate`, I am pretty sure it should be `cal.theDate <= chn.MoveInDate`
![image-20200814-134052](https://user-images.githubusercontent.com/20728145/90480693-77c8c380-e0e5-11ea-881d-918c6f71b23b.png)

Also, there is no mention in the spec about the new 5.7 logic.
![image-20200814-133758](https://user-images.githubusercontent.com/20728145/90480771-94fd9200-e0e5-11ea-8385-3623b648d33f.png)

**Comment by MollyMcEvilley** [comment]
`cal.theDate < chn.ExitDate` covers all dates that are less than _ExitDate_ -- they are included regardless of the relationship between _MoveInDate_ and _ExitDate_.
The line with `cal.theDate = chn.MoveInDate` adds the _ExitDate_ only for RRH enrollments where _MoveInDate_ = _ExitDate_ -- it doesn't take away the fact that dates prior to move-in are already included per the line above.

Updating the specs -- commit forthcoming:
![image](https://user-images.githubusercontent.com/6156815/90613623-a45d0800-e1d7-11ea-96e9-354d8a91239d.png)
