### ISSUE TITLE
6.12 Records in sys_TimePadded not matching

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#471]
I have been going through all of temp tables and making sure my export with the code matches what the temp tables Dave just sent out are.  Everything is spot on except sys_TimePadding.  I'm getting way more records than what the provided sample file has.  Here is just one of many clients and the process I used to determine how they got added.
ClientID = 61961

6.12.1
=====
The client is hh.Stat = 5 but the enrollment 170155 comes up for the OR statement thus excluding the client having their LastInactive set at this step.

6.12.2a
=====
Values for tlsa_Household (1 row)

FirstEntry: 8/27/2018
HHType: 99
HoHID = 61961

Values for tlsa_HHID (3 rows)

ActiveHHType:  99 for all 3
Active = 1 for one row
ExitDate < 10/1/2018 for the other 2 rows

By the end of the joins, we have the 3 rows going into the Where clause

LastInactive for hh is null, so we go on to the final AND statement....

Project Type <> 1 :: This returns one enrollment 
The OR part of this statement is TrackingMethod = 0 which returns the other 2 enrollments 

tlsa_Household.LastInactive is then set as 7/31/2018 which is correct for the final step of the section.

FINAL EVALUATION
=======================
Step 6.12.2a should bring in 3 rows for sys_TimePadded for the client

```
HoHID | HHType | Cohort | StartDate   | EndDate
61961  | 99          | 1          | 2/28/2015 | 7/20/2015
61961  | 99          | 1          | 8/1/2018   | 8/27/2018
61961  | 99          | 1          | 8/27/2018 | 9/30/2019
```
With having the other tlsa_HHID and tlsa_Household tables matching, and the code looking good, I am uncertain as to how these among many others are missing from the provided sys_TimePadded csv file.  Feel free to reach out to me if  you want to discuss further.

**Comment by dburgstrom** [comment]
I stepped through the code and at first, these three are indeed included in sys_TimePadded at step 6.12.2a:
![image](https://user-images.githubusercontent.com/64597095/91197193-10080f00-e6c9-11ea-85ad-c7e62872eb48.png)

However,  in step 7.6, those values from sys_TimePadded are deleted, and new ones selected in their place. The records require an entry in the tlsa_Exit table and there is none where HoHID=61961, so no records are re-inserted in sys_TimePadded.

![image](https://user-images.githubusercontent.com/64597095/91197941-ee5b5780-e6c9-11ea-8367-5edc085138b0.png)
