### ISSUE TITLE
LSA Calculated in Sample Data Set includes Step column

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#472]
This is not a huge issue by any means, but including the Step column in the sample export LSACalculated.csv file prevents successful upload of it to the HDX.

**Comment by dburgstrom** [comment]
Any other .csv files in that same predicament? I am getting my very own HDX account soon and will check on my end. Next upload I will leave off the step column.

**Comment by eanders** [comment]
I believe that's the only sample file structure related issue we had when uploading to the test HDX.

**Comment by dburgstrom** [comment]
OK, great. Thank you.

**Comment by MollyMcEvilley** [comment]
As a heads-up, I added notes at the end of the script with (commented out) queries to drop the column or to SELECT all but the Step column... Commit forthcoming.
