### ISSUE TITLE
HDX - Sample LSA Export Invalid Ethnicities and Races 

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#474]
The dictionary suggests that -1 is a valid value for both Race and Ethnicity, but the HDX (testing site) is currently flagging that as an error.

**Comment by MichelleNevius** [comment]
Thanks for reporting. I am experiencing this, too, as an LSAPerson.csv error that makes the upload fail.

**Comment by cwanska** [comment]
@MollyMcEvilley we are updating the HDX internal dictionary to allow a -1 value for both Race and Ethnicity in LSAPerson but to not allow it in LSAHousehold and LSAExit files. We are making manual changes and want to keep a record of it here for when you update the official dictionary.

**Comment by JulesABrown** [comment]
[LSA Data Dictionary FY2019_2020.08.25.xlsx](https://github.com/HMIS/LSASampleCode/files/5125177/LSA.Data.Dictionary.FY2019_2020.08.25.xlsx)
Molly, in an effort to make your life easier, here is an update to the data dictionary with those corrections included. Hopefully you can just review it briefly and post it. Note that we also have two internal columns we use for validation that we believe would be useful for the vendors to see: whether the column is nullable and any character length restrictions.

**Comment by MollyMcEvilley** [comment]
https://github.com/HMIS/LSASampleCode/commit/5e392bb889a005bb30b07c7e6b32aef940fa9c50

The commit here made this correction.
