### ISSUE TITLE
* 6.12.3 - lastDay.inactive possible issue in Sample Code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#475]
### Sample Code
![image-20200821-143609](https://user-images.githubusercontent.com/20728145/91142532-c89c6700-e665-11ea-9bb3-edc48df1e041.png)

`LastInactive` is updated for only records with hh.LastInactive is null.

Just want to confirm that in the nested query, we shouldn't use 'hh.LastInactive is null'.

**Comment by MollyMcEvilley** [comment]
It's not required to produce the correct output, but you could totally add it to your own code if that is your preference.  There isn't any requirement to do things in the same way the sample code does them -- just to produce results that are consistent with the specs.
