### ISSUE TITLE
* 6.12.2 - LastInactive issue in Sample Code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#476]
### Sample Code
![image-20200821-141244](https://user-images.githubusercontent.com/20728145/91143182-f7ffa380-e666-11ea-90d2-7bf7882b7e9d.png)

`hh.LastInactive is null` is used only in `6.12.2.a`, but is completely missing for `6.12.2.b`
Spec doesn’t have logic that `LastInactive` should be used in 6.12.2. Actually, it is not clear how 6.12 spec section was split in 4 part in sample code.

**Comment by MollyMcEvilley** [comment]
In 6.9, we set system engagement status (**Stat**).  
In 6.12, we're looking for the most recent inactive date.  sys_TimePadded is used to build a history of system engagement & identify the most recent gap of at least 7 nights.  We could do this for all households as described in the specs and get the correct result.
BUT!  Based on what we know from **Stat**, we can skip the resource intensive sys_TimePadded for some -- maybe most -- households:
- For first time homeless (**Stat** = 1), we already know that the household had a gap of at least two years prior to their **FirstEntry**.  
- For households returning or re-engaging with the continuum after 15-730 days (**Stat** in (2,3,4)), we already know that there's at least a 15 day gap prior to their **FirstEntry**.
- Even for continuously engaged households (**Stat** = 5), if there is no enrollment within 6 nights prior to **FirstEntry**, there's no need for sys_TimePadded.

Logically, for all of these, **LastInactive** is the day before **FirstEntry**.  Again, we don't HAVE to set it for these households in 6.12.1.  We could delete 6.12.1 entirely and get the same output.  But it's faster / less resource-intensive to set them based on what we already know.
