### ISSUE TITLE
* 6.12.2 - missing ReportEnd restriction in sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#477]
### Spec
According to the spec, `sys_TimePadded.EndDate` cannot be greater than **ReportEnd**
![image-20200821-135906](https://user-images.githubusercontent.com/20728145/91143557-8e33c980-e667-11ea-8907-0c3065333363.png)

### Sample Code
It doesn’t compare and choose **the earlier of ReportEnd** and (NNN + 6 days)
![image-20200821-140004](https://user-images.githubusercontent.com/20728145/91143653-b6bbc380-e667-11ea-994e-cdaf030eb9bc.png)

**Comment by MollyMcEvilley** [comment]
This is a totally valid point and yet I am not going to change the sample code because it won't change the output... sys_TimePadded is only used to set **LastInactive**, and in that step (6.12.3), dates are limited to <= ReportEnd
