### ISSUE TITLE
** 5.8.3, 5.10.5, 6.14.1, 6.14.2 - missing LivingSituation = 27 from Sample Code (and spec) **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#478]
LivingSituation = 27 is missing here:

- 5.10.5
- 5.8.3
- 6.14.1
- 6.14.2

![image-20200821-122828](https://user-images.githubusercontent.com/20728145/91143989-38abec80-e668-11ea-95dc-dd0ef7726066.png)

This issue exists in both Sample Code and Spec.

If it is correct to not include LivingSituation = 27, then it should be removed from Sample Code and Spec in 6 places in section 9 where LivingSituation IN (1,16,18,27) is used.

**Comment by MollyMcEvilley** [comment]
There is no change in logic here from last year (when 27 was still part of the data standards).  The information is being used in different ways in sections 5 and 6 than it is in section 9.  

The LSA doesn't count time in interim housing as ESSHStreet time, so it's not included in 5.10.5, 5.8.3, 6.14.1, or 6.14.2.  

However, in looking at data quality, the other fields ARE (were) required when _LivingSituation_ = 27, so it's appropriate to check for it in Section 9 if the value exists.
