### ISSUE TITLE
* 6.13 - missing additional condition for ProjectType = 13 in sample code (and spec)*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#479]
Based on the experience from the previous corrections to the spec and sample code, we think that one scenario was overlooked in both spec and sample code.

### Scenario

- `ProjectType = 13`
- `and` MoveInDate = ExitDate

`[date] = MoveInDate` should be included in `sys_Time`

### Spec
![image-20200821-113945](https://user-images.githubusercontent.com/20728145/91145298-14510f80-e66a-11ea-9414-b9a40c3b7721.png)

### Sample Code
![image-20200821-114007](https://user-images.githubusercontent.com/20728145/91145337-2468ef00-e66a-11ea-8d4e-9273f23c94a8.png)

**Comment by MollyMcEvilley** [comment]
This one is okay as is (yahoo!).  Here we are counting days NOT housed, so if there's a move-in date, we stop the day before it regardless of the exit date.
