### ISSUE TITLE
*** 8.22 - issue in the spec that may affect testing in HDX ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#480]
In section 8.22 it is said that for “_Universe = 10, ProjectID **must match** a record in Project.csv_.”

![image-20200805-090238](https://user-images.githubusercontent.com/20728145/91145548-80cc0e80-e66a-11ea-911c-d6567220251a.png)

But in one of the previous sections - section 8.20 - it is confirmed that “_ProjectID **may not be included** in Project.csv_”

![image-20200805-090320](https://user-images.githubusercontent.com/20728145/91145632-9f320a00-e66a-11ea-9158-6a56f7fe4a12.png)

Shouldn’t section 8.22 be updated? 

Can it cause validation error in the HDX?

**Comment by MollyMcEvilley** [comment]
DQ rows 60-62 are an exception to the general requirement that **ProjectID**s in LSACalculated must match Project.csv.  Commit forthcoming.

**Comment by MollyMcEvilley** [comment]
Correction in 8.22 and also minor edits in sections 8.9, 11, 13, 15, and 17, which previously stated that all project-level counts must match a ProjectID in Project.csv.  (Those report rows do have to match, but the blanket statement was incorrect.)
