### ISSUE TITLE
*** 5.8.3 - possible issue in Sample Code (and spec) ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#481]
Previously @MollyMcEvilley  fixed spec and sample code for similar parts in other sections.
![image-20200820-130029](https://user-images.githubusercontent.com/20728145/91145931-0f409000-e66b-11ea-9d4a-f5deee60b6d1.png)

We think that:

1. `chn.ProjectType not in (1,8)` should be removed
2. or chn.ProjectType in (1,8) should be added
3. should there be any cal.theDate <= chn.MoveInDate restrictions for ProjectType 13?

Please let us know if we are mistaken. If not mistaken, then spec also should be corrected.

**Comment by MollyMcEvilley** [comment]
Yes!  Thank you -- added chn.ProjectType in (1,8) as in option.  

Unfortunately, anything where `ProjectType in (1,8) and _PreviousStreetESSH_ = 1` is not legit data -- the data standards don't allow collection of _PreviousStreetESSH_ by ES/SH projects -- so `ProjectType NOT in (1,8) ` has to stay.  

There is no need for anything special here for RRH -- we are counting homeless days and a _MoveInDate_ won't be counted as a homeless day.

![image](https://user-images.githubusercontent.com/6156815/91464863-0d3d2380-e85b-11ea-9427-28636704b2c7.png)

**Comment by MollyMcEvilley** [comment]
Apologies... In reviewing issue #495, I realized that I should not have made the change to 5.8.3 in response to this issue -- a commit to undo it is forthcoming.

For LSA CH, regardless of project type, we do not count ES/SH/Street dates prior to project entry based on 3.917 if _LivingSituation_ indicates that the client was not in ES/SH or on the street.  Here's the relevant bit of the specs document for 5.8.3:
![image](https://user-images.githubusercontent.com/6156815/92161721-fcfaea80-edfe-11ea-9cef-6c3521de1633.png)
