### ISSUE TITLE
* 6.14.2 - issue with hn.EntryDate in Sample Code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#483]
### Review of Recent Changes:

- 8/13/2020 -  if HH member EntryDate < HoH EntryDate, insert enrollment to tlsa_Enrollment w/ HoH EntryDate
- 8/19/2020 - calculate EntryAge based on tlsa_Enrollment.EntryDate instead of hmis_Enrollment (values may differ since 8/13/2020 change to 3.4.1)

Thus, @MollyMcEvilley  updated EntryAge as it should be based on  tlsa_Enrollment.EntryDate and not hmis_Enrollment.

**What is about other sections that still use hmis_Enrollment.EntryDate:**

- 6.14.2
![image-20200821-125756](https://user-images.githubusercontent.com/20728145/91147343-fafd9280-e66c-11ea-8472-c0d736782a87.png)

- 5.10.4
![image-20200821-130154](https://user-images.githubusercontent.com/20728145/91147401-123c8000-e66d-11ea-98a5-f3f0683a7532.png)

- 5.10.5
![image-20200821-130230](https://user-images.githubusercontent.com/20728145/91147468-27b1aa00-e66d-11ea-96fd-a3b610c7f238.png)

**Comment by MollyMcEvilley** [comment]
Happily, no change needed in 6.14.2 because the there are no adjustments to EntryDate for tlsa_HHID (or for the HoH at all) -- it will always match the value in hmis_Enrollment.

Sadly (or happily as it's being corrected), changes ARE needed in 5.10.4 and 5.10.5.
