### ISSUE TITLE
*** 8.14.2, 8.14.4 - latest.Age shouldn't be used - Problem with Sample Code***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#486]
It looks like steps 8.14.2 and 8.14.4 have issues with `latest.Age`

Populations are limited to `pop.PopID between 113 and 144`. None of these populations is limited to Maximum Age. Any “latest” table code should be removed.

Code has `(pop.PopID not between 113 and 128 or latest.Age is not null)`. There is an issue in this code. I guess Molly wanted to use `IF( pop.PopID between 113 and 128, latest.Age is not null, TRUE)` but anyway spec has no `Maximum Age` logic for `pop.PopID between 113 and 144 so (pop.PopID not between 113 and 128 or latest.Age is not null)` should be removed.
![image-20200827-122336](https://user-images.githubusercontent.com/20728145/91465415-9b58e000-e842-11ea-97ae-571a09cb9ec0.png)

**Comment by MollyMcEvilley** [comment]
Updating the specs to reference max age -- people shouldn't be counted more than once.
