### ISSUE TITLE
8.19 OperationEndDate issue may cause LSA_Calculated Missing records

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#487]
Hi Molly,
While comparing the result. We think the LSA_Calculated missing a record for step 8.19.
In 8.19 section, there is a condition:  p.OperatingEndDate between cd.CohortStart and cd.CohortEnd
We think, it may need to check the OperationEndDate is NULL or not in the middle, otherwise those Project with OperatingEndDate is NULL records will be excluded from this part. 
Please take a look at this part. Thanks very much.

Best,
Chen

**Comment by MollyMcEvilley** [comment]
What we are looking for here is a count of enrollments that are still active after the project's operating end date -- so we want to exclude projects that do not have an operating end date.  

I am closing this issue, but if anything remains unclear, please feel free to re-open it.
