### ISSUE TITLE
*** 8.14.1, 8.14.3 - concerns about maximum/any age - Issues with Sample Code... and spec***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#488]
### Sample Code
![image-20200827-113948](https://user-images.githubusercontent.com/20728145/91465676-eb37a700-e842-11ea-983a-4c5baf490faa.png)

### Sample Code Issues
1. In the spec it is said to use `Maximum ActiveAge` for rows 24 .. 34.
It looks like only clients with `n.ActiveAge` = `Maximum ActiveAge` should be counted. Please confirm/correct me.
**I am pretty sure there is an issue in Sample Code because any client regardless** `Maximum ActiveAge` **will be counted for rows 24 .. 34 because of** `or pop.PopID not between 145 and 148` **restriction**.

Test Scenario:
- PopId = 27
- n.ActiveAge = 17
- latest.Age = 21
According to the spec, client shouldn’t be counted for PopId = 27 because his `Maximum ActiveAge` = 21 (so latest.Age is null).
But in fact, the client is counted regardless latest.Age is null, because of  "**OR** `pop.PopID not between 145 and 148`" restriction.

2. A similar issue is in the sample code for PopId between 145 and 148. 
Regardless that `latest.Age is null` client is counted because of “**OR** `pop.PopID not between 24 and 34`" restriction.

3. In the spec for rows 147 and 148 it is said that client should be counted **if any** Household member has `ActiveAge` = 21 and 24 correspondently. 
BUT even if there was no issues #1 and #2 the sample code would still have an issue because there is no code to check “if any Household member” restriction. 

### Spec
![image-20200827-112319](https://user-images.githubusercontent.com/20728145/91466704-5d5cbb80-e844-11ea-8c21-fb12bf8c607e.png)

![image-20200827-112454](https://user-images.githubusercontent.com/20728145/91466750-6baad780-e844-11ea-98fb-900b4d8c88ee.png)

### Spec Issue
Issue in `tlsa_Person.tlsa_Enrollment.ActiveAge` text

**Comment by MollyMcEvilley** [comment]
Thank you!
