### ISSUE TITLE
* 8.21 - hmis_Exit.ExitDate issue *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#490]
### Spec
![image-20200827-133915 (1)](https://user-images.githubusercontent.com/20728145/91472512-681b4e80-e84c-11ea-95c6-d288b1d1f158.png)

### Sample Code
![image-20200827-134046](https://user-images.githubusercontent.com/20728145/91472555-7bc6b500-e84c-11ea-8c53-ff0aa2a8fa9e.png)

1. In the spec it is said `Exit.ExitDate >= ReportStart` (“>=” is used)
But in the sample code we can see two restrictions:
a. `hx.ExitDate >= rpt.ReportStart` in the `left outer join`
b. and `hx.ExitDate > rpt.ReportStart` in the WHERE.

Which one is correct?

**Comment by MollyMcEvilley** [comment]
I'm sorry -- I forgot to close this one, but it was addressed on the day it was opened... commit cd4f508dcd03a090ff0fc34f61982e156f3b6269
(ExitDate should be greater than or equal to ReportStart.)
