### ISSUE TITLE
* 9.2 NotOneHoH1/3 - different tables are used in sample code and spec *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#491]
### Spec
![image-20200831-150743](https://user-images.githubusercontent.com/20728145/91863635-2ca1cb00-ec24-11ea-9152-355670957cce.png)

### Sample Code
![image-20200831-150736](https://user-images.githubusercontent.com/20728145/91863704-3fb49b00-ec24-11ea-8de7-6aa61cda35f6.png)

1. Spec refers to tables that are not used in sample code:

lsa_Report

tlsa_CohortDates

hmis_Exit

hmis_Project

hmis_ProjectCoC

hmis_EnrollmentCoC

2. Conditions described in the spec are not used in sample code

**Comment by MollyMcEvilley** [comment]
The output of the sample code is consistent with the logic described in the specs, so neither are wrong.  Not addressing at this time.
