### ISSUE TITLE
*** 3.3.1 - CRITICAL issue: hmis_ProjectCoC is missing in sample code and spec ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#493]
![image-20200901-101233](https://user-images.githubusercontent.com/20728145/91864844-98d0fe80-ec25-11ea-93f8-2b501b9a91de.png)

**Comment by MollyMcEvilley** [comment]
It is not there, but it is not missing.  The CoC Code restriction is on the enrollment, not the project.
