### ISSUE TITLE
** 7.6.2.b and others - hmis_Services dates possible issue **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#494]
![image-20200901-105657](https://user-images.githubusercontent.com/20728145/91865159-f49b8780-ec25-11ea-8f3f-bad1811e0d96.png)

Shouldn’t we use only bed-nights  between hhid.EntryDate and coalesce(dateadd(dd, -1, hhid.ExitDate), rpt.ReportEnd) as it is done in. i.e. `5.8.2`, 6.12.2.b, `6.13.2`

![image-20200901-110817](https://user-images.githubusercontent.com/20728145/91865286-1432b000-ec26-11ea-8694-d9f3cd7c8ec9.png)

Other sections that also should be updated with validation that bed-night is within project stay are:

- 8.9
- 8.10.1
- 8.10.2
- 8.11
- 8.12.1
- 8.12.2
- 8.13
- 8.14.1
- 8.14.2
- 8.14.3
- 8.14.4
- 8.15
- 8.16.1
- 8.16.2
- 8.17
- 8.18.1
- 8.18.2

**Comment by MollyMcEvilley** [comment]
Yes -- in any system that isn't programmed to prevent this invalid data, reporting procedures for that application must exclude it.  Ref this language in section 3.3:
![image](https://user-images.githubusercontent.com/6156815/92748559-46918b00-f353-11ea-8c2d-3f50a303653b.png)
