### ISSUE TITLE
* 9.1 - MoveInDate discrepancy *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#497]
### Spec
There is no separate section with instructions for MoveInDate
### Sample Code
Sample code has a left join with nested queries
![image-20200831-131056](https://user-images.githubusercontent.com/20728145/92078259-cf685f80-ed72-11ea-81f3-06c2fc2b3def.png)

1. Why is `distinct` used if we already have `group by hh.HouseholdID`?
2. Why is `min(hh.MoveInDate)` used if, according to HMIS Standards, `MoveInDate` is collected for Head of Household only and only on enroll screen so now it is not possible to collect `MoveInDate` in status/annual assessment or exit screen. So Why is min() used? Or is it an adjustment for scenarios when a household has more than 1 HoH?

**Comment by MollyMcEvilley** [comment]
Apologies -- I misunderstood the issue.  Added this clarification to the specs:
![image](https://user-images.githubusercontent.com/6156815/94825423-2db94a00-03d4-11eb-9f3d-5eed2f779500.png)

and tweaked the sample code...
