### ISSUE TITLE
* 9.1 - SSNValid issue *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#498]
![image-20200831-125333](https://user-images.githubusercontent.com/20728145/92078510-3d148b80-ed73-11ea-808d-b1a344eb7538.png)

![image-20200831-125353](https://user-images.githubusercontent.com/20728145/92078526-4aca1100-ed73-11ea-91ad-3634af191970.png)

Shouldn’t  `SSNValid` be null if `c.SSNDataQuality = [99, null]`? There is no such rule either in spec or in sample code. Molly, please advise.

**Comment by MollyMcEvilley** [comment]
No, the specs and sample code are consistent with the intention.  **SSNValid** is only NULL when the client declined to provide an SSN for a specified reason -- it's used for the count in LSAReport.**SSNNotProvided**.
![image](https://user-images.githubusercontent.com/6156815/92729551-813df800-f340-11ea-93c9-b6605dc44122.png)
