### ISSUE TITLE
* 9.1 - "EntryDate <= CohortEnd" is missing in sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#499]
Both sample code and the spec were updated recently, that caused new issues.
### Spec
![image-20200831-120312](https://user-images.githubusercontent.com/20728145/92078743-a2687c80-ed73-11ea-835d-30686351ff0f.png)
### Sample Code
`EntryDate <= CohortEnd` is missing in the sample code

Also. shouldn’t we check that `ExitDate > EntryDate` where `ExitDate` is not null?

**Comment by MollyMcEvilley** [comment]
Added EntryDate <= CohortEnd to the sample code.
We're looking for DQ issues in this section, so we don't want to exclude enrollments BECAUSE of a DQ issue here.
