### ISSUE TITLE
** 9.1 - Status1 issues in Sample Code and Spec **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#500]
This is a follow-up to #321 

@MollyMcEvilley  updated 9.1 recently so I started working on this section in Clarity. I think I found 2 more issues:
### Sample Code
![image-20200831-123957](https://user-images.githubusercontent.com/20728145/92079054-215db500-ed74-11ea-8063-37ba5f9d36c3.png)

### Spec
![image-20200831-123857](https://user-images.githubusercontent.com/20728145/92079079-30dcfe00-ed74-11ea-8541-de14961e7470.png)

### Issue 1
Sample code has a scenario to set Status1 = null when `x.ExitDate < cd1.CohortStart`. There is no such scenario in the spec.
### Issues 2
Sample code uses `cd1.CohortStart` instead of `cd3.CohortStart` for Status3
![image-20200831-124522](https://user-images.githubusercontent.com/20728145/92079226-68e44100-ed74-11ea-9b47-4eddcf9b4f63.png)

**Comment by MollyMcEvilley** [comment]
Issue 1:  Adding a line to the **Status1** section in the specs:  

![image](https://user-images.githubusercontent.com/6156815/92165624-5403be00-ee05-11ea-9289-0d82e8f19385.png)

Issue 2:  correcting the table alias for setting Status3
