### ISSUE TITLE
* 7.6.1 - issue in sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#503]
According to the spec, **LastInactive** cannot be earlier than 9/30/2012
![image-20200825-115800](https://user-images.githubusercontent.com/20728145/92079838-72ba7400-ed75-11ea-9dc1-591d69ecb4e5.png)

9/30/2012 is not used in the sample code:
![image-20200825-121031](https://user-images.githubusercontent.com/20728145/92079938-8fef4280-ed75-11ea-8621-caf3e1143932.png)

Also, `Stat <> 5` restriction is not documented in the spec.

**Comment by MollyMcEvilley** [comment]
Thank you -- added a CASE statement. Commit forthcoming.
![image](https://user-images.githubusercontent.com/6156815/93491957-4572d780-f8d8-11ea-9f8c-adf38d0e4d02.png)
Stat <> 5 isn't core to the logic -- it just cuts down on the processing.  There was a section in the specs about using it as an optional limitation, but it was removed per vendor request on an office hours call as it was not critical to the logic and therefore confusing.
