### ISSUE TITLE
* section 6 - "hhid.EntryDate > hh.LastInactive" undeclared restriction *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#504]
### Sample Code
![image-20200821-111310](https://user-images.githubusercontent.com/20728145/92080147-e8264480-ed75-11ea-82b1-d4c93d05b348.png)

`hhid.EntryDate > hh.LastInactive` restriction appears 6 times for:

- 6.13.1
- 6.13.2
- 6.13.3
- 6.14.1
- 6.14.2
### Spec
There are no any instructions for `hhid.EntryDate > hh.LastInactive`
![image-20200821-111400](https://user-images.githubusercontent.com/20728145/92080258-173cb600-ed76-11ea-9e5e-693438aaf2c4.png)

**Comment by MollyMcEvilley** [comment]
The specs and the code are logically consistent.  In order for any part of an enrollment to be > **LastInactive**, every part of the enrollment, beginning with the entry date, must be > **LastInactive**. (No change.)
