### ISSUE TITLE
* Section 7 - DateDeleted restriction is missing in Sample Code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#507]
This is a follow-up to #343 

@MollyMcEvilley wrote

> This might have been a dupe or I might have forgotten to close it when I added the DateDeleted restrictions... but it has been addressed.

but, unfortunately, issue 1 still remains:
![image-20200828-111553](https://user-images.githubusercontent.com/20728145/92081189-8ebf1500-ed77-11ea-870f-a8efdce1557f.png)

**Comment by MollyMcEvilley** [comment]
Added in the commit referenced above.
