### ISSUE TITLE
Step 4.70 - Data Quality 3 Year Period - Code and Specification Discrepancy

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#51]
Where we get the records for dq_Enrollment (For the Data Quality 3 Year Period), 

Should it be: 
Exit Date that falls in the 3 years BEFORE the ReportStart Date (according to the Code Doc) 
OR 
Exit Date that falls in the 3 years BEFORE the ReportStop Date (according to the Specification Doc) 

Specificaitons Doc Says:
ExitDate is NULL or ExitDate >= (ReportEnd - 3 years)
Code Doc says:
ExitDate is NULL or ExitDate >= dateadd(yy, -3, ReportStart)

Thanks!

**Comment by MollyMcEvilley** [comment]
Corrected
