### ISSUE TITLE
* 7.6.3 - Cohort in lastDay *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#510]
This is a follow-up to #485 

In fixing the sample code, the spec wasn't updated. Please review and update the specs to include the changes. https://github.com/HMIS/LSASampleCode/commit/e7bebcc42cfba2e2cf158e2ec5c3e1c2b84e700f

**Comment by MollyMcEvilley** [comment]
I can't tell which part you're referring to for sure... the changes associated with that issue were in sections 7.2 and 7.5 and the specs were updated in both places.
