### ISSUE TITLE
* 9.1 - missing HoH restriction for MoveInDate *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#513]
![image-20200901-103654](https://user-images.githubusercontent.com/20728145/92288743-d8684680-eec2-11ea-9258-a0254bd049b7.png)

Shouldn’t MoveInDate be checked for HoHs only? Just wonder if “and hh.RelationshipToHoH = 1” should be added.

**Comment by MollyMcEvilley** [comment]
No change because no impact on output.  This is just populating the dq_Enrollments table -- DQ reporting on MoveInDate1/3 in 9.2 is limited to HoH.
