### ISSUE TITLE
* 8.9 - discrepancy in tlsa_CohortDates usage * 

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#515]
Followup to #363 

### Spec
![image-20200821-104034](https://user-images.githubusercontent.com/20728145/92289295-d901dc80-eec4-11ea-80d2-98bc3ae5d5e2.png)

### Sample Code
![image-20200727-090256 (1)](https://user-images.githubusercontent.com/20728145/92289318-ecad4300-eec4-11ea-8003-c0a758139f12.png)

According to the spec, `ExitDate = CohortStart` is excluded.

But in the sample code `ExitDate = CohortStart` is possible if:

- `ProjectType = 13`
- and `ExitDate = MoveInDate`

### Issue
Spec should be updated. And not only 8.9 should be updated but also;

- 8.10.1
- 8.10.2
- 8.11
- 8.12.1
- 8.12.2
- 8.13
- 8.14.1
- 8.14.2

**Comment by MollyMcEvilley** [comment]
Updating specs sections 8.9 through 8.18 - per section 3.3, count an RRH exit date as a bednight if it is the same as the move-in date.  Commit forthcoming.
