### ISSUE TITLE
* 7.7 - question about 365 days for SystemPath = -1 *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#516]
Followup to #349 

@MollyMcEvilley responded:

> Yes -- the specs and the code match so no change...

We submitted a question in July, but it was closed on August, 27 …

Yes, both spec and sample code for 7.7.1 match and use 365 days. But shouldn’t 365 days be replaced with 1 year so code can be used for a leap year (366 days)?

Previously we explained similar concerns for 5.10 section, and it was taken into account, and “365 days” were replaced with “1 year”.

**Comment by MollyMcEvilley** [comment]
In retrospect, I should not have made that change.  The code can be used for 365 days regardless of whether it is a leap year or not.  

At this point, the only changes to the code and/or the specs that I'm supposed to be making are to correct things that are wrong.

**Comment by MollyMcEvilley** [comment]
(NOTE:  The commits referenced above are not related to this issue -- they are related to issue #519.
