### ISSUE TITLE
* 6.2 - question about HHNoDOB and HHChild *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#519]
In both spec and sample code client is counted as HHAdult if there is no other enrollment where the same client is counted as HHChild so client cannot be counted in more than 1 category.

Running LSA on one of live instances, we faced the situation that a client is counted in both HHNoDOB and HHChild (client’s birth day is after EnrollDate #1 and before EnrollDate #2).

Should we keep counting client in both HHNoDOB and HHChild? Or it should be counted either HHNoDOB or HHChild? Please ask Molly to advise (in case corrections are needed, both sample code and spec should be updated).

**Comment by MollyMcEvilley** [comment]
You are correct -- for any given household, a person should only be counted once.  To ensure that this occurs, if a DOB is invalidated for any enrollment, the person's age should be considered unknown LSA-wide.  
To accomplish this, updating specs and sample code in section 3.5.

**Comment by MollyMcEvilley** [comment]
These commits address this issue (they were mistakenly associated with the wrong issue number).

MollyMcEvilley added a commit that referenced this issue 5 hours ago
@MollyMcEvilley
Update 3_2 to 3_6 HMIS Households and Enrollments.sql
a1f2a89

MollyMcEvilley added a commit that referenced this issue 5 hours ago
@MollyMcEvilley
Update LSA Programming Specifications FY2019.docx
3dfb050
