### ISSUE TITLE
LSACalculated 

### ISSUE THREAD

**Issue by MollyMcEvilley** [abtassociates/LSASampleCode#53]
In the test kit, there are 5,191 rows in LSACalculated , but only 5,182 distinct combinations of  value, cohort, universe, hhtype, population, systempath, projectid, reportrow, reportid.  This would indicate that some values are not properly combined in the sample code / are being grouped by a value that doesn't appear in LSACalculated.

**Comment by nathanandrade74** [comment]
I noticed that the duplicate rows I found were all in ReportRow 56. Could the duplicates be because section 4.66 (Get counts of bed nights by project type) is grouping by projectID?

**Comment by TimLawrencePCL** [comment]
Once I get OH-500 uploaded I'll run a new set of sample upload files using all the latest code and check the totals.  It may not make much difference, but we should rule out that the problem may have already been fixed.

**Comment by MollyMcEvilley** [comment]
@nathanandrade74 -- Yes, thank you! Will fix.

**Comment by MollyMcEvilley** [comment]
Found another extraneous ProjectID in GROUP BY for 4.68 -- both fixed.
