### ISSUE TITLE
* 7.6.3 - important question *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#534]
@MollyMcEvilley , we are trying to rework the report, where possible, to improve run times. 

I wonder if we need "ex.LastInactive is null" in the lastDay nested query. Please advise.

![image-20200908-134655](https://user-images.githubusercontent.com/20728145/92496374-e6f97b00-f1ac-11ea-9a06-de2f45c7965b.png)

**Comment by michelleogburn** [comment]
One of the reasons why we asked about "ex.LastInactive is null" is that 7.6.3 uses sys_TimePadded that is filled in steps 7.6.2.a and 7.6.2.b using a mandatory “LastInactive is null" restriction.

Also curious if we indeed need “`and stp.Cohort = ex.Cohort`” in 7.6.3. What if `hhid.EntryDate` and `hhid.EntryDate - 1` have different cohorts? Even if there are records in sys_TimePadded on `hhid.EntryDate - 1` they will not be found because of “and stp.Cohort = ex.Cohort” restriction => stp.HoHID is null is true and `[inactive] = hhid.EntryDate - 1`

**Comment by MollyMcEvilley** [comment]
1.  You can re-work any of the sample code to improve performance as long as it's consistent with the logic defined by the specs.  
2.  I'm not totally sure I understand what is being asked here, but:  tlsa_HHID has cohort-specific household types.  If an enrollment is relevant to determining **SystemPath** for the same **HoHID**/**HHType** in different cohorts, there will be records in sys_TimePadded for each of the cohorts, so the enrollment should be found even with the requirement that the cohorts match.  (HHType is cohort-dependent and one enrollment might have different HHTypes for different cohorts.) 

(Please re-open this vs. creating a new issue if this does not answer the question.)
