### ISSUE TITLE
HDX rejects HMISParticipatingProject 99

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#547]
Hi @cwanska, we're receiving an upload error for an HMISParticipatingProject value of 99. Should this really prevent upload?  

According to the HMIS CSV spec this should be 1.7 which would include 0,1,99.  I see that in the LSA Data Dictionary this is List 5 which is only 0,1. Is 99 intentionally excluded?

**Comment by MollyMcEvilley** [comment]
It makes sense that the HDX would reject a 99 value for any PDDE data. A response isn’t dependent on outside info — a worker (i.e., a user working with a client) might forget to collect data and be unable to obtain it later, but a CoC doesn’t have the option to decline to specify whether or not the project is participating.

**Comment by eanders** [comment]
Thanks @MollyMcEvilley

**Comment by MollyMcEvilley** [comment]
Hi,
This is something that can't be programmed around -- the CoC will have to fix the record(s) and re-run the LSA.  (By any standard, I think it's a reasonable expectation that an HMIS administrator and/or whoever is running the LSA must be aware of -- or able to find out -- whether or not a continuum project is participating in HMIS.)
