### ISSUE TITLE
*** 8.13 - sample code doesn't have "tlsa_Enrollment. Maximum ActiveAge" ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#548]
The spec was updated, but it wasn't reflected in either the release notes or in sample code so it is now one of the critical issues.
### Spec
`“tlsa_Enrollment.Maximum ActiveAge = NNN”` was added
![image-20200915-145757](https://user-images.githubusercontent.com/20728145/93363819-9f9e6a80-f7fc-11ea-913c-c7c40deeaf65.png)

### Sample Code
There is no “tlsa_Enrollment.Maximum ActiveAge = NNN” logic in 8.13
![image-20200915-145916](https://user-images.githubusercontent.com/20728145/93364342-484cca00-f7fd-11ea-85ba-020eef99ce5e.png)

Either spec or sample code needs to be updated.

**Comment by MollyMcEvilley** [comment]
Updating code - commit forthcoming.
