### ISSUE TITLE
*** 8.14.1, 8.14.3 - concerns about maximum/any age ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#549]
This is a followup to #488

1. Row 147 was fixed, but now row 148 still has an issue
![image-20200911-130304](https://user-images.githubusercontent.com/20728145/93387929-d08f9700-f81e-11ea-9237-0ea6e023b071.png)
2. What is the “(any household member)” text in rows 147 and 148 about. Should it be removed?
3. For “Maximum ActiveAge“ rows only clients with `ActiveAge` = MAX(`ActiveAge`) are selected. Please confirm if it is correct. 
We have doubts because of “(any household member)” text that makes us think that the whole household regardless of HH member’s age should be counted if MAX(HH member’s age) = 21(24)
![image-20200911-130625](https://user-images.githubusercontent.com/20728145/93388186-2a905c80-f81f-11ea-9c9d-8af935f060e5.png)

**Comment by MollyMcEvilley** [comment]
Row 147 counts any and all household members (including the HoH) who are part of a parenting youth household and whose maximum active age is 21.
Row 148 counts any and all households members (including the HoH) who are part of a parenting youth household and whose maximum active age is 24.
