### ISSUE TITLE
* 6.13 - issues in the spec *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#552]
This is a follow-up to #514 

@MollyMcEvilley reworked the spec, but one issue remains:
### New Spec
![image-20200911-095928](https://user-images.githubusercontent.com/20728145/93389907-b7d4b080-f821-11ea-90c8-770bbde40a9f.png)
### Sample Code
![image-20200911-100046](https://user-images.githubusercontent.com/20728145/93389969-d044cb00-f821-11ea-9ad0-7de86489952f.png)
### Issue in the Spec
Second row where Value = 4 is missing:
```
[Date] >= EntryDate and
[Date] <= the first non-NULL of [ExitDate – 1 day] and ReportEnd
```

that exists in the sample code.

**Comment by MollyMcEvilley** [comment]
The specs and the code are logically consistent.  

This is the first part of that logic section and applies to all dates:
![image](https://user-images.githubusercontent.com/6156815/93464738-a2aa6100-f8b7-11ea-8cf1-abef50cccb90.png)

No change.
