### ISSUE TITLE
* 7.6.1 - missing 9/30/2012 comparison for LastInactive in the sample code *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#553]
### Spec
![image-20200915-101959](https://user-images.githubusercontent.com/20728145/93390447-8e685480-f822-11ea-9efd-a2651e11010d.png)
### Sample Code
![image-20200915-102134](https://user-images.githubusercontent.com/20728145/93390488-9cb67080-f822-11ea-9e17-c69644376cad.png)
### Issue in Sample Code
**LastInactive** is missing “is the later of 9/30/2012“ restriction

**Comment by MollyMcEvilley** [comment]
Addressed in commit e13c377523c8b412c5f0e63873f77daf6012fd12
see #503 for more detail...
