### ISSUE TITLE
** 8.14.3 and 8.14.4 - issue with "latest" age **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#554]
![image-20200916-125308](https://user-images.githubusercontent.com/20728145/93390627-d9826780-f822-11ea-9ab1-9e9c2d71cd6d.png)
Now in both 8.14.3 and 8.14.4 `latest.Age` depends on `hhid.ProjectType` (see hightlighted).

We think there is an issue and highlighted `hhid.ProjectType` should be removed because `Universe = 16` should be for combined ES/SH/TH

**Comment by MollyMcEvilley** [comment]
![image](https://user-images.githubusercontent.com/6156815/93468458-01bea480-f8bd-11ea-8b7a-690005dcc0bd.png)

I think the best answer I can give here is that the specs do not go into enough detail about this to make either option (leaving it or removing it) definitely wrong or definitely right. A "clarification" could constitute a change in some systems but not others.  Given the date and looming deadline, I'm going to leave both alone for now -- although I'm also going to leave this issue open and flag it, at least until after the office hours call today.
