### ISSUE TITLE
** 3.3.1 - LastBedNight and ExitDate issue (overlooked scenario) **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#555]
### Scenario
Project settings:

- Project.ProjectType = 1 
- Project.TrackingMethod = 3
- Project.OperatingEndDate = 10/02/2018

Hoh’s project stay:

- Enrollment.EntryDate = 10/01/2018
- Exit.ExitDate = 10/15/2018
- Bed Nights (Services.RecordType = 200) DateProvided are:
   - 10/01/2018
   - 10/02/2018
   - 10/10/2018
   - 10/14/2018
### LastBedNight (Spec and Sample Code)
According to the spec and sample code, **LastBedNight = 10/02/2018** (_equals to Project.OperatingEndDate_)
![image-20200917-125313](https://user-images.githubusercontent.com/20728145/93611780-94297b80-f983-11ea-8fb3-3ea5f7f290ce.png) 
![image-20200917-125623](https://user-images.githubusercontent.com/20728145/93611825-a0153d80-f983-11ea-989d-8f9f0b560edc.png)
### ExitDate (Spec and Sample Code)
According to the spec and sample code, **[effective Exit Date] = LastBedNight + 1day = 10/03/2018** - one day **after** Project._OperatingEndDate_
![image-20200917-130540](https://user-images.githubusercontent.com/20728145/93612008-dce13480-f983-11ea-96f5-a43586f6c329.png)
But in this case, **[effective Exit Date]** that is one day **after** Project._OperatingEndDate_ **is inconsistent with another part of the spec**
![image-20200917-131105](https://user-images.githubusercontent.com/20728145/93612170-07cb8880-f984-11ea-9f46-4349a932ecef.png)

Please advise.

**Comment by MollyMcEvilley** [comment]
This is a very good point.
