### ISSUE TITLE
** 9.2 - NoCoC and NotOneHoH1/3 - hmis_Project questions **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#556]
This is a followup concern with #347 

@MollyMcEvilley responded:

> Question 1
>  
> Yikes. Project types 9 and 10 should be excluded from every part of the LSA except the PDDE files... I added the project type restriction in 9.1.
> 
> Question 2
> 
> Yes, the OperatingEndDate criteria was intentionally excluded. We are looking for DQ issues, so we don't want to exclude an enrollment from dq_Enrollment BECAUSE of a DQ issue.

Molly has fixed the sample code, but the spec still needs to be updated:
![image-20200918-102415](https://user-images.githubusercontent.com/20728145/93830923-657eff80-fc26-11ea-83ef-b75e415e9975.png)

**Comment by MollyMcEvilley** [comment]
Correcting the file name (it's LSAReport and not LSACalculated) and adding the file type restriction.  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/94808555-4cf9ac80-03bf-11eb-89d1-13dd47c6bb9b.png)
