### ISSUE TITLE
HDX rejects HMISParticipatingProject=99 error

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#558]
Hi Molly and Cicely,

We have encountered the same issue with #547. I have quote Molly's response in this question. However it is not seems clear for us regarding how to handle it. Would you please be more specific? Should we do data fixing for HMISParticipatingProject='99'? As 99 is allowed in HUD CSV project.

Thanks.

Best,
Chen

It makes sense that the HDX would reject a 99 value for any PDDE data. A response isn’t dependent on outside info — a worker (i.e., a user working with a client) might forget to collect data and be unable to obtain it later, but a CoC doesn’t have the option to decline to specify whether or not the project is participating.

_Originally posted by @MollyMcEvilley in https://github.com/HMIS/LSASampleCode/issues/547#issuecomment-691144869_

**Comment by MollyMcEvilley** [comment]
Hi,
This is something that can't be programmed around -- the CoC will have to fix the record(s) and re-run the LSA. (By any standard, I think it's a reasonable expectation that an HMIS administrator and/or whoever is running the LSA must be aware of -- or able to find out -- whether or not a continuum project is participating in HMIS.)
