### ISSUE TITLE
dictionary values for some lsaexit fields are broken. 

### ISSUE THREAD

**Issue by TimLawrencePCL** [abtassociates/LSASampleCode#56]
At least the fields below seem to have issues when populating ref_lsaValues.  I can probably find the fix -- just not this afternoon.

lsa_Exit.HHVet
lsa_Exit.HoHRace
lsa_Exit.HHAdultAge 
lsa_Exit.HHParent
lsa_Exit.SystemPath

**Comment by MollyMcEvilley** [comment]
Thank you!  The values being inserted for ColumnNumber for HHVet, HHDisability, HHFleeingDV, HoHRace, HoHEthnicity, HHAdultAge, HHParent, AC3Plus, and SystemPath were all +1 -- they are columns 8-16, but were being set as columns 9-17.
