### ISSUE TITLE
*** sys_TimePadded primary key constraint breaks the process (including sample data kit)

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#561]
Hello

In the group of sample code updates released yesterday, one of the changes added this line:

`constraint pk_sys_TimePadded primary key clustered (HoHID, HHType, Cohort, StartDate)`

to the "create table sys_TimePadded" statement. Both statements inserting records to this table (6.12.2 and 7.6.2) are unions of two select statements, and in both cases there is nothing to prevent those statements from returning records with the same key.

For example (using sample data kit), in case of 6.12.2, the first statements returns the following set of records (the columns with asterisks were added for debugging purposes):

```
  hohid | hhtype | cohort | enrollmentid* | projecttype* | trackingmethod* | entrydate  |    case    | step
-------+--------+----------+--------------+-------------+----------------+------------+------------+----------
 62400 |      1 |        1 | 170190       |           1 |              0 | 2018-09-06 | 2018-09-13 | 6.12.2.a
 62400 |      1 |        1 | 170130       |           2 |                | 2018-07-06 | 2018-08-05 | 6.12.2.a
 62400 |      1 |        1 | 170378       |          13 |                | 2018-09-05 | 2019-09-30 | 6.12.2.a    <----
 62400 |      1 |        1 | 170328       |           2 |                | 2018-09-07 | 2019-09-30 | 6.12.2.a
 62400 |      1 |        1 | 170333       |          13 |                | 2018-04-11 | 2019-09-30 | 6.12.2.a
```

while the second one returns this:

 ```
hohid | hhtype | cohort | enrollmentid* | projecttype* | trackingmethod* | dateprovided |  provided + 6  | step
-------+--------+----------+--------------+-------------+----------------+--------------+------------+----------
 62400 |      1 |        1 | 170185       |           1 |              3 | 2018-09-02   | 2018-09-08 | 6.12.2.b
 62400 |      1 |        1 | 170185       |           1 |              3 | 2018-09-03   | 2018-09-09 | 6.12.2.b
 62400 |      1 |        1 | 170185       |           1 |              3 | 2018-09-04   | 2018-09-10 | 6.12.2.b
 62400 |      1 |        1 | 170185       |           1 |              3 | 2018-09-05   | 2018-09-11 | 6.12.2.b    <----
 62400 |      1 |        1 | 170161       |           1 |              3 | 2018-08-07   | 2018-08-13 | 6.12.2.b
```

The records that violate primary key constraint were maked with an arrow. I know the actual statements are "distinct", but nothing prevents them from returning the exact conflicting records (no defined order, no grouping or exclusions). And in our case they do.

This is just an example of one HoHID that happened to trigger the conflict first; but there are others in the same situation. Identical conflict is being encountered in 7.6.2, with HoHID = 62168 being the first one to encounter the conflict during the statement execution.

There are also other errors in the deployed code, like missing closing brackets, but those are triggering syntax erros and thus are pretty easy to spot.

Best regards

**Comment by MollyMcEvilley** [comment]
Thank you -- that's an excellent point.  I have reverted the commit that added the primary key constraint.
