### ISSUE TITLE
6.11 - Specs vs Code (Date not added to sys_Time where ExitDate is same as MoveInDate)

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#562]
https://github.com/HMIS/LSASampleCode/blob/4e18e3922df5f71e55ba74a991e57b4e9291b8db/6_1%20to%206_19%20LSAHousehold.sql#L663-L665

![Snag_381dbb80](https://user-images.githubusercontent.com/44415627/94294771-ef301500-ff25-11ea-8319-4ede2fd4b0de.png)

We are all of a sudden getting rejected uploads on a previously known good set of data.
One of the errors is the following:
'The LSAHousehold field RRHHousedDays, which reports days housed in RRH, must NOT equal 0 days if the household was placed, either during or before the report period (as reported in RRHMoveIn), and if the household was served in RRH during the report period (as reported in RRHStatus), and if the household was not simultaneously housed in PSH (which they could not have for the households you reported in this row since PSHHousedDays=0 here). The following row in your LSAHousehold file violates that rule.'

We've pinpointed the cause of the error back to six clients who have an RRHStatus of 22 or 12, an RRHMoveIn of 1, RRHHousedDays of 0 and PSHHousedDays of 0.  These clients have RRH MoveInDates that are the same as their ExitDates

Looks like the code is not allowing that in.

**Comment by MollyMcEvilley** [comment]
Thanks!
