### ISSUE TITLE
HDX doesn't accept sample LSA export

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#564]
@cwanska , I sent this as an email, but it occurs to me that others may attempt this, and we should probably track this here.  Uploading the 9/21/2020 Sample LSA export is being rejected by the HDX.  Errors attached.  I believe, if the sample code is working correctly, the sample data set should generate a file compatible with HDX.

[sample-data-set-validations.pdf](https://github.com/HMIS/LSASampleCode/files/5293627/sample-data-set-validations.pdf)

**Comment by jbloescw** [comment]
I don't get the LSA Exit error on my data set (which is not the HUD data set), but those errors are the ones we are getting also.  This is definitely a show stopper.  Uploading our error sheet to confirm what Elliot is seeing.
[CWDS_upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/5293742/CWDS_upload-errors.pdf)

**Comment by cwanska** [comment]
We are looking into the issue to determine if these data validations are capturing real issues. If there is an error in the calculation we will immediately roll back.

**Comment by cwanska** [comment]
We have rolled this back temporarily while the flags are being finalized in SAS.
