### ISSUE TITLE
Step 5.17 - Causes Flag 270

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#566]
Hi,
We have a HouseholdID active in RRH ProjectType=13; with 4 participants/enrollments (EntryAges and ActiveAges 34,17,17,99):

- Step 5.12 correctly sets HHTypeRRH=2 (AC)

- Because one of the enrollments has an ActiveAge=99 it causes Step 5.17 to set HHAdultAge=-1 in tlsa_HHID for all enrollments linked to the HouseholdID

- In Step 5.18, HHAdultAgeACRRH is only set where HHAdultAge between 18 and 55, and since HHAdultAge=-1, HHAdultAgeACRRH will be set to -1

- This causes Flag 270: "HHAdultAgeACRRH in the LSAPerson file cannot equal -1 (not applicable) for people who were served in AC households in RRH (as reported in the HHTypeRRH field)."

Since HHAdultAge=-1 (No adults in household), it Flags the Household. We know there is at least one adult Age=34 in the HouseholdID, should we have set HHAdultAge=-1 in Step 5.17?

Thanks!

**Comment by MollyMcEvilley** [comment]
No, step 5.17 is correct and consistent with the specs -- **HHAdultAge** and related column values should be set to -1 if we don't know all adults' ages.

The Dictionary incorrectly defined -1 as 'No adults in household' -- the correct definition is just 'n/a' and a forthcoming commit for the Dictionary will address that.  

Resolution of this issue will require correction of flag 270 (and any similar).

**Comment by cwanska** [comment]
Flag and data dictionary updated. closing this issue.
