### ISSUE TITLE
Flag 675: LSAReport and LSAPerson (Upload Error)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#567]
Issue text:

> There is a discrepancy between your LSAReport and LSAPerson data. The total number of adults served during the report period differs between the two files.

|LSA Report: UnduplicatedAdult1|243|LSAPerson: Total Adults (according to the AdultEST, AdultRRH, and AdultPSH fields)|183|
|---|---|---|---|

UnduplicatedAdult1 = # of clients who had enrollments within 3-year-period even if they exited before ReportStart.

AdultEST, AdultRRH, and AdultPSH =  # of clients who had enrollments within 1-year-period ( between ReportStart and ReportEnd).

So it is absolutely logical that UnduplicatedAdult1 can be greater than sum of AdultEST, AdultRRH, and AdultPSH.

Please ask HDX team to review their validation for flag 675.

**Comment by TanyaPieterse** [comment]
Hi Michelle,
After a few hours of research on our Flag 675, I came to a different conclusion.  I believe it is our dataset that is causing this Flag 675 and submitted a Ticket #571 with my explanation of what is happening.  

UnduplicatedClient1, UnduplicatedAdult1 and DOB1 all look at the enrollments where the Status=1, in other words if they were served in the reporting period.  BUT these counts include enrollments where the HouseholdID has RelationshipToHoH issues, and these enrollments are excluded from the LSAPerson file - making the count less in LSAPerson.

Thanks!

**Comment by MollyMcEvilley** [comment]
**UnduplicatedAdult1** is a totally different universe from **AdultEST**/**RRH**/**PSH** -- which are a subset of **AHAREST**/**RRH**/**PSH**.  The flag is based on an erroneous assumption.

**Comment by AzimShivji-Abt** [comment]
No, the error is in the Adult variables. They are not supposed to be limited to the AHAR universe.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by cwanska** [comment]
The flags have been edited to suppress this validation for the 2019/2020 upload cycle. We will revisit the issue when updating the specs and sample code for the 2021 upload cycle.
