### ISSUE TITLE
** 3.3.1 - LastBedNight and ExitDate issue (overlooked scenario) **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#569]
Correcting issues identified in #555 unfortunately created some new issues.

1. using this restriction in 3.3.1 
![image-20200928-124605](https://user-images.githubusercontent.com/20728145/94612879-94b1f400-0258-11eb-9efe-3926c78eb8eb.png)
But, according to spec, Projects must be active since 10/01/2012 and not since ReportStart.
![image-20200928-124107](https://user-images.githubusercontent.com/20728145/94612947-b1e6c280-0258-11eb-9d57-4073b72797e6.png)

![image-20200928-124648](https://user-images.githubusercontent.com/20728145/94612974-bca15780-0258-11eb-84f4-2ff21a15b525.png)

2. Inserted code **does not** solve the issue we reported. Now we have

  - tlsa_HHID.LastBednight = OperatingEndDate
  - tlsa_HHID.ExitDate = OperatingEndDate

That is against the spec
![image-20200928-125903](https://user-images.githubusercontent.com/20728145/94613120-ece8f600-0258-11eb-9289-b83bd66b069a.png)

Please ask Molly to fix both issues and ensure the spec is updated accordingly (if needed).

**Comment by MollyMcEvilley** [comment]
1.  Thank you.  Deleting the erroneous condition related to **ReportStart** from the join to hmis_Project -- the correct conditions are in the WHERE clause.
2.  Specifying in specs and code that bednights >= _OperatingEndDate_ are not relevant.

Commits forthcoming.
