### ISSUE TITLE
General Issues in Upload Review

### ISSUE THREAD

**Issue by MollyMcEvilley** [abtassociates/LSASampleCode#57]
(Discussion thread) Julia is going to use this Issue to discuss upload peculiarities / potential problems that the research team is encountering in initial review of uploads, particularly those that don't trigger an HDX 2.0 error (yet).  These are FYI -- she will reach out directly to individual vendors if there is a VendorContact / VendorEmail in LSAReport -- but feel free to weigh in...

**Comment by JulesABrown** [comment]
Project files with multiple rows of the same Project ID are causing a "server processing error."

**Comment by JulesABrown** [comment]
Geography files with the CoC code (or some other value instead of the HUD-assigned 6-digit) geocode are causing a "server processing error."

**Comment by thomas-powers** [comment]
Not sure if this is the correct location for this, but here goes.

I have one CoC that is getting Stat is missing errors from LSAExit and LSAHousehold. So, I search through my SQL and find the problem, though I'm not sure how to resolve it.

As you know, the tmp_Exit.Stat uses the tmp_Exit.StatEnrollmentID to populate it. So I look at the StatEnrollmentID query and compare to the sample code and we are looking good. So I run the SELECT portion of the UPDATE statement and I find my problem.

select hx.ExitDate, lhh.FirstEntry, (lhh.FirstEntry + INTERVAL '730 days') FEntry730 from Enrollment_csv prior inner join tmp_Household lhh on prior.PersonalId = lhh.HoHID and prior.RelationshiptoHoH::INT = 1 inner join Exit_csv hx on hx.EnrollmentID = prior.EnrollmentID and hx.ExitDate::DATE > prior.EntryDate::DATE;

  exitdate  |     firstentry |      fentry730
------------+------------+---------------------
 2015-12-31 | 2016-09-19 | 2018-09-19 00:00:00

Notice that exitdate is NOT between firstentry and fentry730 (firstentry + 730 days). In other words, this CoC has NO results that meet the criteria so StatEnrollmentID never gets set to anything, so Stat never gets set to anything, so it throws an error in upload.

How can I remedy this? Thanks!

**Comment by JulesABrown** [comment]
For PITCount in Project.csv—we only allow nulls and numbers, not the words “n/a” for PITCount

**Comment by JulesABrown** [comment]
Long dash in Grant ID in the Funder.csv file. A double Hyphen will pass.

**Comment by JulesABrown** [comment]
Data quality problem with LSACalculated. The bed inventory script cannot run if there are rows in LSACalculated that are identical other than the Value field, with multiple rows having different values. Data integrity as we understand it requires that the fields other than Value in LSACalculated create a unique key, with one value per key.

**Comment by thomas-powers** [comment]
I am getting 0's in the following areas on the results page, but I have no idea which table | variables represent the calculations for these:

8. "Households experiencing homelessness for the first time this reporting period"	shows 0 in all categories.
9. "Households that re-engaged in the homeless system after a previous temporary or unknown destination" shows 0 in all categories.
10. "Households that returned to homelessness this reporting period after a previous permanent housing placement" shows 0 in all categories.
Table: Summary Exit Outcomes for Households Served in Temporary Situations during the Report Period

11. "Households served in ES,SH,TH or RRH that exited to permanent housing destinations" shows 0 in all categories.
12. "Households served in ES,SH,TH or RRH that exited to temporary destinations" shows 0 in all categories.
Table: Households Served in PSH During the Report Period

20. "Of households that exited to permanent situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
21. "Of households that exited to temporary situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
22. "Of households that exited to other situations, the number that returned within 180 days
Table: Households that exited in the year beginning one year prior to the start of the report period
23. "Of households that exited to permanent situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
24. "Of households that exited to temporary situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
25. "Of households that exited to other situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
26. "Of households that exited to permanent situations, the number that returned within 365 days	0	0%	0	0%	0	0%	0	0%
27. "Of households that exited to temporary situations, the number that returned within 365 days	0	0%	0	0%	0	0%	0	0%
28. "Of households that exited to other situations, the number that returned within 365 days
Table: Households that exited in the year beginning two years prior to the start of the report period
29. "Of households that exited to permanent situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
30. "Of households that exited to temporary situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
31. "Of households that exited to other situations, the number that returned within 180 days	0	0%	0	0%	0	0%	0	0%
32. "Of households that exited to permanent situations, the number that returned within 365 days	0	0%	0	0%	0	0%	0	0%
33. "Of households that exited to temporary situations, the number that returned within 365 days	0	0%	0	0%	0	0%	0	0%
34. "Of households that exited to other situations, the number that returned within 365 days	0	0%	0	0%	0	0%	0	0%
35. "Of households that exited to permanent situations, the number that returned within 730 days	0	0%	0	0%	0	0%	0	0%
36. "Of households that exited to temporary situations, the number that returned within 730 days	0	0%	0	0%	0	0%	0	0%
37. "Of households that exited to other situations, the number that returned within 730 days
Table: Data Quality

**Comment by JulesABrown** [comment]
Thomas-
Apologies for not seeing this earlier. This file, which Meradith sent out from the HUB yesterday,
[LSASummaryData_ConditionalStatements.xlsx](https://github.com/HMIS/LSASampleCode/files/2695408/LSASummaryData_ConditionalStatements.xlsx)
 should help you identify the source for all of those values in the LSAHousehold and LSAExit files. Let me know via this thread or by directly emailing (julia_brown@abtassoc.com) if you have further questions.
