### ISSUE TITLE
** 6.17 - missing closing parentheses in the sample code **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#570]
After update on `9/24/2020`, there is an issue with missing closing parentheses in the sample code in each 6.17 sub-section
![image-20200929-103920](https://user-images.githubusercontent.com/20728145/94613607-a9db5280-0259-11eb-86b6-5e7ab595dc0a.png)

**Comment by MollyMcEvilley** [comment]
Thanks!  Commit forthcoming.
