### ISSUE TITLE
Flags 674, 675, 676: LSAReport and LSAPerson

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#571]
Hi,
**Flag 674** - LSAReport: UnduplicatedClient1 count more than LSAPerson: Total Clients
**Flag 675** - LSAReport: UnduplicatedAdult1 count more than LSAPerson: Total Adults (according to the AdultEST, AdultRRH, and AdultPSH fields)
**Flag 676** - LSAReport: DOB1 count more than LSAPerson: Total People with Unknown Ages

I believe all 3 Flags are caused by the same underlaying issue in the dataset and not in the code: 
- Step 3.3 creates tlsa_HHID by selecting records from hmis_Enrollment, but due to a hohCheck, it excludes all HouseholdID's with multiple RelationsShipToHoH=1
- Step 3.4 creates tlsa_Enrollment by selecting records from tlsa_HHID 
- Step 5.3/5.4 creates tlsa_Person by selecting the active recs from tlsa_Enrollment (which excludes those enrollments from households with RelationshipToHoH issues.

When Step 9.1 creates dq_Enrollment by selecting records from hmis_Enrollment, there is NO CHECK for HouseholdID's with multiple RelationsShipToHoH=1.

This means when Step 9.2 counts UnduplicatedClient1, the count includes these enrollments from households with RelationshipToHoH issues; thus making the count more than the count of clients in lsa_Person (which looks at tlsa_Person which excludes these enrollments).   

Since Step 9.2 has to calculate NotOneHoH1 and NotOneHoH3 so we have to include the enrollments with RelationshipToHoH issues.  If I understand this correctly, these Flags will be removed once the dataset is fixed and these 2 fields both equal 0.

Thanks!

**Comment by MollyMcEvilley** [comment]
This is an error in the flags.  The logic used for DQ counts is explicitly different from the logic associated with others.

The flags are mistakenly comparing **UnduplicatedAdult1** to values in **AdultEST**, **AdultRRH**, and **AdultPSH** -- the latter 3 columns are limited to adults in the AHAR universe; **UnduplicatedAdult1** is not.

**Comment by AzimShivji-Abt** [comment]
No, the error is in the Adult variables. They are not supposed to be limited to the AHAR universe.

**Comment by michelleogburn** [comment]
@MollyMcEvilley and @cwanska 

We are seeing the same flag, 674, but think it is a validation issue. The following is from our developer outlining her thoughts on the problem.

### Spec
**Logic for LSAPerson**

- Step 3.3 creates `tlsa_HHID` by selecting records from `hmis_Enrollment` using restriction for `HoHsExit.ExitDate > Enrollment.EntryDate` Sample of code uses this restriction too.
- Step 3.4 creates `tlsa_Enrollment` by selecting records from `tlsa_HHID` using restriction for `clientsExit.ExitDate > Enrollment.EntryDate`. Sample of code uses this restriction too.
- Step 5.3/5.4 creates `tlsa_Person` by selecting the active recs from `tlsa_Enrollment`

**As a result,** `tlsa_Person` **has data depends on clients with** `Exit.ExitDate > Enrollment.EntryDate`
![image-20201020-150429](https://user-images.githubusercontent.com/20728145/97476588-cc6d9380-190b-11eb-8019-ea4f5f86d8c6.png)

![397707ee-e516-468f-8429-f474a5bb9980](https://user-images.githubusercontent.com/20728145/97476704-f7f07e00-190b-11eb-915f-4fcfc1ad49f3.png)

### Spec
**The logic for LSAReport: UnduplicatedClient1**

- Steps 9.1 creates `dq_Enrollment` by selecting records from `hmis_Enrollment` without restriction `Exit.ExitDate > Enrollment.EntryDate`
- Step 9.2 calculate `UnduplicatedClient1` using data from `dq_Enrollment`
![475a30df-83b2-4dec-a759-2e5a2e266ea6](https://user-images.githubusercontent.com/20728145/97476990-4f8ee980-190c-11eb-9b65-2ae6349233b7.png)

![4f39c72f-c72e-490d-b40b-80e624ee7efb](https://user-images.githubusercontent.com/20728145/97477212-8e24a400-190c-11eb-8a8c-248197c5264c.png)

So according to the spec and the sample code: 

**LSAPerson: Total Clients** include Clients, where `Exit.ExitDate > Enrollment.EntryDate`, so in **LSAPerson doesn't include clients** where `HoHExit.ExitDate = HoHEnrollment.EntryDate`

**LSAReport: UnduplicatedClient1** include Client with HoH, but without restriction, so **UnduplicatedClient1 includes** clients where `HoHExit.ExitDate = HoHEnrollment.EntryDate`

Previously we found the similar issue https://github.com/HMIS/LSASampleCode/issues/499 and receive answer from Molly
![785dcaa0-d6e5-46c2-9486-ec8583515489](https://user-images.githubusercontent.com/20728145/97477485-ec518700-190c-11eb-9e3c-cd666a314111.png)

So, we are 99% sure that the validation system should be fixed.

Hope this makes sense.

**Comment by AzimShivji-Abt** [comment]
No, the LSAPerson and one-year DQ universes of _people_ should be the same, as they were in 2018, and regardless of whether you count additional enrollments for those people in the DQ statistics (although we really should impose the same exit>entry condition there as well). This is a Specs and sample code error.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by cwanska** [comment]
The flags have been edited to suppress this validation for the 2019/2020 upload cycle. We will revisit the issue when updating the specs and sample code for the 2021 upload cycle.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:

    Redefined AdultEST/RRH/PSH to include all LSA adults.
    Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.

Clarified that the DQ universe for LSAReport is deliberately and necessarily broader than people included in LSAPerson.
