### ISSUE TITLE
Flag 142: LSAPerson (Upload Error)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#574]
This is related to #565 . Apologies for missing it before creating a new ticket.

> If these people were served in AO households in RRH (as you reported in HHTypeRRH), then they must have been served as adults. But you reported otherwise in the AdultRRH field for the following row of your LSAPerson file.
> 
> HHTypeRRH | 1 (AO) | AdultRRH | -1 (Not applicable)
> -- | -- | -- | --

### Spec
According to the spec (section 5.15) and sample code, AdultRRH should have `ActiveAge between 21 and 65` and all restrictions from 5.14.
![image-20200930-095407](https://user-images.githubusercontent.com/20728145/94837169-c1851900-03c8-11eb-9f62-471902e14f85.png)

Please pay attention that **MoveInDate** cannot be null. Otherwise, both **AdultRRH** and **AHARRRH** would be -1.

### Live Example
Client (HoH, adult) has individual enrollment with parameters:

- n.ProjectType = 13 
- n.EntryDate = 2/8/2018
- n.ExitDate = null 
- n.MoveInDate = null
- n.Active = 1
- n.ActiveAge = 64
- hhid.ActiveHHType = 1

The reason why this client is reported in Flag 142 is because:

- MoveInDate = null and, as a result, AdultRRH = -1
- but it is still RRH program so HHTypeRRH = hhid.ActiveHHType = 1

### Issue
Either validation system should be fixed, or both spec and sample code should include `or MoveInDate = null` option for  **AdultRRH** and **AHARRRH** and maybe some other parameters.

**Comment by cwanska** [comment]
@michelleogburn the Abt team is planning to disable the flags related to this issue. We will leave this open until testing is confirmed.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by cwanska** [comment]
The flags have been edited to suppress this validation for the 2019/2020 upload cycle. We will revisit the issue when updating the specs and sample code for the 2021 upload cycle.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:  

- Redefined AdultEST/RRH/PSH to include all LSA adults.
- Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.
