### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by k-adunn** [abtassociates/LSASampleCode#579]
1.	As per specs section 3.1 – LSAScope, “Reporting on system use and chronic homelessness uses systemwide data regardless of LSAScope”. Does this mean if I run Project level report for one project of ES type and client enrolled in that project is also enrolled in other projects of different types, the report should consider other project enrollments for the client to report System use (like SystemPath, Days, CH data)? 
2.	What is the expected value of HHType in 8.21? In the section detail it says "The counts are grouped by household type" but is followed by statement HHType is always 0.
3.	8.13 works as per July 2020 version of specs, but 8.14 Population 113 to 144 there is no criteria for HHAdultAge between 18 and 24 in specs, but the report doesn't count household if any member is above 24. Is this correct?

**Comment by MollyMcEvilley** [comment]
1.  Yes.  For a project-level LSA, clients and households (i.e., those represented in LSAPerson/LSAHousehold/LSAExit) are limited to people/households served by the ES project, but path, system engagement status, returns, CH, etc., are all based on systemwide data.
2.  Like the DQ counts in 8.19, 8.20, and LSAReport, **HHType** in 8.21 should always be 0.  Apologies for the contradictory info in the specs -- I think that was a copy/paste error on my part.  (Commit forthcoming.)
3.  In 8.14, **HHAdultAge** is not relevant for populations 113-144.  (It _is_ relevant for PopIDs145-148, so **HHAdultAge** is required in the code for section 8.14 --  but **HHAdultAge** is null for 133-144 in ref_Populations, so it isn't a factor.)
