### ISSUE TITLE
4.16 Get Dates to Include Counts of ES/SH/Street Days

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#58]
A question about how a certain situation should be handled:

In specifications:

> ch_Date -
Distinct dates between CHStart and LastActive when client was in ES/SH or on the street; also referred to as ES/SH/Street dates.

And then

> Logic
For each PersonalID in tmp_Person, any date between CHStart and LastActive is counted as an ES/SH/Street day (ch_Date) if it meets one of the sets of criteria below as compared to CH enrollments. 
...
Criteria for counting dates in ES/SH or on the Street Based on 3.917 Living Situation:
...

There is one client in sample data (PersonalID 162405):

- One enrollment in Project Type=2
- Start Date = 2014-10-30
- End Date = 2017-01-06
- Approx Date Homless = 2010-10-30
- CHStart = 2014-01-07 (last Active 2017-01-06 - 3 years)

For this client, what is correct episode to use

a) 2014-01-07 2014-10-29 296
Or
b) 2012-10-01 2014-10-29 759

**Comment by MollyMcEvilley** [comment]
Definitely a) -- only dates between CHStart and LastActive are relevant.  The commit above fixes the code in 4.16 that was counting days prior to CHStart.  Thank you!
