### ISSUE TITLE
*** Flag 337: LSAPerson (Upload Error) ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#583]
> In the LSAPerson file, veteran status should equal -1 (not applicable) for people who are not adults. The following row in your LSAPerson file violates that rule.
> 
> VetStatus | 1 (Yes) | AdultEST | -1 (Not applicable) | AdultRRH | -1 (Not applicable) | AdultPSH | -1 (Not applicable)
>|---|---|---|---|---|---|---|---|
> VetStatus | 0 (No) | AdultEST | -1 (Not applicable) | AdultRRH | -1 (Not applicable) | AdultPSH | -1 (Not applicable)

### Spec
According to the spec (section 5.15) and sample code, **AdultRRH** should have `ActiveAge between 21 and 65` and **all restrictions from 5.14**.

![image-20200930-095407 (1)](https://user-images.githubusercontent.com/20728145/95275535-94d46580-07fd-11eb-9479-c799215b0351.png)

Please pay attention that **MoveInDate** cannot be null. Otherwise, both **AdultRRH** and **AHARRRH** would be -1.

### Live Example
Client (HoH, adult) has individual enrollment with parameters:

- n.ProjectType = 13
- n.EntryDate = 2/8/2018
- n.ExitDate = null
- n.MoveInDate = null
- n.VetStatus = 1
- n.Active = 1
- n.ActiveAge = 64
- hhid.ActiveHHType = 1

The reason why this client is reported in Flag 337 is that:

- MoveInDate = null and, as a result, **AdultRRH = -1**
- but it is still RRH enrollment that has **VetStatus = 1**

### Issue
Either validation system should be fixed, or both spec and sample code should include `or MoveInDate = null` option for **AdultRRH** and **AHARRRH** and maybe some other parameters.

**Comment by cwanska** [comment]
@michelleogburn the Abt team is planning to disable the flags related to this issue. We will leave this open until testing is confirmed.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by MollyMcEvilley** [comment]
Flags are still active, but waiting for confirmation that the flag logic has been updated to reference age columns vs. Adult columns.

**Comment by michelleogburn** [comment]
Verified this issue is now resolved.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:

    Redefined AdultEST/RRH/PSH to include all LSA adults.
    Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.
