### ISSUE TITLE
4.24-4.25 HHAdultAge for tmp_Household

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#59]
So, a conflict between spec and code sample:
https://github.com/MollyMcEvilley/LSASampleCode/blob/71f4fc896329032e02f3bc4e424e8e32289441a6/LSASampleCode.sql#L1647-L1656

According to the specs:
![image-2018-11-08-16-58-37-745](https://user-images.githubusercontent.com/20728145/48334557-ee32ba80-e60f-11e8-83c6-769d5ce955b8.png)

But code like:
`select coalesce( case when t.id = 1 then 1
                      else 2 end, -1)
 from ( select null as id ) as t`
will return 2 instead of -1. The same happened with HHAdultAge
If we check provided files (LSA Upload files/ intermediates) for HoHID = 100343
activeHousehold.csv -> HHAdultAge = -1
tmpHousehold.csv -> HHAdultAge = 25

We believe this is incorrect.

**Comment by TimLawrencePCL** [comment]
I think we need to start that CASE statement with this:

    WHEN MAX(hhid.HHAdultAge) = -1 THEN -1

**Comment by MollyMcEvilley** [comment]
Thanks to both of you -- fixed.

**Comment by MollyMcEvilley** [comment]
No -- alas -- that didn't really fix it.  Reworking it now.

**Comment by MollyMcEvilley** [comment]
It's a lot more straightforward with multiple UPDATE statements instead of using CASE in a single UPDATE.

https://github.com/HMIS/LSASampleCode/blob/001943f66ad36c26158098e2fc4059914b630915/LSASampleCode.sql#L1705-L1739
