### ISSUE TITLE
8.x - "Relevant Data Source" tables are missing completely

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#590]
Each 8.x sub-section has a shema to display what tables are involved. But there is no "Relevant Data Source" table to describe what fields are use.

**Comment by MollyMcEvilley** [comment]
This isn't a change from last year, although the Relevant Data tables would be nice to add in future versions.

**Comment by JulesABrown** [comment]
Review for FY22" label is moot because we will be doing away with these sections in FY22. Removed.
