### ISSUE TITLE
4.1 - PITCount corrections for the spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#591]
![image-20200910-113803](https://user-images.githubusercontent.com/20728145/95277804-8a1ccf00-0803-11eb-9892-4a3a126f5a6e.png)

We think “n/a“ for `PITCount` should be replaced with “must be NULL“ (similar to how `ResidentialAffiliation` works now) because `PITCount` is declared as INT column so it doesn’t allow for “n/a“ text.
![image-20200910-114158](https://user-images.githubusercontent.com/20728145/95277874-b6d0e680-0803-11eb-85f6-3598a4d629ba.png)

**Comment by MollyMcEvilley** [comment]
The note here that the column value is not applicable is similar to those for other columns that the HDX should ignore, regardless of content or data type.
