### ISSUE TITLE
***6.19 Typo in logic for PSHHousedDays***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#595]
Hello @MollyMcEvilley,

I'm filling in for Michelle again.

![image](https://user-images.githubusercontent.com/6241517/95449415-5d170c00-092a-11eb-980a-a00b38dc6f7c.png)

According to sample code 
* instead of `PSHHousedDays between 366 and 180` should be `PSHHousedDays between 366 and 730`
* instead of `PSHHousedDays between 731 and 730` should be` PSHHousedDays between 731 and 109`

Also, we lost the space symbol in `PSHHousedDays between 1461and 1825`. Should be `PSHHousedDays between 1461 and 1825`

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming to correct these (and some other) typos.
