### ISSUE TITLE
*** 6.15 - "Other3917Days" calculation issue (sample code) ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#596]
"Other3917Days" is calculated in two sections:
* section 6.14
* section 6.15
It was programmed and also there is a note that `Other3917Days` can be null in the section 6.14.1.
![image](https://user-images.githubusercontent.com/6241517/95449767-d44ca000-092a-11eb-953f-a81483404695.png)

### Spec ( section 6.15 )
![image](https://user-images.githubusercontent.com/6241517/95449797-ddd60800-092a-11eb-8aab-8a9fb046c3db.png)

### Sample Code ( section 6.15 )
![image](https://user-images.githubusercontent.com/6241517/95449827-ea5a6080-092a-11eb-9afa-f111a92a21e4.png)

### Issue
`Other3917Days`  calculated for 6.14 is a “part 2” for `Other3917Days` calculation for 6.15.

If `Other3917Days` (section 6.14) = null, than `Other3917Days` (section 6.15) should be “part 1” + 0. 

Now `Other3917Days` (section 6.15) = 0 regardless “part 1” calculations because `Other3917Days` (section 6.14) = null. This scenario is not described in the spec and is a part of “Flag 517” because `TotalHomelessDays` = 0 for `Other3917Days is null`.

**Comment by michelleogburn** [comment]
@MollyMcEvilley , we need a resolution for this issue. Thank you!

**Comment by Ladvien** [comment]
Closing this issue, as it appears to be on our side.
