### ISSUE TITLE
*** 6.15 - "TotalHomelessDays" issue that causes Flag 517 ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#597]
### Spec (Issue 1)
“TotalHomelessDays” logic is completely missing in the spec (see “Logic” section).

### Sample Code
![image](https://user-images.githubusercontent.com/6241517/95450071-54730580-092b-11eb-916c-3f5606aaca1b.png)

It looks like “`when Other3917Days is null then 0`” restriction was copy/pasted from `Other3917Days`. 

This restriction causes Flag 517 issue because of values:
* TotalHomelessDays = 0
* AND SystemHomelessDays =30
but `TotalHomelessDays` is 0 regardless any data in sys_Time table because of  “`when Other3917Days is null then 0`” restriction

**Comment by michelleogburn** [comment]
@MollyMcEvilley , we need a response to this issue. Thank you!

**Comment by michelleogburn** [comment]
Hey @MollyMcEvilley , this is still causing problems.

**Comment by Ladvien** [comment]
Closing this issue, as it appears to be on our side.
