### ISSUE TITLE
6.19 - "ReturnTime" no logic in spec

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#598]
![image](https://user-images.githubusercontent.com/6241517/95450251-a451cc80-092b-11eb-9898-2b5d2bca0ae4.png)

I can’t find corresponding logic for the highlighted code in spec for 6.19. Also, I can’t find any notes about ReturnTime in 6.19

There is a similar part of the code in 7.8. **But 7.8 is not 6.19**

![image](https://user-images.githubusercontent.com/6241517/95450314-b7649c80-092b-11eb-8e79-4d41c7246ca2.png)

**Comment by MollyMcEvilley** [comment]
The logic for **ReturnTime** is defined in section 6.9.  There is no need to generate averages for this column, so it COULD be set directly.  However (as noted in the highlighted comment below) the code sets the actual days in 6.9 and groups the values in 6.19 -- same result, slightly different process. 

![image](https://user-images.githubusercontent.com/6156815/96898362-a05e9800-145d-11eb-9fdb-f964953fb281.png)
