### ISSUE TITLE
4.46 Optional System Path Calculation Clarification

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#6]
From Spec v1.2.2 4.46 
"(Optional) For first-time homeless households (Stat = 1) and households returning or re-engaging with the continuum after 15-730 days (Stat in (2,3,4)), we already know that their continuous system use is limited to the project type associated with the qualifying exit.  As such, it isn’t necessary to build a full history (as described in the next step) to determine their SystemPath – it may be set directly based on ExitFrom values using the values shown in the table below. "

The sample code does not filter by Stat, but rather filters by other conditions that i can't seem to find in the specs. Could we get some clarification on this filter as well as if the intention for this section is to filter on `stat in (1,2,3,4)`

https://github.com/MollyMcEvilley/LSASampleCode/blob/b6ca5c97bb57bba047f0e96eb6e7581a652d23ad/LSASampleCode.sql#L3014-L3031

Thanks!

**Comment by MollyMcEvilley** [comment]
In the WHERE clause, "(dateadd(dd, -1, ex.EntryDate) = ex.LastInactive)" is the equivalent of "ex.Stat in (1,2,3,4)" -- i.e., it selects households who were inactive immediately prior to the enrollment with the qualifying exits.  It's pointlessly confusing, though -- updated the code to use Stat (Line 3112 [Committed 10/15/2018](https://github.com/MollyMcEvilley/LSASampleCode/commit/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8).).
