### ISSUE TITLE
*** Flag 617: LSAPerson and LSAHousehold (Upload Error) ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#601]
@MollyMcEvilley, please confirm next columns cannot be 0 but can be -1:
* `AHARRRH`
* `AHARRRH`
* `AHARPSH`
![image](https://user-images.githubusercontent.com/6241517/95482698-06262c80-0954-11eb-84ce-c06085cf0ee9.png)
![image](https://user-images.githubusercontent.com/6241517/95482737-0f16fe00-0954-11eb-9e58-96b9f0ef9715.png)

@cwanska, it is not clear what columns are used for validation here:
1. Served as head of household (in this household type) in ES/SH/TH during the report period?
2. Served as head of household (in this household type) in the AHAR universe in ES/SH/TH during the report period?
3. Served as head of household (in this household type) in RRH during the report period?
4. Served as head of household (in this household type) in the AHAR universe in RRH during the report period?
5. Served as head of household (in this household type) in PSH during the report period?
6. Served as head of household (in this household type) in the AHAR universe in PSH during the report period?

Please update flags explanation to include exact columns with file names they belong.

@MollyMcEvilley, here is query we use find client based on flag description:
```
SELECT * 
  FROM lsa_Household
 WHERE ESTChronic = 1
   AND HHType = 1
   AND HoHEthnicity = 0
   AND HoHRace = 2
   AND ESTStatus != 0
   AND ESTAHAR = 0
   AND RRHStatus = 0
   AND RRHAHAR = 0
   AND PSHStatus = 0
   AND PSHAHAR = 0;
```
RowTotal = 1, so we can easily replace `lsa_Household` with `tlsa_Household` so see HoHID (this client has only one enrollment so it is easy to verify data).

This client is counted in LSAPerson (with additional Gender = 2 criteria)
```
SELECT * 
  FROM lsa_Person
 WHERE HHChronicEST = 1   
   AND Ethnicity = 0
   AND Race = 2   
   AND HHTypeEST = 1
   AND AHAREST = 1
   AND AHARRRH = -1
   AND AHARPSH = -1
   AND Gender = 2
```

It looks like everything is OK with data, and client is reported. So maybe there is validation rule issue? Is it possible to get list of all validation rules with their logic?

**Comment by michelleogburn** [comment]
This flag appears to have been resolved. Closing this issue.
