### ISSUE TITLE
8.7 Potential Issue in Sample Code

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#602]
![image](https://user-images.githubusercontent.com/6241517/95483209-94021780-0954-11eb-9611-e0914cbb840c.png)
According to Spec Population List should be 
![image](https://user-images.githubusercontent.com/6241517/95483236-9b292580-0954-11eb-814d-1e15e3eba094.png)

When we use condition `and pop.PopID between 0 and 4` we receive the next Population List
![image](https://user-images.githubusercontent.com/6241517/95483303-ab410500-0954-11eb-8980-ed4d286c9723.png)
Row `Veteran` should be removed from the Population List for 8.7

**Comment by MollyMcEvilley** [comment]
This is an excellent point -- and if the record highlighted above isn't excluded, the code won't limit the averages to Veteran Households... I will push out an update to the sample code for section 8.7 later today as shown in the screenshot below.  (PopType 1 is for populations based on household characteristics / PopType 3 is for populations based on personal characteristics).

![image](https://user-images.githubusercontent.com/6156815/96905121-094a0e00-1466-11eb-8f81-34a6d7034bda.png)
