### ISSUE TITLE
*** LSACalculated.csv: 63 and 64 codes are rejected ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#603]
Recently Molly fixed LSA spec & Sample code to resolve Flag 680 under #572.  But the fix is also required in the validation system.
![image](https://user-images.githubusercontent.com/6241517/95574934-7041de80-09f3-11eb-99cd-e080d2fd898d.png)

The validation system wasn’t fixed, so now LSA submission is totally rejected
![image](https://user-images.githubusercontent.com/6241517/95574948-7932b000-09f3-11eb-9d72-17b4cbd2fcf1.png)

**Comment by KAdlerCW** [comment]
We are experiencing this issue too: 
![image](https://user-images.githubusercontent.com/71895096/95908080-842a6f00-0d6a-11eb-9239-f5fb5794223a.png)

**Comment by cwanska** [comment]
Flags have been updated. Closing issue.

**Comment by cwanska** [comment]
@MollyMcEvilley I'm looking back at this now after replying to @KAdlerCW via email. Are you saying that 63 and 64 are now valid values? If so, can you please take a look at list 33 in the Data Dictionary and update that? We can then update the data dictionary used by HDX. Thanks!

**Comment by cwanska** [comment]
@MollyMcEvilley (cc @KAdlerCW ). I see this was introduced in the latest data dictionary but we haven't carried it over in HDX data dictionary. I think we had an internal miscommunication - sorry for confusion! We will update ASAP.

**Comment by KAdlerCW** [comment]
@cwanska A CaseWorthy customer is still receiving error 63 on their upload this morning. 

![image](https://user-images.githubusercontent.com/71895096/96485585-9f81f800-120a-11eb-833a-b3dbc4ae34c6.png)
