### ISSUE TITLE
*** HDX Upload - Files Rejected ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#606]
We are suddenly receiving a fatal error when uploading a file that was previously accepted. I believe something has gone wrong with the latest "improvement" to HDX. Help! Customers will start using today.

![image-20201019-133633](https://user-images.githubusercontent.com/20728145/96467260-962f6600-11df-11eb-8165-58bcaa417dba.png)

**Comment by michelleogburn** [comment]
This has now been replicated by other Bitfocus customers.

**Comment by cwanska** [comment]
@michelleogburn do you have the error report you can share? We had a couple of data dictionary inconsistencies that were causing new issues with uploads. We rolled out a new version of the data dictionary yesterday. Perhaps you can try an upload again? If you still are experiencing issues please send me the error report so I can see what is causing the upload to fail. (Print Error Report on the page)

**Comment by michelleogburn** [comment]
I haven't heard of this anymore... so closing for now. It can't be replicated.
