### ISSUE TITLE
*** Funding Source - ESG-CSV Source not accepted ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#607]
We've discovered a problem with the new ESG-CSV funding source 47. This didn't exist when we started this whole thing...

**Comment by eanders** [comment]
We are seeing this as well.

**Comment by cwanska** [comment]
We found a discrepancy between the LSA Data Dictionary and what is used for HDX directly. We are updating our version now and will update the code to use. I will come back and update as soon as this is complete - should be within a day.

**Comment by eanders** [comment]
This update fixed our issue
