### ISSUE TITLE
*** LSA Calculated file - invalid error 63 and 64 ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#608]
This is a follow-up to #603 

63 and 64 are still being flagged as an issue.

**Comment by cwanska** [comment]
@michelleogburn I am able to upload a zip with value 64 in the LSACalculated file. Can you please try again and let me know if you're still experiencing this error? I tried just now after manually changing one of the rows to value 64.

**Comment by michelleogburn** [comment]
Will advise...

**Comment by michelleogburn** [comment]
OK, looks like this has been resolved. Closing
