### ISSUE TITLE
Multiple Move-in Dates causes 9.1 to fail

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#609]
@MollyMcEvilley, we're seeing a situation where the sample code won't run, and would love some help figuring out a solution.

We believe the situation arrises because of the following scenario.

1. A parent child household moves into RRH and receives a move-in date
2. Some time later, a second parent and child are added to the household.
3. Later, the first HoH exits the enrollment and the second parent is assigned as HoH.
4. Cleanup is not done on the first HoH, leaving the household with two heads and two differing move-in dates.

We think, though please correct us if we are wrong, the only issue with the data at this point is that there are 2 heads of household for the household.  If that's the case, these should be caught in the NotOneHoH bits of 9.2.

The issue is that  9.1 returns two rows in this sub-query for each household member.
https://github.com/HMIS/LSASampleCode/blob/1352ba1708f9d80633ef5ddc44fcf44a80387ac5/9_1%20to%209_3%20LSAReport%20DQ%20and%20ReportDate.sql#L87-L100

Is there some way to preference one of the move-in dates? Or perhaps, if the enrollment contains a move-in date use that instead of the household move-in date? 

Here's one example of the data we're seeing.
![Screen Shot 2020-10-23 at 12 18 05 PM](https://user-images.githubusercontent.com/1346876/97028241-dbc69880-1529-11eb-96e4-8bb9ae7d6582.png)

**Comment by michelleogburn** [comment]
We have the same question, @MollyMcEvilley
