### ISSUE TITLE
Active_Enrollment.MostRecent issues

### ISSUE THREAD

**Issue by thomas-powers** [abtassociates/LSASampleCode#61]
Hi,

I am having an issue with the following query:

update active_Enrollment
set MostRecent =
	case when mr.EnrollmentID is null then 1
	else 0 end 
FROM active_enrollment an
left outer join (select later.PersonalID, later.EnrollmentID
		, later.EntryDate, later.HHType
		, case when later.ProjectType in (1,2,8) then 1
			else later.ProjectType end as PT
	from active_Enrollment later
	where later.RelationshipToHoH = 1
	) mr on (mr.PersonalID = an.PersonalID 
		and mr.HHType = an.HHType 
		and mr.PT = case when an.ProjectType in (1,2,8) then 1 else an.ProjectType end
		and (mr.EntryDate > an.EntryDate 
			or (mr.EntryDate = an.EntryDate and mr.EnrollmentID > an.EnrollmentID)))
AND an.RelationshipToHoH = 1;

In a particular CoC that we have, the active_Enrollment table contains around 200k records. However, when this query runs, it processes somewhere around 6 billion and takes a very long time to finish. This is obviously not intended. However, I cannot find any reference to MostRecent in the spec. Can you please tell me what this query is supposed to do? We are trying to re-write it currently and our guess is that it sets MostRecent to 1 where enrollmentid matches the distinct personalid and maximum entrydate. Is this accurate?

**Comment by MollyMcEvilley** [comment]
Deleted the SET active_Enrollment.MostRecent altogether and incorporated identification of the most recent active enrollment into the UPDATE statements for EST/RRH/PSHGeography.  You are right in noting that the specs don't reference MostRecent, so this illustrates the logic better -- and I hope it helps with the performance...
