### ISSUE TITLE
Flag 676 - LSAReport and LSAPerson client count discrepancy

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#610]
I'm unsure if this is a sample code or flag issue, but there the flag 676 asserts:

>There is a discrepancy between your LSAReport and LSAPerson data. The number of clients served during the report period with unknown ages (either missing/invalid or where the client refused to answer or did not know the DOB) differs between the two files. 

The sample result set results in the following error

|LSAReport: DOB1 |	503 |	LSAPerson:| Total People with Unknown Ages|	494
---|---|---|---|---|

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by eanders** [comment]
This is no longer in the flag file.

**Comment by MollyMcEvilley** [comment]
Note for LSA 2021:  The universe of people included in the data quality columns in LSAReport is necessarily and intentionally broader than the universe of people included in LSAPerson.  The data quality reporting is intended, among other things, to identify DQ issues that may have resulted in the exclusion of some people from LSAPerson (This is why the universe is broader; it includes records that were excluded, if any.)
- The value in LSAReport.**DOB1** should never be less than the number of people identified as missing a DOB in LSAPerson, but it's reasonable for it to be greater.  
- The comparison of  LSAReport.**UnduplicatedClient1** to the count of people in LSAPerson is totally reasonable as an HDX check -- the value of **UnduplicatedClient1** should NEVER be less than the count of people in LSAPerson -- but there are an assortment of valid reasons that the LSAReport.**UnduplicatedClient1** might be greater than the count of people in LSAPerson.  Minor discrepancies in that direction (other than the HoH issue*, which is specifically identified by the **NotOneHoH** columns) are no big deal.  Big discrepancies might be valid, but should be explained. 

*For example, households (and people in those households) with no identified head of household or more than 1 head of household are excluded from LSA reporting.  DQ reporting includes them -- we don't want to just exclude them without making it apparent to both the CoC and the analysis team that they're missing. There is no good reason for this error to occur -- most HMIS applications make it impossible -- so data that results in values > 0 for **NotOneHoH1** and **NotOneHoH3** must be fixed before LSA data are considered usable for AHAR purposes.
