### ISSUE TITLE
Flag 343 - CH time should be -1 for all non-HoH, non-adults

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#611]
I think this is probably an issue with the flag calculation because I can't see a way the code for 5.10 would generate the situation.  We're seeing 343 pop up in real data.  Is it possible the calculations for the various Adult* checks use different dates than 5.10 when calculating if someone is an adult?  

Here's what were seeing.  Tracking it down may be difficult, but if anyone has suggestions, I'd love to hear them.

| LSAPerson File | 343 | 1 | Upload Error | LSAPerson | In the LSAPerson file, CH time should equal -1 (not applicable) for people who are neither adults nor heads of household. The following row in your LSAPerson file violates that rule. | 15 | Yes | Observation Number (not counting the header row) in your LSAPerson file | 1044 | CHTime | 0 (0-269 days) | AdultEST | -1 (Not applicable) | AdultRRH | -1 (Not applicable) | AdultPSH | -1 (Not applicable) | HoHEST | -1 (Not applicable) | HoHRRH | -1 (Not applicable) | HoHPSH | -1 (Not applicable) | 
|----------------|-----|---|--------------|-----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----|-----|-------------------------------------------------------------------------|------|--------|----------------|----------|---------------------|----------|---------------------|----------|---------------------|--------|---------------------|--------|---------------------|--------|---------------------| 

We're seeing this in flags 329 - 345, this was just one example.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by MollyMcEvilley** [comment]
Flags are still active; waiting for confirmation that they have been edited to ref age columns vs. Adult columns.

**Comment by cwanska** [comment]
The flags have been updated for this year.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:

    Redefined AdultEST/RRH/PSH to include all LSA adults.
    Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.
