### ISSUE TITLE
HDX2.0 reflects LSAPerson and LSAExit errors on new code from yesterday

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#613]
We implemented the changes to the code from 10/29/2020 and produced LSA results that exactly matched the new sample outputs with the 10/29 dates. However, when we uploaded to HDX2.0 the upload failed because of  errors these spots:
LSAPerson> many fields related to HH
LSAExit> fields related to System Path
[module.upload-errors (1).pdf](https://github.com/HMIS/LSASampleCode/files/5466158/module.upload-errors.1.pdf)

**Comment by KAdlerCW** [comment]
CaseWorthy is experiencing this issue as well on test uploads that were previously accepted. (the ProjectCoC error is one we can resolve). 
[module.upload-errors(4).pdf](https://github.com/HMIS/LSASampleCode/files/5466591/module.upload-errors.4.pdf)

**Comment by cwanska** [comment]
@MichelleNevius @KAdlerCW  - our developer turned the flags back on in Testing that have been disabled up until now while the team finalized the SAS program. I'm checking today to confirm whether these upload errors in HDX align with the SAS flag output or whether this needs further review. Will check back within an hour or 2.

**Comment by cwanska** [comment]
> @MichelleNevius @KAdlerCW - our developer turned the flags back on in Testing that have been disabled up until now while the team finalized the SAS program. I'm checking today to confirm whether these upload errors in HDX align with the SAS flag output or whether this needs further review. Will check back within an hour or 2.

I did some testing and observed that the errors showing up in the HDX error report are consistent with what we are seeing in the flag output and I'm also seeing evidence of the data errors within sample output file. @MollyMcEvilley, can you help me understand why these data errors are being generated in the output?

**Comment by MollyMcEvilley** [comment]
Hi Cicely... These are related to flags we discussed yesterday.  

- LSAExit flags (see issue #600) that flag **SystemPath** on the basis of values in **ExitFrom** and **Stat** will all need to be reviewed/updated.
- Any flags that compare values in LSAPerson.**AdultEST/RRH/PSH** (issues #583, #611, #571, #574, and others) to anything else will need to be reviewed/updated.

**Comment by MichelleNevius** [comment]
Update from Foothold: We again took our system's LSA results that exactly matched the sample outputs with the 10/29 dates and uploaded to HDX2.0 , this time with no errors. So, I would say this can be closed if there are no objections.

**Comment by MollyMcEvilley** [comment]
FY2021 specs / LSAPerson issue:

-     Redefined AdultEST/RRH/PSH to include all LSA adults.
-     Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.

LSAExit issue:
-     It is possible that a SystemPath might include multiple project types under these circumstances... flags will be updated.
