### ISSUE TITLE
Flag 693 - Possible Population Issue?

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#614]
We are seeing Flag 693 pop up and something doesn't seem right.

![image](https://user-images.githubusercontent.com/44415627/97925240-aa6a7b80-1d26-11eb-901b-7441d11b0584.png)

After looking into it report row 55 (subpopulation of PopIDs 113,117,124) allow a value to be set due to their being a NULL in the HHAdultAge field.  
Report row 53, PopID = 9, does not contain any NULLS in the ref_Population for HHAdultAge.

Therefore when this join condition in 8.10 happens, the records get dropped where as it gets a pass in 8.14.
AND (hhid.HHAdultAge = pop.HHAdultAge OR pop.HHAdultAge IS NULL)

So my research leads me to believe that something is up with the ref populations.
The one file in question has an HHAdultAge of 25 which excludes them from 8.10 (Report row 53) but allows them in 8.14 (Report row 55).

Any insight to this would be greatly appreciated.
Thank you.

**Comment by MollyMcEvilley** [comment]
Hi... could you paste the full text of the descriptions in a comment or expand the cells in your screenshot?  I can't figure out the specifics of what this is referencing.

ETA:  no further info needed!  Cicely pulled the flag file and it looks like this flag is as a result of a difference between the specs logic and the flag logic that we can follow up on.

**Comment by cwanska** [comment]
The team has marked this flag for internal review.

**Comment by jbloescw** [comment]
![image](https://user-images.githubusercontent.com/44415627/98276911-4b8e4780-1f5c-11eb-91d4-7ad70cd44ea0.png)

**Comment by jbloescw** [comment]
Here is a view of the contents of the ref populations.  You can see how the PopIDs 113,117,124 will allow the record to join even though the HHAdultAge of the record is 25 (because the join lets it through on the join in row 643, "pop.HHAdultAge is null".

Section 8.10, Population 9, does not have any nulls in HHAdultAge so this record is now excluded and causing the mismatch as seen on the flag file.

![image](https://user-images.githubusercontent.com/44415627/98286074-0de3eb80-1f69-11eb-9e74-e36f758b7093.png)

Hopefully that clears up what I'm looking at.  
Thanks.

**Comment by cwanska** [comment]
Flag has been edited for 2019/2020 to address this issue. The spec will be revisited for 2021.

**Comment by MollyMcEvilley** [comment]
Specs section 9.4 includes criteria for HHAdultAge when counting Parenting Youth 18-24 and not just that the parent is between 18 and 24.
