### ISSUE TITLE
Flag 778 (and related) - Possible code issue in section 8.15

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#615]
We are getting counts of days averaging higher than the possible days in the year.  This seems to be coming in at section 8.15 for this case, the rrhpsh but most likely also for the est.
The specs state that the date must be report start and end but the code for those left joins does not enforce this if there is an exit date present.  This allows for more dates to sneak into the averages.
![image](https://user-images.githubusercontent.com/44415627/98033071-8f594380-1dda-11eb-8c28-b0c32ea893d6.png)

![image](https://user-images.githubusercontent.com/44415627/98033507-3dfd8400-1ddb-11eb-8c15-f8d58923145c.png)

If I am misunderstanding something please let me know but from what I can tell, the ExitDate inside the coalesce statement needs to be inspected to see if the ExitDate is after the report end and make the adjustments necessary.

**Comment by MollyMcEvilley** [comment]
The sample code uses n as an alias for tlsa_Enrollment.  As populated by the sample code, tlsa_Enrollment.**ExitDate** will be null if the exit date in HMIS is after the report end -- so this _shouldn't_ have an impact on the output.  Any chance that you have exit (and/or move-in) dates in your source table that fall after **ReportEnd**?

**Comment by jbloescw** [comment]
Got it resolved on our side of things.  Thank you.
