### ISSUE TITLE
Disabled Error Code List

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#617]
We're receiving Errors/Warnings files from many communities with requests to clarify why there are Errors/Warnings for particular items.  We're still guessing in our responses about which flags have been or will be disabled.  It's very frustrating.  @cwanska, any chance you could give us the authoritative list of which codes will be disabled in the HDX so that communities know what error codes are safely ignored?

**Comment by cwanska** [comment]
@eanders Elliot, the flag files that were uploaded to Production for communities take into account any flags that have been suppressed. So, if the communities are asking about an error in the flag file it's definitely still being considered a valid and active flag. We are working on getting the full list of flags posted on GitHub, hopefully this week. I have been told that isolating only flags that are suppressed, and therefore no longer a part of that universe might be much harder for the team to pull together.

**Comment by eanders** [comment]
@cwanska, I believe these files were generated before the flags were suppressed as they included flags like 538, which should fall into the same category as 533, which you noted would be suppressed here: https://github.com/HMIS/LSASampleCode/issues/600.

Additionally it contains 674, which you noted would be suppressed here: https://github.com/HMIS/LSASampleCode/issues/571

**Comment by cwanska** [comment]
@eanders I was referring to any flags that have been shared with communities. Those flag files were run after the flags were suppressed. You are correct that we are still waiting for updated vendor flag files on Testing. I have reached out to the Analyst team to try to get an ETA on those since I expected them on Friday.

**Comment by eanders** [comment]
@cwanska, we're getting production errors/warnings files back from our communities that contain these and similar flags.  These were probably uploaded on 10/30 to meet the first deadline.  They're looking to us for support because the flags are showing up under the Vendor tab, but we can't give them a reasonable answer because we don't know which flags will be suppressed for the next round or not, and I believe the guidance has been for them _not_ to re-upload.

**Comment by cwanska** [comment]
@eanders I appreciate your patience while I'm trying to troubleshoot this! Based on internal conversations, I don't think the flag files were run prior to the flags being suppressed. So, it would be very helpful to take a look at the flag file you're referencing to see if we can better understand the disconnect. Do you happen to have a CoC# or an upload # you can share with me so I can pull down the flag file? Alternatively you can email it to me. It would be super helpful for troubleshooting. Thanks!

**Comment by cwanska** [comment]
@eanders the team will continue to review flags for validity so please continue to post ones that you think are generated in error. For flag 538, one of the analysts reviewed and said although it looks very similar to 533, it's different. It’s triggered when someone exits from RRH but their system path does not include RRH (and is not “not applicable”) and they feel it's a valid error. I'll take a look at the files you sent over and confirm whether any and all flags we agreed to suppress have in fact been suppressed. Thanks!

**Comment by eanders** [comment]
Thanks @cwanska.  538 was set for review here: https://github.com/HMIS/LSASampleCode/issues/613#issuecomment-722487469.

**Comment by eanders** [comment]
@MollyMcEvilley, can you confirm that 538 is a sample code bug?
>The SystemPath field in LSAExit must include RRH or be equal to all other combinations or not applicable (i.e., any of the following SystemPath values: -1, 4, 5, 6, 7, 10, 11, 12) if the household exited from RRH (as reported in the ExitFrom field). The following row in your LSAExit file violates that rule.

If it's not, it should be moved to the "Flags - CoC" tab, though I'm unclear how the CoC could clear it up.  In this case, we're seeing SystemPath **8 (PSH only)** with an ExitFrom **7 (RRH without placement in PH)** where Stat is **1 (Engage with continuum for first time or after at least 730 days inactive)** or Stat is **4 (Re-engage 15-730 days after exit to unknown destination)** or Stat is **5 (Continuously engaged)**
