### ISSUE TITLE
4.35 - condition checking that the Date inserted is after LastInactive

### ISSUE THREAD

**Issue by ericwilka** [abtassociates/LSASampleCode#62]
Hello,

In 4.35 the specs segment out the calculation for Other3917 day for prior to LastInactive and on or after LastInactive.  In the sample code the DateDiff stops counting at LastInactive, but in the insert into sys_Time, there aren't any conditions to check if the Date is on or after LastInactive.  Should this be a condition that is added?

**Comment by MollyMcEvilley** [comment]
No!  (Woohoo!)  Days between DateToStreetESSH and the associated EntryDate from 3.917 that are before LastInactive can be counted in Other3917Days as long as the period of time is contiguous with the client's period of activity (i.e., there is a record in sys_Time for the HoH where sysDate = EntryDate).  

![image](https://user-images.githubusercontent.com/6156815/48743412-04a0cd80-ec31-11e8-9ab1-6704a9694be3.png)

**Comment by ericwilka** [comment]
If I'm understanding correctly, I don't think we're looking at the same section.  I was thinking more about a scenario when we're counting Days for sysStatus = 7 that are already counted in the DATEDIFF part.  (assuming only a single enrollment) If the DateToStreet is 9/28/17, Project Entry Date of 10/2/17 that would put the LastInactive Date to 10/1/17.  

Looking at the sample code, it would first count the DATEDIFF between 9/28/17 and 10/1/17; then in the insert into sysTime, I think it would count those same days again as in the section:
inner join ref_Calendar cal on cal.theDate >= hn.DateToStreetESSH
	and cal.theDate < hn.EntryDate
There's no check that theDate is after LastInactive.  Should there be a condition for that?
