### ISSUE TITLE
Flag ID 757 - Flag calculation issue coming from 8.18 and 8.17

### ISSUE THREAD

**Issue by KAdlerCW** [abtassociates/LSASampleCode#620]
We are receiving Flag ID 757 in our data set, below is one sample of this flag:
![image](https://user-images.githubusercontent.com/71895096/99580581-9de45500-29ad-11eb-9a41-505e6af8e79b.png)
 
We think the flag is being caused by HDX joining LSA Calculated to LSA_Project in the calculation for Data Flag 1 and the lack of an inner join to LSA_Project in section 8.18.
 
To find the value for Data Flag Field 1, we initially ran section 8.17 against project type = 13, HHType = 0 (null) and Population = 3. This gave us a value greater than Flag Field 2. We then joined the ProjectID to LSA_Project, and got the 3614 value being output in the flag.
 
We matched the value output in Flag Data Field 2 by running section 8.18 filtered by project type (specifically project type 13 in this instance). This gives a higher value than Data Flag Field 1, as 8.18 is letting in some projects that do not meet the criteria for LSA_Project. 

The specs support adding an inner join to LSA_Project in both 8.17 and 8.18, which would resolve this flag (in addition to flag 780 and 711 noted in issue #616).

![image](https://user-images.githubusercontent.com/71895096/99586636-00415380-29b6-11eb-9888-1552af7f3eaf.png)
![image](https://user-images.githubusercontent.com/71895096/99586686-0df6d900-29b6-11eb-9e60-2b22de3dec9f.png)

**Comment by KAdlerCW** [comment]
Related to this, the specs for 8.16 have similar language as 8.18: 
![image](https://user-images.githubusercontent.com/71895096/99593164-3d5e1380-29bf-11eb-9467-ecda8a394422.png)

Not sure if the intention here is to say the projecttype must come from the project.csv, meaning the project must have a record in LSA_Project. The sample code is currently getting the project type from tlsa_Enrollment. If it is the intention to assign the project type value from LSA_Project, this section would need the join to LSA_project as well.

**Comment by MollyMcEvilley** [comment]
In 8.16, the sample code (appropriately) specifies that the enrollment must be active (n.**Active** = 1).  As long as there's an enrollment that meets that criteria, there _should_ be a record in lsa_Project where the type is the same as tlsa_Enrollment -- so it wouldn't matter which one is used.  

I think the primary problem in 8.17 and 8.18 is that the sample code doesn't specify that n.**Active** = 1.  I'm adding that (commit forthcoming). 

ETA:  HOWEVER, there are other reasons -- e.g. issues with PDDE data missing a ProjectCoC record -- that something might be legitimately counted in 8.16/17/18 even though there is no record for the _ProjectID_ in lsa_Project.  I don't the solution is to hide the issue by joining to lsa_Project -- which would potentially result in undercounts here.  It seems better to be able to identify the issue (via a flag) and correct it (by adding a ProjectCoC record).   Does that make sense?

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Previously you removed **n.Active = 1** from 8.17 and 8.18 under ticket #431 with the comment:

> In all (or nearly all) of the 8.x counts where the specs note that Active should = 1, it turns out to be extraneous in the code because criteria in the joins for entry/exit/bednight dates as they relate to report/cohort start and end dates are consistent with but more specific than the criteria used to set Active = 1 in section 5.2.*
I removed it from the sample code WHERE clause in 8.17 and 8.18 because it's superfluous, but for now I'm going to leave other sections alone.
*I am very lightly editing section 5.2 of the specs because it defined the logic for identification of active enrollments, but did not explicitly state that the end result should be that they are flagged with Active = 1 in tlsa_Enrollment.

As now n.Active = 1 is restored for 8.17 and 8.18, does it mean that #431 should be re-opened because there are no instructions to use Active = 1 in sections 8.17 and 8.18 is the spec?

Thank you!
