### ISSUE TITLE
Flag 484 & 486

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#623]
This issue was originally address under #578 . Seemed to have been resolved, but is back...

Scenario:
Client A (HoH) has only ES Entry-Exit project stay [5/20/2012 - null].

**LSA calculations**
1. Step 3.3.1:
tlsa_HHID.EntryDate = 5/20/2012
![image-20201117-151318](https://user-images.githubusercontent.com/20728145/99606456-abeea180-29be-11eb-959b-bd17f77df7c2.png)

2. Step 3.4.1:
tlsa_Enrollment.EntryDate = 5/20/2012
![image-20201117-151557](https://user-images.githubusercontent.com/20728145/99606525-c6287f80-29be-11eb-9f1d-0f4990849f72.png)

3. Step 6.9.1:
tlsa_Household.FirstEntry = 5/20/2012
![image-20201117-151731](https://user-images.githubusercontent.com/20728145/99606615-f3752d80-29be-11eb-9e7a-08dd44363c4e.png)

4. Step 6.12.1:
tlsa_Household.LastInactive= 9/30/2012
![image-20201117-151941](https://user-images.githubusercontent.com/20728145/99606680-1273bf80-29bf-11eb-8c5a-d89e78087baa.png)

5. Step 6.13.1:
No day is inserted in `sys_Time` table because of mandatory `hhid.EntryDate > hh.LastInactive` restriction
![image-20201117-152051](https://user-images.githubusercontent.com/20728145/99606747-3a632300-29bf-11eb-9fa2-956f764a54b8.png)

6. Step 6.15:
There is no record in `sys_Time` table for `sysStatus = 3`, so `ESDays = 0`
![image-20201117-152249](https://user-images.githubusercontent.com/20728145/99606871-71d1cf80-29bf-11eb-8a5f-3694c44ad606.png)

As a result, we get Flag 484 because:

- ESDays = 0
- THDays = 0
- ESTDays = 0
- ESTStatus = 11

NOTE: this issue also causes Flag 486

**Comment by TanyaPieterse** [comment]
Hello,
We are having the same problem... 2 clients with no Exit Date, and Entry Dates that fall before the Last Inactive Date that was set as 09/30/2012, causing no system time to be calculated:
(Step 6.12) Because First Entry < 2012-09-30, Last Inactive is set to 2012-09-30
(Step 6.13.1) And because tlsa_HHID.EntryDate does not fall > tlsa_Household.LastInactive 

![image](https://user-images.githubusercontent.com/44713006/99997571-5bdf5880-2d8b-11eb-80ec-3642e1be402a.png)

Thanks!

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming to include counts of dates for enrollments with entry dates prior to 10/1/2012 when LastInactive = 9/30/2012 and the enrollments extend beyond that date. (There was a similar issue for LSAExit, which has also been addressed.)
