### ISSUE TITLE
Flag 737 -- Possible issue with 8.16

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#625]
Good morning Molly,
Flag 737: PSH: The unduplicated total number of bed nights for people served in this project type during the current report period is less than the sum of bed nights for these people reported for AO, AC, CO, and UN (unclassifiable). We expect the sum and the unduplicated total count to be equal. If the sum is greater than the unduplicated count, that could indicate either a potential programming error or that people were not exited properly in HMIS and had erroneously overlapping enrollments (e.g., that they were enrolled in two PSH projects simultaneously and in different household types).

In code 8.16, it counts PersonalID+dates then group by HHType:
'select count (distinct n.PersonalID + cast(est.theDate as nvarchar))
		+ count (distinct n.PersonalID + cast(rrhpsh.theDate as nvarchar))
		+ count (distinct n.PersonalID + cast(bnd.theDate as nvarchar))
...

group by rpt.ReportID, pop.PopID, pop.HHType
'

Therefore, when we have a person enrolled into a PSH projects with overlap days and the HHtype is different among them, then after group by HH type, this will result the sum of HHType in (1,2,99) greater than HHtype=0. 
Please take a look and advice on this issue. Flag 758 may also of the same reason. 

Thanks very much. 

Best,
Chen

**Comment by MollyMcEvilley** [comment]
It is not possible for the sum to be less than the unduplicated count, but there are legitimate reasons for the sum to exceed the unduplicated count.

**Comment by cwanska** [comment]
The AHAR team will review approaches to mitigate this, acknowledging that there can be valid use cases for this scenario but it can also point to a data quality issue that could affect usability of data.

**Comment by cwanska** [comment]
The AHAR team acknowledges that there could be some scenarios in which this is a valid scenario, but more commonly is a data quality issue that should be fixed and therefore the flag should stay as is. Communities can add a note to address if this is a valid scenario.
