### ISSUE TITLE
Flag 538 - System path and LSAExit 

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#626]
> The SystemPath field in LSAExit must include RRH or be equal to all other combinations or not applicable (i.e., any of the following SystemPath values: -1, 4, 5, 6, 7, 10, 11, 12) if the household exited from RRH (as reported in the ExitFrom field). The following row in your LSAExit file violates that rule.

Is this a sample code issue? If not, it should probably be moved to the "Flags - CoC" tab, though I'm unclear how the CoC could clear it up. In this case, we're seeing SystemPath **8 (PSH only)** with an **ExitFrom 7 (RRH without placement in PH)** where **Stat is 1 (Engage with continuum for first time or after at least 730 days inactive)** or **Stat is 4 (Re-engage 15-730 days after exit to unknown destination)** or **Stat is 5 (Continuously engaged)**

Let me know if there's some bit of additional information I can provide to help.

**Comment by MollyMcEvilley** [comment]
Enrollments with entry dates prior to 10/1/2012 that should have been included in **SystemPath** were not... (see #628).  Commit forthcoming to address this.
