### ISSUE TITLE
Flag 964 - Seeking clarification

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#629]
Flag Description: Adult-Only households: You reported that zero people were served during the entire report period in this HMIS-participating project's beds (for this household type). Please confirm and explain.
(Inventory and LSA Calculated)

Flag Fields:
AO HHs: Total people	0	
AO HHs: Total beds active on average per night	3

I see 3 households for the AO type in the tlsa_HHID and tlsa_Enrollment.  Both tables show active as null because there is a different enrollment within the report period into a different COC.  
Technically, the inventory is accurate for those 3 HHTypes because it did happen for those folks but the enrollments never make it into the calculated due to the different COC.

Am I understanding the flag correctly?  Is there more to it here?
Is this something where the customer puts in an explanation here about there being a later CoC code in the report period?

Thank you.

**Comment by cwanska** [comment]
@jbloescw you are correct that communities should put in an explanation for this warning if a valid scenario.
