### ISSUE TITLE
Flag 1037 -- Help with explanation

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#630]
Good morning Molly and Cicely,

We have a warning flag 1037: 
'Adult-Only   households in PSH: The utilization rate for this household type and project   type is unusually high. Please confirm and explain. (And for reference, note   that we calculated utilization in two ways for this flag: The first   utilization rate is a standard measure of average people divided by average   HMIS beds. But the second version of the utilization rate adjusts the   denominator, the average HMIS beds, for any possible floating beds, in case   the actual usage of those beds by household type differed from their planned   usage'
This is one of the flags we need help with understanding with interpretation, specially each of this kind of flag has some calculated average utilization rates associated with.  Which our team can't figure out what numbers been used to get those percentage. Please help with this one. 

To be more specific: Our submitted Inventory.CSV is empty. Then, are those numbers got from LSA_Calculated. cvs?

Thanks in advance for your time and help. 

Best,
Chen

**Comment by cwanska** [comment]
@2008zjqc it would be very helpful if you could note which CoC this is for so we can research.

**Comment by 2008zjqc** [comment]
> @2008zjqc it would be very helpful if you could note which CoC this is for so we can research.

Hi Cicely, Thanks for looking into this issue. This is for OH-508, Stark County. Thanks very much.

**Comment by nataliesus** [comment]
Hi @2008zjqc ,

We do not have Flag 1037, but there are several other similar flags. I wonder how you resolved it. Could you please give us a clue? Thank you!

**Comment by 2008zjqc** [comment]
> Hi @2008zjqc ,
> 
> We do not have Flag 1037, but there are several other similar flags. I wonder how you resolved it. Could you please give us a clue? Thank you!

Good morning,
The following is the reply we got from AHAR team, it is flag specific, but the main concept should be similar. I just copy here for your reference. Jason is the one who provided us with such detailed explanation, it may not appropriate for me to put his email here, I think if you would like to  know the details regarding your flag, you may reach out Cicely to get additional explanation from AHAR team. 
For our flag 1037:
The 341.81 figure is calculated from LSACalculated.csv, using the following steps:

1.       Get value where cohort=1 & universe=15 & hhtype=1 & population=0 & reportrow=56. In this case, the value is 124,762.

2.       Divide by 365.


The 164.68 figure is calculated from LSACalculated.csv and Project.csv, using the following steps:

1.       Select project-level bed-night counts from LSACalculated.csv, by household type (where cohort=1 & universe=10 & population=0 & reportrow=56).

2.       Merge with Project.csv and restrict to tenant-based PSH projects (projecttype=3 & housingtype=3)

3.       Multiply the total number of bed-nights by the proportion of non-UN bed-nights that are AO bed-nights: ALL*AO/sum(AO,AC,CO). This is the adjusted number of bed-nights for AO households, by project.

4.       Divide by 365. Per the occupancy-based method, we are considering this to be an estimate of the average number of active beds per night, by project.

5.       Sum up the project-level averages to obtain the CoC-wide average number of active beds per night.

 last step is that the average bed count obtained through the occupancy-based method (164.68, using the steps described) is then added to the average bed count obtained through the standard method (which applies to other kinds of projects and is calculated from Inventory.csv). But since our Inventory.csv was empty, this latter average bed count was zero. 164.68 + 0 = 164.68.

Best,
Chen

**Comment by nataliesus** [comment]
Thank you very much, Chen!
