### ISSUE TITLE
Flag 757: Last-minute changes from Molly for 8.17 and 8.18 - Spec update needed

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#631]
It's like a game of wack-a-mole... but wait, there's more!!

This is related to issue #620 

Molly responded:

> In 8.16, the sample code (appropriately) specifies that the enrollment must be active (n.Active = 1). As long as there's an enrollment that meets that criteria, there should be a record in lsa_Project where the type is the same as tlsa_Enrollment -- so it wouldn't matter which one is used.
> 
> I think the primary problem in 8.17 and 8.18 is that the sample code doesn't specify that n.Active = 1. I'm adding that (commit forthcoming).

And made a commit adding n.Active = 1 in steps:

- 8.17
- 8.18.1
- 8.18.2

Previously, we created https://github.com/HMIS/LSASampleCode/issues/431 because there was n.Active = 1 for 8.17 and 8.18 in the sample code but not in the spec. So we expected the spec to be updated. Instead, Molly removed n.Active = 1 from 8.17 and 8.18 mentioning it can be also removed from the rest of 8.x sections. Here is Molly’s comment:

> In all (or nearly all) of the 8.x counts where the specs note that **Active** should = 1, it turns out to be extraneous in the code because criteria in the joins for entry/exit/bednight dates as they relate to report/cohort start and end dates are consistent with but more specific than the criteria used to set **Active** = 1 in section 5.2.*
> 
> I removed it from the sample code WHERE clause in 8.17 and 8.18 because it's superfluous, but for now I'm going to leave other sections alone.
> 
> *I am very lightly editing section 5.2 of the specs because it defined the logic for identification of active enrollments, but did not explicitly state that the end result should be that they are flagged with **Active** = 1 in tlsa_Enrollment.

Now that n.Active = 1 is restored for 8.17 and 8.18, the spec should also be updated.

**Comment by cwanska** [comment]
@MollyMcEvilley trying to get my arms around everything left and don't recall where we landed on this one. Is it a Specs issue and is it on your radar for addressing for this year or does it need a label of On Hold to address next year?

**Comment by cwanska** [comment]
This issue has been closed for the 2019/2020 collection cycle. We have labeled it with the On hold label so that we will know to go back in and review for next year.
