### ISSUE TITLE
Flag 466 - Unclear Step 6.2 Leading To LSAHousehold Error

### ISSUE THREAD

**Issue by evaripatis** [abtassociates/LSASampleCode#632]
We are receiving a flag for the LSAHousehold file stating "All of the HHAdultAge fields, describing the age groups of adult household members (HHAdultAge, ESTAdultAge, RRHAdultAge, and PSHAdultAge), must equal -1 (not applicable / no adults in household) if the household type is neither AO nor AC...."  In Step 6.2, where HHAdultAge is set for tlsaHousehold, it _does_ state that the populations, for which HHAdultAge are "relevant", have either an HHType value of 1, or 2.  This _does not_, however, indicate in any way, shape, or form, that it is _incorrect_ to populate this field with a value other than -1 for households of an HHType other than 1 and 2.  Furthermore, the sample code for this section does not specify any such conditions on HHType, it only requires that HHType from tlsaHousehold and ActiveHHType from tlsaHHID are the same.  If this error is indeed accurate, than it sounds like an update should be made, to both the specifications and the sample code, in order to reflect this requirement.

**Comment by cwanska** [comment]
@evaripatis can you please specify the flag number? This will help in troubleshooting.

**Comment by cwanska** [comment]
@evaripatis we think this is flag #466. Can you please confirm?

**Comment by evaripatis** [comment]
Apologies, yes, this is for flag 466, but not related to #466.

**Comment by cwanska** [comment]
Comment from AHAR team: 
Implicated variables are HHAdultAge, ESTAdultAge, RRHAdultAge, and PSHAdultAge. The latter three inherit the logic of HHAdultAge. A question we asked is whether these variables are applicable for a household with an “unknown” household type, even if we know there is an adult in that household. (For example, a household with one adult and another person with an unknown age.) Below are the possible values of HHAdultAge:

HHAdultAge | Not   applicable
-- | --
HHAdultAge | The   oldest adult in AO or AC household is between 18 and 21
HHAdultAge | The   oldest adult in AO or AC household is between 22 and 24
HHAdultAge | At   least one adult in AO household is 25 or older; at least one is under 55
HHAdultAge | All   adults in AO household are 55 or older

If the household type is unknown, I don’t think there’s a way to determine which category the household belongs to. It’s a variable that’s dependent on knowing the ages of all household members. So, the flag is correct that HHAdultAge should be “not applicable” if the household type is neither AO nor AC. It’s true that this isn’t made clear in section 6.2 of the specs. 
@MollyMcEvilley there is a question to youa bout whether the sample code needs to be updated.

**Comment by MollyMcEvilley** [comment]
The logic associated with **HHAdultAge** -- as applied to a single (household) enrollment -- is defined in section 5.17, and it should be set to -1 if there are any people of unknown age.
![image](https://user-images.githubusercontent.com/6156815/102543419-4951f980-4081-11eb-9a02-c099466a59e9.png)

The logic associated with **HHAdultAge** for LSAHousehold is based on the **HHAdultAge** value of all enrollments for the household (unique combination of **HoHID**/**HHType**).  For AC households (and only AC households), there could be an enrollment for the ****HoHID**/HHType** with no household members of unknown age and another enrollment that includes a household member of unknown age.  Ergo, there could be a record in LSAHousehold where **HHNoDOB** > 0 and **HHAdultAge** <> -1.    

![image](https://user-images.githubusercontent.com/6156815/102544347-a39f8a00-4082-11eb-96fc-ee7d4a77da6d.png)

**Comment by MollyMcEvilley** [comment]
@cwanska I am assigning this to both of us as a reminder to discuss in more detail.

**Comment by MollyMcEvilley** [comment]
To summarize, the valid combinations of **HHType** and **HHAdultAge** values in LSAHousehold are:
![image](https://user-images.githubusercontent.com/6156815/102784588-9f1cef00-436a-11eb-93c8-f47ebcc4d3ef.png)

@cwanska, there is a small discrepancy between the list of valid values and the note from the AHAR team, which is that **HHType** 2 (AC) and **HHAdultAge** 25 is a valid combination.

![image](https://user-images.githubusercontent.com/6156815/102785036-469a2180-436b-11eb-8f7f-d93563770d86.png)

**Comment by evaripatis** [comment]
Has this ticket been closed prematurely?  It sounded as though some type of updates were required for the specs and/or sample code, but I don't see any updates made to the github code.  Should I expect such updates to be forthcoming?

**Comment by evaripatis** [comment]
Still looking for clarification on my question from 17 days ago.

**Comment by cwanska** [comment]
@MollyMcEvilley I'm tagging you on this since you're no longer assigned. This issue has been closed and evaripatis is asking if there were further updates upcoming.
