### ISSUE TITLE
LSA FY 2019: Flag ID 718 - spec/sample code or flag problem

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#633]
@MollyMcEvilley , seems we've found another problem that is either a problem with the spec/sample code OR the flag. Here are the details.

ReportRow = 53 AND Cohort = 1 AND HHType = 0 AND Population = 3 AND ProjectID = 70 | ReportRow = 55 AND Cohort = 1 AND HHType = 0 AND Population = 3 AND ProjectID = 70
-- | --
Value = 1 | Value = 0
section 8.9 | section 8.13

It took the developer almost half a day to catch the exact scenario.

![image-20201209-152213](https://user-images.githubusercontent.com/20728145/101722870-f57f5900-3a5f-11eb-8a2f-5d00ff7db234.png)

![image-20201209-151045](https://user-images.githubusercontent.com/20728145/101722894-ff08c100-3a5f-11eb-8e0a-6ca640034b75.png)

Section 8.9:

- because of a mandatory `(n.ProjectType in (3,13) and n.MoveInDate <= cd.CohortEnd)` restriction so project stay where EnrollmentID = 160448 is excluded.
- because of `hhid.HHVet = pop.HHVet`, PersonalID=29622 (EnrollmentID=25193) is counted for ReportRow = 53.

Section 8.13:

- because of a mandatory `(n.ProjectType in (3,13) and n.MoveInDate <= cd.CohortEnd)` restriction so project stay where EnrollmentID = 160448 is excluded.
- because of `lp.VetStatus = pop.VetStatus`, PersonalID=29622 (EnrollmentID=25193) is also excluded.

as a result, nobody is counted for ReportRow = 55.

**Comment by nataliesus** [comment]
@MollyMcEvilley , flag 719 is similar to flag 718. Please advise.

**Comment by michelleogburn** [comment]
@cwanska , this flag was reported by NE-502.

**Comment by MollyMcEvilley** [comment]
The LSA data here is valid & AHAR liaisons should be aware (Cicely is coordinating this) / help communities understand scenarios where this might occur.
