### ISSUE TITLE
9.2 NotOneHoH1/3 - different tables are used in sample code and spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#634]
This is a follow-up to #576 

This issue was closed but to be consisted with the sample code, spec should be updated to use dq_Enrollment (i.e. SSNNotProvided and other also use dq_Enrollment).
![image-20201207-122402](https://user-images.githubusercontent.com/20728145/101723269-cb7a6680-3a60-11eb-8b3c-c0423bb215d7.png)

**Comment by MollyMcEvilley** [comment]
Commit forthcoming!
![image](https://user-images.githubusercontent.com/6156815/102536547-c24c5380-4077-11eb-9f43-a22c9e017037.png)
