### ISSUE TITLE
Section 7.7 - spec need corrections

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#641]
In issue #626 and #628  @MollyMcEvilley fixed flags 538 and 539... but forgot to fix the specs
![image-20201207-105357](https://user-images.githubusercontent.com/20728145/101724844-501ab400-3a64-11eb-8b9d-e8c6002cde43.png)

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/102534603-08ec7e80-4075-11eb-86d4-a7d3b86b9235.png)
