### ISSUE TITLE
Section 6.14 - question related to changes made for section 6.13

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#642]
In issue #623 , @MollyMcEvilley removed `hhid.EntryDate > hh.LastInactive` restriction for sections:

- 6.13.1
- 6.13.2
- 6.13.3

But there are the same restrictions in section 6.14.1 and 6.14.2:
![image-20201207-114439](https://user-images.githubusercontent.com/20728145/101725020-a851b600-3a64-11eb-946c-8ca875759e1a.png)

We would like to confirm we should keep `hhid.EntryDate > hh.LastInactive` in 6.14.1 and 6.14.2 regardless of the recent update for 6.13.

**Comment by MollyMcEvilley** [comment]
Yes, this is intentional -- **Other3917Days** are only counted for enrollments after **LastInactive**.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,
If this ticket is closed, then why it appears here - https://github.com/HMIS/LSASampleCode/projects/1#card-51438457 - as "To Do"?
![image](https://user-images.githubusercontent.com/28144855/102594317-b36cac00-411e-11eb-9790-55763771b466.png)
