### ISSUE TITLE
Flag 674 still active

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#643]
Hi @cwanska,

In issue #571, you noted that flag ID **674** would be suppressed for this round of submissions.  I believe it was adjusted and now checks that `LSAReport: UnduplicatedClient1` >= `LSAPerson: Total Clients`.  We're now seeing situations where `LSAReport: UnduplicatedClient1` < `LSAPerson: Total Clients`.  I'm sure I'm missing something in my reading of the spec, but LSAPerson Total Clients is the distinct count of all Clients, whereas LSAReport UnduplicatedClient1 is the count of clients in one year.

Any help in tracking down why this might be happening would be very helpful.

**Comment by jessejorstad** [comment]
I believe that LSAReport: UnduplicatedClient1 >= LSAPerson:Total Clients is true. LSAReport is not limited (as LSAPerson is) to those last served in ReportCoC -see page 40 of the specs (first line of the page) vs page 145 (under Value, 3rd bullet). Additionally, LSAPerson:Total Clients is limited to the reporting period, per page 39. And, as you noted, UnduplicateClient1 is limited to the one year period. 
@MollyMcEvilley can you confirm this?

**Comment by MollyMcEvilley** [comment]
LSAReport: **UnduplicatedClient1** should always be greater than or equal to LSAPerson.(sum of **RowTotal**) for any upload that would be submitted to HUD -- i.e.,  where the report period is one year or less. 

(I'm not sure I understand the original issue here -- is the sample code generating files where UnduplicatedClient1 < the sum of RowTotal in LSAPerson?)

**Comment by eanders** [comment]
Yes, we're seeing **674** which I believe tracks back to `UnduplicatedClient1 < the sum of RowTotal in LSAPerson`

**Comment by MollyMcEvilley** [comment]
I can't reproduce this with test data and can't find anything in the code that would cause this...  @eanders if you could try executing this on the intermediate tables for a data set that gets this flag, it could help to track down people/enrollments being excluded from the DQ queries -- which might lead to some clue about why... 
```
if (select sum(RowTotal) from lsa_Person) > (select UnduplicatedClient1 from lsa_Report)
begin
	select 'There are more people in LSAPerson (' +
		cast((select sum(RowTotal) from lsa_Person) as varchar) + ') than there are in LSAReport.UnduplicatedClient1 (' +
		cast((select UnduplicatedClient1 from lsa_Report) as varchar) + '). Active PersonalIDs and EnrollmentIDs not included in dq_Enrollment are shown below.'

	select *  
	from tlsa_Person lp
	where lp.PersonalID not in
		(select distinct PersonalID from dq_Enrollment where Status1 is not null)

	select * 
	from tlsa_Enrollment n
	where n.Active = 1 
		and n.EnrollmentID not in 
			(select distinct EnrollmentID from dq_Enrollment where Status1 is not null)

end
else
begin
	select 'No problem here.'
end
```

**Comment by eanders** [comment]
@MollyMcEvilley , sorry for the delay
```
There are more people in LSAPerson (5692) than there are in LSAReport.UnduplicatedClient1 (3831). Active PersonalIDs and EnrollmentIDs not included in dq_Enrollment are shown below.
```

The two tables contain 3,087 and 1,871 rows.

**Comment by eanders** [comment]
@MollyMcEvilley , in a data set that didn't have the 674 flag previously, I'm getting similar results where `(select sum(RowTotal) from lsa_Person) > (select UnduplicatedClient1 from lsa_Report)` is returning true.

-- CORRECTION --
We hadn't been seeing this previously in the CoC but the most recent flag file for TX-601 now includes 674.

**Comment by eanders** [comment]
@MollyMcEvilley , thanks for your help (and code) in tracking this down.  We're testing a theory now, which is that we have some cases where EnrollmentCoC.HouseholdID does not match Enrollment.HouseholdID.  That's the only scenario we could come up with where something would be left out of dq_Enrollments but included in tlsa_Enrollments.

**Comment by eanders** [comment]
Fixing the HouseholdIDs in EnrollmentCoC to match those in Enrollment has cleared this up.  Closing.
