### ISSUE TITLE
Flag 525 - Spec/Sample Code Problem

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#645]
We've discovered a new issue

### Spec (Section 7.4)
![image-20201215-141132](https://user-images.githubusercontent.com/20728145/102459665-c0907a80-3ffa-11eb-9073-dff5fe11286c.png)

### Sample Code (Section 7.4.1)
![image-20201215-141326](https://user-images.githubusercontent.com/20728145/102459744-d9992b80-3ffa-11eb-82ce-83104587b25a.png)

### Scenario
Issue appears for client who has:

- DoB = 09/27/2002 (18 years old on the current date)
- VeteranStatus = 1 (veteran question was filled after client turned 18 years old)
- On EnrollDate client was 17 years old

### Issue
Calculating `tlsa_Exit.vet`, client's age on Enroll Date is ignored. 
`EntryAge BETWEEN 18 and 65` restriction should be added for veteran question.

**Comment by MollyMcEvilley** [comment]
@michelleogburn:  There is no need to follow up on the question I asked on the call about the real life scenario>

 Given that this is an issue in LSAExit, a 17-year-old could have exited in 2017 as not-a-veteran, turned 18, joined the military for a couple of years, and then returned to the system as a veteran.  I am going to update the code as you suggested -- commit forthcoming.

**Comment by michelleogburn** [comment]
For what it's worth, this was for El Paso, TX. TX-603
