### ISSUE TITLE
Incorrect number of active records in the tlsa_HHID and tlsa_Enrollment table

### ISSUE THREAD

**Issue by logicsandeep** [abtassociates/LSASampleCode#646]
Hi,
 The tlsa_HHID.csv file has an incorrect number of active records.

 For example HouseholdID = 168810 in the tlsa_HHID.csv file is not active after step "5.1" and it should be.

HouseholdID. EntryDate.             ExitDate               ReportStart Date      ReportEnd Date
    168810        2015-01-29        2018-03-07.         2018-01-10                2019-09-30

I get 1521 records after running this query which indicates there are 1521 active households. And I'm confused to see only 586 records where active = 1 in the tlsa_HHID file.

Here's the query I'm runing:
select HHID.householdid from lsa.tlsa_HHID HHID
	inner join lsa.lsa_Report rpt on rpt.ReportEnd >= hhid.EntryDate
	inner join lsa.lsa_Project p on p.ProjectID = hhid.ProjectID
	where (hhid.ExitDate is null or hhid.ExitDate >= rpt.ReportStart) 
		and (select coc.CoC_Code
			from v2020.Enrollment_coc coc
			where cast (coc.enrollmentid as varchar) = hhid.EnrollmentID
				and coc.Information_Date <= rpt.ReportEnd
				and coc.parent_id is null and deleted  = false
			order by coc.Information_Date desc limit 1) = rpt.ReportCoC

Please help me understand how can I receive only 586 active HHIDs from the above query.

**Comment by logicsandeep** [comment]
I'm talking about the tlsa_HHID.csv file within the "Sample LSA Temp Tables 2020_11_24.zip"

**Comment by MollyMcEvilley** [comment]
For a report period of October 2018-September2019:

- There are 267 records in tlsa_HHID with a NULL exit date and 319 with an exit between October 2018 and September 2019, for a total of 586.
- There are 4105 records with an exit date prior to October 1, 2018.

OH!! I think there is a transposition in the start date of your query...  There are 1,254 records with exit dates between **_January 10_**, 2018 and September 30, 2019 and 267 nulls, which matches your total of 1521.   

![image](https://user-images.githubusercontent.com/6156815/102782754-d938c180-4367-11eb-9fcc-daed91049846.png)

**Comment by logicsandeep** [comment]
Thanks, @MollyMcEvilley. I really appreciate it. Happy holidays.
