### ISSUE TITLE
Flag ID 845: Warning flag... but a couple of concerns.

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#649]
We'd like to know the formulas to confirm Flag 845. Seems this is a new flag. The AHAR team confirms “It is possible that the difference between the unduplicated and duplicated geography proportions is due mostly to this double-counting” but they still want us to take a look? 

We aren't sure how to respond. When do we know if the warning is an actual problem or not? 

It would also be helpful if this was a CoC flag rather than a Vendor flag. Seems like it is an inventory record issue... maybe. But not a reporting problem.

### Warning Text

> Adult-Child households in PSH (active in residence): There is a large difference in the unduplicated* proportion of households served in urban/suburban/rural areas, as reported in the PSHGeography field of your LSAHousehold file, and the duplicated* proportion of households served in urban/suburban/rural areas, as reported in your LSACalculated file. (* The unduplicated proportion is the simple proportion of households served in each geography type, measured across all households housed in PSH in your CoC. The duplicated proportion, however, is based on the project-level household counts from the LSACalculated file. Each PSH project has a geography type you reported. We summed those project-level counts, among all PSH projects, by geography type to compute this duplicated proportion. It is a 'duplicated' proportion because it would double-count heads of household housed in the same household type in multiple PSH projects. It is possible that the difference between the unduplicated and duplicated geography proportions is due mostly to this double-counting, but it is also possible that the geography type was misclassified in the LSAHousehold file, and that is why we are asking this question.)

AC HHs in PSH (active in residence): LSAHousehold - Percentage of households in areas where the geography type is urban | 65.45%
-- | --
AC HHs in PSH (active in residence): LSACalculated - Percentage of households in areas where the geography type you reported is urban | 53.04%
-- | --
AC HHs in PSH (active in residence): LSAHousehold - Percentage of households in areas where the geography type is suburban | 34.55%
-- | --
AC HHs in PSH (active in residence): LSACalculated - Percentage of households in areas where the geography type you reported is suburban
-- | --

**Comment by michelleogburn** [comment]
Is it possible the way the AHAR team is mapping zip codes for geography type is different from the HUD data dictionary?

**Comment by jessejorstad** [comment]
This flag is simply asking the vendor/community to confirm there are no misclassified geography types. The mapping used is available here (4th bullet point): [(https://www.hudexchange.info/resource/3824/hmis-data-dictionary/)]

**Comment by michelleogburn** [comment]
thank you. Closing this issue.
