### ISSUE TITLE
Section 4.64 Typo in the Specs (Population value 97)

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#65]
One of the tables under section 4.64. Population value 97 correctly lists the population name as “Veteran – Female” in some rows but incorrectly lists the name as “Veteran – Gender non-conforming” in other rows. Population value 100, which is not listed in this table, should instead correspond to “Veteran – Gender non-conforming”. The nature of the error leads me to believe that vendors will know that both 97 and 100 are expected to be observed in this section (which I’ll code accordingly in the validation tool), but it’s nevertheless something to fix for next year.

**Comment by tcalder** [comment]
Popid 100 is excluded in the Sample code: see

https://github.com/HMIS/LSASampleCode/commit/7696e93133af5e5c0f65e6f4752fcdf3f687d911

https://github.com/HMIS/LSASampleCode/issues/8
