### ISSUE TITLE
Flag 617 - formula should be fixed

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#651]
How the LSAPerson version of the number of heads of households was calculated | LSAPerson: This number was calculated as the sum of RowTotal in LSAPerson where HoHEST in (1,12,13,19,123,129,139,1239) & AHARHoHEST in (1,12,13,19,123,129,139,1239) & HoHRRH not in (1,12,13,19,123,129,139,1239) & AHARHoHRRH not in (1,12,13,19,123,129,139,1239) & HoHPSH not in (1,12,13,19,123,129,139,1239) & AHARHoHPSH in (1,12,13,19,123,129,139,1239) & Ethnicity=0 & Race=2 & ESTChronic in (1,12,13,19,123,129,139,1239)
-- | --

### Issue
There is no **ESTChronic** column in LSAPerson

The formula calculation should be corrected.

**Comment by jessejorstad** [comment]
Thank you for bringing this to our attention.
There is  a typo in the description, but the calculation is correct. We will fix this typo for next round.
