### ISSUE TITLE
LSA: flag 852 is caused by the issue in the Sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#655]
![image-20210118-132541](https://user-images.githubusercontent.com/20728145/105294765-4d84a180-5b6e-11eb-951e-f627b8a7b92b.png)

Exit._ExitDate_ between CohortStart and CohortEnd is missing in the sample Code.

![image-20210118-132530](https://user-images.githubusercontent.com/20728145/105295347-7147e780-5b6e-11eb-85c4-dca3cfbe8def.png)

What about the scenario where “**Exit.ExitDate > ReportEnd** _and LastBednight <= [CohortEnd – 90 days](ReportRow 60)”_  - with issue in the Sample Code “Exit.ExitDate > ReportEnd” was counted for ReportRow 61

![image-20210119-083335](https://user-images.githubusercontent.com/20728145/105296476-b8ce7380-5b6e-11eb-9118-f06a75b82c84.png)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley , @jessejorstad, @cwanska ,
Could you please take a look at this ticket? Thank you!

**Comment by kcourtneywellsky** [comment]
We traced this back to a discrepancy between the last bed night calculation in 3.3.1 versus 8.20.

The 8.20 code looks at the effective Exit Date stored in tlsa_HHID.ExitDate. The 3.3.1 code calculates the effective Exit Date as tlsa_HHID.ExitDate.

This section in the 3.3.1 code pulls in the "recorded Exit Date", but then excludes any hmis_Exit records where the Exit Date is after the Report End Date. 

"
...
left outer join hmis_Exit hx on hx.EnrollmentID = hoh.EnrollmentID
 	and hx.ExitDate <= rpt.ReportEnd 
..."

We think commenting out this "and hx.ExitDate <= rpt.ReportEnd" clause in 3.3.1 will fix the scenario where the actual Exit Date is after the Report End date for ES NBN:
"
...
left outer join hmis_Exit hx on hx.EnrollmentID = hoh.EnrollmentID
 	--and hx.ExitDate <= rpt.ReportEnd 
..."

This change will result in a more accurate calculation of the effective Exit Date, and that will result in the 8.20 code not flagging this scenario as an error.

**Comment by kcourtneywellsky** [comment]
Also, in 3.3.1, in the CASE statement where the effective Exit Date is calculated, dates are being compared that may be null, such as p.OperatingEndDate and hx.ExitDate. This could cause unexpected results.

"
    , case when p.ProjectType = 1 and p.TrackingMethod = 3 
 				and dateadd(dd, 1, bn.LastBednight) >= p.OperatingEndDate then p.OperatingEndDate
 	    when p.ProjectType = 1 and p.TrackingMethod = 3 and hx.ExitDate > dateadd(dd, 1, bn.LastBednight)
 			then dateadd(dd, 1, bn.LastBednight)
 		when p.ProjectType = 1 and p.TrackingMethod = 3 and hx.ExitDate is null 
 			and dateadd(dd, 90, bn.LastBednight) <= rpt.ReportEnd then dateadd(dd, 1, bn.LastBednight) 
 		when p.OperatingEndDate <= rpt.ReportEnd and hx.ExitDate is null then p.OperatingEndDate
 		else hx.ExitDate end
"

This should be changed to include null checks:

"
	, case when p.ProjectType = 1 and p.TrackingMethod = 3 AND p.OperatingEndDate IS NOT NULL
				and dateadd(dd, 1, bn.LastBednight) >= p.OperatingEndDate 
				then p.OperatingEndDate
	    when p.ProjectType = 1 and p.TrackingMethod = 3 and bn.ExitDate IS NOT NULL AND bn.ExitDate > dateadd(dd, 1, bn.LastBednight)
			then dateadd(dd, 1, bn.LastBednight)
		when p.ProjectType = 1 and p.TrackingMethod = 3 and hx.ExitDate is null 
			and dateadd(dd, 90, bn.LastBednight) <= rpt.ReportEnd then dateadd(dd, 1, bn.LastBednight) 
		when p.OperatingEndDate IS NOT NULL AND p.OperatingEndDate <= rpt.ReportEnd and hx.ExitDate is null then p.OperatingEndDate
		else hx.ExitDate end as ExitDate
"

**Comment by kcourtneywellsky** [comment]
If this is deemed not related to the Flag 852 issue at hand, please let me know, and I will open a separate issue regarding 3.3.1.

**Comment by MollyMcEvilley** [comment]
Update to FY2021 specs section 10.3 to include enrollments with exits after CohortEnd where the last bednight is 90 or more days before CohortEnd in ReportRow 60.
