### ISSUE TITLE
Error ID 470, Sub-ID 1 - Question

### ISSUE THREAD

**Issue by amusillamiSSG** [abtassociates/LSASampleCode#657]
Investigating this error:
Error ID 470, Sub-ID 1: There is a discrepancy between the HHAdultAge field and the ESTAdultAge, RRHAdultAge, and PSHAdultAge fields in your LSAHousehold file. Each of these fields should be determined by the priority order defined in section 6.2 of the LSA Programming Specifications, as the first value of the following list, in this order: 18 (the oldest adult is 18-21), 24 (the oldest adult is 22-24), 55 (all adults are 55+), 25 (at least one adult over 24 and at least one adult under 55), and -1 (no adults / not applicable). The value of HHAdultAge should equal the first value (based on the priority order cited here) among the ESTAdultAge, RRHAdultAge, and PSHAdultAge fields. The following row in your LSAHousehold file violates that rule.

We can't find in the specifications or the code where **"The value of HHAdultAge should equal the first value (based on the priority order cited here) among the ESTAdultAge, RRHAdultAge, and PSHAdultAge fields"** is referrenced.

We understand that there is preferential order for the values for any one of those fields, but we can't find where it states that HHAdultAge should have the preferred value across the other three age fields.

**Comment by MollyMcEvilley** [comment]
Here's where the specs require the logic referenced by the flag (section 6.8):

![image](https://user-images.githubusercontent.com/6156815/121541285-2a4f7700-c9d5-11eb-8fa6-218dd5b00fbe.png)
