### ISSUE TITLE
System performance measure report

### ISSUE THREAD

**Issue by logicsandeep** [abtassociates/LSASampleCode#658]
Hi,
Apologies I realize this may not be a good place for SPM report, but I want to see if somebody can generate a sample SPM report with the LSA test kit data and with the same date range for me to compare my report.

I need the following if possible
1) Sample SPM report with the same date range.
2) Sample code is available.

Any help on this topic will be appreciated.

**Comment by michelleogburn** [comment]
@logicsandeep , 

We can run the SPM using the LSA test data, however we wouldn't be able to give you sample code. 

Would that help? If yes, please specify which version of the test kit you want to use and report parameters to run it on. Best would be to attach the test kit here. Just to make sure we are all on the same page.

**Comment by logicsandeep** [comment]
Hi @michelleogburn ,
That would be great. I've attached the latest version of the LSA data kit data and the report parameters below.  
Report start date = 2018-10-01
Report end date = 2019-09-30
Report Coc = XX-500
[FY_2020_LSA.zip](https://github.com/HMIS/LSASampleCode/files/6025732/FY_2020_LSA.zip)

Thank you so very much for your help on this topic.

Thanks
Sandeep

**Comment by nataliesus** [comment]
Hi Sandeep,

Here it is: [hudx-223-ad_1614089531.pdf](https://github.com/HMIS/LSASampleCode/files/6029774/hudx-223-ad_1614089531.pdf)

I am pretty sure (but not 100% sure) it was for the latest LSA data kit so I am uploading your ZIP archive in our system now. The report can be generated in less than 1 min, but the upload data process takes hours :) I will let you know when it is ready and re-upload the generated PDF version of HUD SPM.

Best regards,
Natalie

**Comment by logicsandeep** [comment]
Thank you so much. This is extremely helpful.

**Comment by nataliesus** [comment]
Hi Sandeep,

Here is HUD SPM generated on data from the file you attached (values are the same as in my prev comment):
[hudx-223-ad_1614330011.pdf](https://github.com/HMIS/LSASampleCode/files/6048528/hudx-223-ad_1614330011.pdf)

Best regards,
Natalie

**Comment by logicsandeep** [comment]
Natalie,
Thank you so much for your help here. I really appreciate it.

Regards
Sandeep
