### ISSUE TITLE
tlsa_HHID.TrackingMethod - column was removed but it is still used in the spec

### ISSUE THREAD

**Issue by nataliesus** [abtassociates/LSASampleCode#661]
Hi @MollyMcEvilley ,

TrackingMethod is no longer a column in tlsa_HHID table.

But tlsa_HHID.TrackingMethod is still used in the spec:

- LSA Programming Specifications FY2021.docx
- LSA Programming Specifications FY2021 Annotated.docx

Could you please take a look?

Thank you,
Natalie

P.S. Also, TrackingMethod is no longer a column in tlsa_Enrollment table. But there is a reference in docs as well.

**Comment by kiadso** [comment]
Hi Natalie-

On line 61, it states
 
> -- Note:  Code here and elsewhere uses ProjectType = 0 when ProjectType = 1 and TrackingMethod = 0 (ES entry/exit)	
> --		  and ProjectType = 1 when ProjectType = 1 and TrackingMethod = 3

 Does that help?

**Comment by kiadso** [comment]
After discussion in the vendor meeting today, we decided to rename the column to LSAProjectType so that it wouldn't be confusing when compared to the specs where there is no ProjectType of 0. Putting this on the To-Do list so those column names can be adjusted. 
Thanks for asking this Natalie!

**Comment by MollyMcEvilley** [comment]
As noted by Genelle (kiadso) above, we're going to leave the specs alone, but have changed the column name in the temp reporting tables to LSAProjectType.
