### ISSUE TITLE
tlsa_HHID: issue with ProjectType

### ISSUE THREAD

**Issue by nataliesus** [abtassociates/LSASampleCode#662]
Hi @MollyMcEvilley ,

_TrackingMethod_ column was removed from tlsa_HHID.

There is a note in "3_2 to 3_6 HMIS Households and Enrollments.sql" that tlsa_HHID.ProjectType  should be equal to 0 if ProjectType = 1 and TrackingMethod = 3.
But there is no ProjectType =0 logic programmed.
Could you please take a look?
![image](https://user-images.githubusercontent.com/28144855/130243546-1f69d2b1-4e7f-4bd8-b3eb-f93350cede09.png)

**Comment by nataliesus** [comment]
Sorry, I overlooked you used nested query where ProjectType is adjusted.

**Comment by MollyMcEvilley** [comment]
Hi @nataliesus,
I don’t know how many times I’ve typed out the ProjectType/TrackingMethod logic to make a simple distinction between entry-exit and night-by-night over the years, but it annoys me. Every. Single. Time.  I hope the switch isn’t equally annoying to others.
