### ISSUE TITLE
NoSingleGender is not a column on hmis_Client

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#665]
This appears to be referencing a column that doesn't exist.  Should `NoSingleGender` be set as an inline calculation somewhere?  Or maybe the intention was to reference a different table?
https://github.com/HMIS/LSASampleCode/blob/a01adee154e8dd7f95000a2d2828c476d90c0fb5/05_01%20to%2005_11%20LSAPerson%20Records%20and%20Demographics.sql#L105

I believe this will appear again in 11
https://github.com/HMIS/LSASampleCode/blob/a01adee154e8dd7f95000a2d2828c476d90c0fb5/11%20LSAReport%20DQ%20and%20ReportDate.sql#L188-L203

**Comment by kiadso** [comment]
Hi Elliot! NoSingleGender is a new Data Element that HUD has set at the same level as the other options.

**Comment by eanders** [comment]
Thanks @kiadso , it appears we were not aware of the v1.1 of the 2022 CSV spec.
