### ISSUE TITLE
NativeHIPacific should be NativeHIOtherPacific to match HMIS spec

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#666]
https://github.com/HMIS/LSASampleCode/blob/a01adee154e8dd7f95000a2d2828c476d90c0fb5/05_01%20to%2005_11%20LSAPerson%20Records%20and%20Demographics.sql#L118-L124

**Comment by kiadso** [comment]
Hi Elliot! One of the changes to the HUD CSV Export specs was removing "Other" from the NativeHiOtherPacific column name, making it NativeHIPacific.
