### ISSUE TITLE
HHVet (and others) can't be null in 7.13

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#668]
I'm getting an error with this section of code:
https://github.com/HMIS/LSASampleCode/blob/a01adee154e8dd7f95000a2d2828c476d90c0fb5/07%20LSAExit.sql#L757-L784

`Cannot insert the value NULL into column 'HHVet', table 'lsa_Exit'`
(Same for `HHDisability, HHFleeingDV, HoHRace, HoHEthnicity, HHAdultAge, HHParent`)

Here's my current attempt to track down the nulls.
```
select count (distinct HoHID + cast(HHType as nvarchar))
	, Cohort, Stat, ExitFrom, ExitTo
	, case when ReturnTime between 15 and 30 then 30
		when ReturnTime between 31 and 60 then 60
		when ReturnTime between 61 and 90 then 90
		when ReturnTime between 91 and 180 then 180
		when ReturnTime between 181 and 365 then 365
		when ReturnTime between 366 and 547 then 547
		when ReturnTime between 548 and 730 then 730
		else ReturnTime end
	, HHType, HHVet, HHChronic, HHDisability, HHFleeingDV, HoHRace, HoHEthnicity
	, HHAdultAge, HHParent, AC3Plus, SystemPath, ReportID
from tlsa_Exit
group by Cohort, Stat, ExitFrom, ExitTo
	, case when ReturnTime between 15 and 30 then 30
		when ReturnTime between 31 and 60 then 60
		when ReturnTime between 61 and 90 then 90
		when ReturnTime between 91 and 180 then 180
		when ReturnTime between 181 and 365 then 365
		when ReturnTime between 366 and 547 then 547
		when ReturnTime between 548 and 730 then 730
		else ReturnTime end
	, HHType, HHVet, HHChronic, HHDisability, HHFleeingDV, HoHRace, HoHEthnicity
	, HHAdultAge, HHParent, AC3Plus, SystemPath, ReportID
```

It looks like the top row here is the culprit.  
![Screen Shot 2021-09-09 at 6 29 15 PM](https://user-images.githubusercontent.com/1346876/132770978-2d5799b4-7cb7-46da-89b5-563edad7759d.png)

**Comment by MollyMcEvilley** [comment]
Thanks — I will fix this in the sample code.

**Comment by MollyMcEvilley** [comment]
Can't reproduce this with test data. Per office hours call, Elliot will review and we will discuss in more detail in the event that this remains an issue.

**Comment by eanders** [comment]
I also can't reproduce from the sample code.  I'll close for now and re-open if we have issues with production data.
