### ISSUE TITLE
4.7 new commit - impacts 4.8 and 4.29.b

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#67]
@MollyMcEvilley with the recent changes to 4.7, we believe a change is also needed to 4.8 and 4.29.b
https://github.com/HMIS/LSASampleCode/commit/a73c01cc91b3e36838d61b9286531319b2e9ad0a

Agreed?

**Comment by MollyMcEvilley** [comment]
Agreed... also 4.40.
