### ISSUE TITLE
4.44 HHParent missing filter on household members < 18 years old

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#7]
HHParent calculation from section 4.44 appears to be missing a filter to check that the household member with Relationship to Household = 2 (Child of HoH) is younger than 18. 

https://github.com/MollyMcEvilley/LSASampleCode/blob/b6ca5c97bb57bba047f0e96eb6e7581a652d23ad/LSASampleCode.sql#L2740-L2789

From the Specs v1.2.2:

> Set HHParent = 1 if HHType is AC or CO (in (2,3)) and at least one household member under the age of 18 has a RelationshipToHoH = 2 (Child of HoH)

**Comment by MollyMcEvilley** [comment]
Corrected.  (Line 2842 [Committed 10/15/2018](https://github.com/MollyMcEvilley/LSASampleCode/commit/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8).)
