### ISSUE TITLE
4.69 and 4.71 NotOneHoH

### ISSUE THREAD

**Issue by nathanandrade74** [abtassociates/LSASampleCode#70]
I noticed that the sample code is counting distinct PersonalIDs as HoH for NotOneHoH1, but is counting distinct EnrollmentIDs as HoH for NotOneHoH3. Should these two fields be different or should they both be counting distinct PersonalIDs?

**Comment by MollyMcEvilley** [comment]
Per the specs, they should both count EnrollmentIDs.  Thanks!
