### ISSUE TITLE
LSA Failing Due to Street Outreach issue

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#72]
We have received an AAQ that cites a situation where a customer is unable to export their LSA due to a client who has no Contact associated with a Street Outreach enrollment. The user wants to know, since the Contact data element isn't relevant to the LSA, if the vendor is right to fail the export or if the customer should be able to export the report, but with potential data errors in it.

**Comment by TimLawrencePCL** [comment]
If the data is invalid, only the vendor would know if it might break the output.  Even if the data doesn't make a difference in a particular case, only the vendor and the customer can decide how to handle invalid data generally.  Report specifications describe what to do with valid data.  It's reasonable for the vendor to insist they can't process invalid input, and it's reasonable for the customer to insist the system should have only been able to produce valid input in the first place, or at least should provide feedback and some way to reconcile the data.  It's frustrating for everyone if the issue doesn't seem to matter for a particular data set and/or report, but there's no way a programming spec could address what to do in these circumstances beyond requiring valid data.

**Comment by TimLawrencePCL** [comment]
Sorry, didn't actually mean to close this (although we probably should).
