### ISSUE TITLE
4.5 Get Inventory.csv/lsa_inventory

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#73]
In prepping for HIC and reviewing LSA inventory records, we have come upon an inconsistency. 

Per the specs:

> Export **_any_** existing user-entered inventory record for every ProjectID included in Project.csv where:
> - CoCCode = ReportCoC
> - InventoryStartDate < ReportEnd
> - InventoryEndDate is NULL or >= ReportStart

Yet further along there is a note stating:

> Note: HDX 2.0 calculations will be consistent with the system logic described in the HMIS Data Dictionary for 2.7 Bed and Unit Inventory to determine:
> 
> - Year-round equivalent counts of beds and units – i.e., the number of beds available on an average night – for each project; and
> - Counts of available beds and units on four specific dates during the report period.
> 
> HDX 2.0 reporting on bed utilization will be based on these counts coupled with client and household counts in
> other files.
> For **_each distinct combination of values in ProjectID, HouseholdType, and Availability_**, the total number of beds/units available on any given date **_are from the most recent Inventory record_** where:
> 
> - InformationDate <= [Given Date]; and
> - InventoryStartDate <= [Given Date]; and
> - InventoryEndDate is null or InventoryEndDate > [Given Date].

However, in the instructions [released by HUD in October](https://www.hudexchange.info/trainings/courses/project-descriptor-data-elements-building-projects-the-correct-way-for-lsa-hic-and-pit/) (starting at 8:30 in the video) in and per the Data Dictionary,

> A project may have multiple current and historical records of inventory.

 there must be the ability to have more than one inventory record, not just the "most recent inventory record."

So, some clarification is needed here...

**Comment by JulesABrown** [comment]
In terms of producing the LSA output, the Specifications as described are accurate and the authority on what should be exported. In terms of that specific note's description of how the HDX will use the inventory, it does seem to be an erroneous description and we will work on editing that for next year.
