### ISSUE TITLE
4.34 Get Dates of Other System Use Question

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#74]
Another question on this section

In the Query

> --Emergency Shelter (Night-by-Night) (sys_Time.sysStatus = 4)
insert into sys_Time (HoHID, HHType, sysDate, sysStatus)
select distinct sn.HoHID, sn.HHType, cal.theDate, 4
from sys_Enrollment sn
inner join hmis_Services bn on bn.EnrollmentID = sn.EnrollmentID
	and bn.RecordType = 200
inner join tmp_Household lhh on lhh.HoHID = sn.HoHID and lhh.HHType = sn.HHType
inner join lsa_Report rpt on rpt.ReportEnd >= bn.DateProvided 
inner join ref_Calendar cal on cal.theDate = bn.DateProvided
left outer join sys_Time other on other.HoHID = sn.HoHID and other.HHType = sn.HHType
	and other.sysDate = cal.theDate
where (cal.theDate > lhh.LastInactive)
	and other.sysDate is null and sn.ProjectType = 1
{quote}
A condition that bn.DateProvided should be < than Enrollment ExitDate is missed (because of services on exit date shouldn't be counted). Because of sys_Enrollment probably contains Entry\Exit dates = NULL for projects with tracking method 3 we should add to this query join hmis_Enrollment table and check ExitDate there.

For Example (sysTime.csv)

|HoHID|HHType|sysDate|sysStatus|
|------ |-------- |--------- |---------|
|300515	|1	|2016-10-17 00:00:00	|4|
|300515	|1	|2016-10-18 00:00:00	|4|
|300515	|1	|2016-10-19 00:00:00	|4|
|300515	|1	|2016-10-20 00:00:00	|4|
|300515	|1	|2016-10-21 00:00:00	|4|
|300515	|1	|2016-10-22 00:00:00	|4|
|300515	|1	|2016-10-23 00:00:00   |4|
|300515	|1	|2016-10-26 00:00:00   |4|

Date 2016-10-26 for client PersonalID = 300515 should not be counted because of end date of enrollment

**Comment by michelleogburn** [comment]
And an additional question regarding Dates after report date range

On populating temporary table sysTime with dates that have sysStatus in (5,6 - RRHPSHPreMoveInDays) at sample code we also take into account dates after Report date range. Is it Ok? If no, there is no such restriction in spec, but usually, we ignore dates after the report date range. Could you please take a look?

Query:

> -- Homeless (Time prior to Move-In) in PSH or RRH (sys_Time.sysStatus = 5 or 6)
insert into sys_Time (HoHID, HHType, sysDate, sysStatus)
select distinct sn.HoHID, sn.HHType, cal.theDate
	, min (case when sn.ProjectType = 3 then 5 else 6 end)
from sys_Enrollment sn
inner join tmp_Household lhh on lhh.HoHID = sn.HoHID and lhh.HHType = sn.HHType
inner join lsa_Report rpt on rpt.ReportEnd >= sn.EntryDate
inner join ref_Calendar cal on 
	cal.theDate >= sn.EntryDate
	and cal.theDate < coalesce(sn.MoveInDate, sn.ExitDate, rpt.ReportEnd)
left outer join sys_Time other on other.HoHID = sn.HoHID and other.HHType = sn.HHType
	and other.sysDate = cal.theDate
where cal.theDate > lhh.LastInactive
	and other.sysDate is null and sn.ProjectType in (3,13)
group by sn.HoHID, sn.HHType, cal.theDate

Sample Client(https://tr-1.clarityhs.com/clients/10403/programs):
HoHID = 362463 (in HUD testKit or sysTime.csv)

**Comment by MollyMcEvilley** [comment]
On the first issue:  Added a join to hmis_Exit and check that any bed nights counted are valid for the enrollment they are associated with (not on or after ExitDate).

On the second question:  When inserting records to sys_Time, any date counted is less than the first non-null date of:
1. _sys_Enrollment.MoveInDate
2. _sys_Enrollment.ExitDate
3. ReportEnd.

That was intended to exclude dates after ReportEnd -- when records are inserted into sys_Enrollment in 4.32, ExitDate is left NULL if it is greater than ReportEnd, BUT there was no similar check in 4.32 for MoveInDate.  As in the first issue, there was also no check in 4.32 to ensure a MoveInDate is valid for the enrollment (between entry/exit).  Added both of these checks in 4.32 so only relevant dates are counted.
