### ISSUE TITLE
LSAExit.HHAdultAge can't be -1 according to LSADictionaryTables.sql

### ISSUE THREAD

**Issue by TimLawrencePCL** [abtassociates/LSASampleCode#77]
https://github.com/HMIS/LSASampleCode/blob/d45a82b82242516d58bdf8a040fb8d4e72f157f9/LSADictionaryTables.sql#L876

This line looks like it was meant to specify that HHAdultAge (column 13) in LSAExit can be -1, but instead it specifies HoHEthnicity (column 12) can be -1.   I think it should read:

insert into ref_lsaValues (FileNumber, ColumnNumber, intValue, textValue) values (4, 13,-1, 'Not applicable')

**Comment by MollyMcEvilley** [comment]
Thank you!  Fixed.
