### ISSUE TITLE
 Step 4.70

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#79]
Step 4.70:
The where clause needs to refer to exits in the 3 years prior to ReportEnd.
Currently: where x.ExitDate is null or x.ExitDate >= dateadd(yy, 3, rpt.ReportEnd)
Should be: where x.ExitDate is null or x.ExitDate >= dateadd(yy, -3, rpt.ReportEnd)

**Comment by MollyMcEvilley** [comment]
(Detailed response under issue #76 )
