### ISSUE TITLE
4.64 PopID Filter needed

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#8]
In section 4.64 of the sample code, it does not filter on PopID but rather filters on PopType = 3. 

https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L4120-L4129

However PopType 3 from the reference tables includes populationID = 100
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSAReferenceTables.sql#L438-L439

This Population is not one of the populations specified in the Specs v1.2.2
![image](https://user-images.githubusercontent.com/44095973/46966777-e8c36e00-d06b-11e8-9517-7aac6a50eebc.png)

**Comment by MollyMcEvilley** [comment]
Update to correct will be committed today...
