### ISSUE TITLE
SSNMissingOrInvalid

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#83]
SSNMissingOrInvalid appears to be setting as UnduplicatedClient3-SSNNotProvided, rather than what is intended.

**Comment by MollyMcEvilley** [comment]
I checked the code and it looks okay... Is this just for the test data?  

Two records in the test data have SSNDataQuality in (8,9) (Client doesn't know/Refused) -- those are counted as SSNNotProvided, regardless of the value in the SSN column.  None of the SSNs are valid, so everyone else should be counted as SSNMissingOrInvalid -- and the sum of those columns should equal UnduplicatedClient3.  (I set some of the SSNs in my db to valid values and the count of SSNMissingOrInvalid went down.)
