### ISSUE TITLE
4.45 Set Stat for Exit Cohort Household

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#85]
According to spec:

> For each EnrollmentID in tmp_Exit, search for the most recent previous enrollment where:
> - (ExitDate + 730 days) is >=- tmp_Exit.EntryDate 

and it is implemented in the code as:
`and dateadd(dd,730,hx.ExitDate) >= ex.EntryDate`

But in the case where _previous_ ExitDate >= tmp_Exit.EntryDate  even without +730 such joined enrollment also would be counted. So without a condition like `hx.ExitDate < ex.EntryDate` enrollments, that aren't defined as "previous", would be taken into account (with entry date between entry/exit date of enrollment from LSAExit)

Notice: there is a condition:
` hx.ExitDate < ex.ExitDate`

Sample client
Aftermath Sleet(PersonalId = 179609)
Cohort 0
Exit 11/18/2016
Counted exit EnrollmentId = 762505 (2016-06-28:2016-07-01)
Correct exit 630697 EnrollmentId = 7(2014-05-28:2015-02-20)

As a result in the query:
```
update ex
set ex.Stat = case when ex.StatEnrollmentID is null then 1
  when dateadd(dd, 15, hx.ExitDate) >= ex.EntryDate then 5
  when hx.Destination in (3,31,19,20,21,26,28,10,11,22,23) then 2
  when hx.Destination in (15,25,4,5,6,7,14,29,1,2,18,27,16,12,13) then 3
  else 4 end
from sample_code.tmp_Exit ex
left outer join test_kit.hmis_Exit hx on hx.EnrollmentID = ex.StatEnrollmentID
```

because of  hx.ExitDate >  ex.EntryDate, some records can get Stat = 5, when they really are 1,2,3,4

**Comment by MollyMcEvilley** [comment]
Updated the sample code to require that the EntryDate for the previous enrollment must be prior to the EntryDate for the qualifying exit enrollment.  This does give me a different StatEnrollmentID than you were getting, however:

![image](https://user-images.githubusercontent.com/6156815/50232979-66636d00-0380-11e9-9105-a1acc48d2909.png)
