### ISSUE TITLE
4.34 Get Dates of Other System Use (Missed client service at report end date)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#86]
Sample client, Document Expert(72773), has service date at 2017-09-30 and Active program on that date, BUT in the query

```
--Emergency Shelter (Night-by-Night) (sys_Time.sysStatus = 4)
insert into sys_Time (HoHID, HHType, sysDate, sysStatus)
select distinct sn.HoHID, sn.HHType, cal.theDate, 4
from sys_Enrollment sn
inner join hmis_Services bn on bn.EnrollmentID = sn.EnrollmentID
	and bn.RecordType = 200
inner join tmp_Household lhh on lhh.HoHID = sn.HoHID and lhh.HHType = sn.HHType
inner join lsa_Report rpt on rpt.ReportEnd >= bn.DateProvided 
left outer join hmis_Exit hx on hx.EnrollmentID = sn.EnrollmentID
	and hx.ExitDate <= rpt.ReportEnd
inner join ref_Calendar cal on cal.theDate = bn.DateProvided
left outer join sys_Time other on other.HoHID = sn.HoHID and other.HHType = sn.HHType
	and other.sysDate = cal.theDate
--CHANGE 12/4/2018 verify that bed night is valid for the enrollment/not on or after exit
where (cal.theDate > lhh.LastInactive) and cal.theDate < coalesce (hx.ExitDate, rpt.ReportEnd)
	and other.sysDate is null and sn.ProjectType = 1
```
this condition excludes the end date of the reporting period:
`cal.theDate < coalesce (hx.ExitDate, rpt.ReportEnd)`

The fix the issue, our developer suggests
`cal.theDate <= coalesce ( dateadd(dd, -1, hx.ExitDate), rpt.ReportEnd)`

**Comment by MollyMcEvilley** [comment]
Thank you!  I like your developer's fix and it will produce an accurate result... I am told that I over-use COALESCE to the point that it has a negative impact on performance, however, so I did it just a little bit differently in the sample code:  
`(cal.theDate < hx.ExitDate or (hx.ExitDate is null and cal.theDate <= rpt.ReportEnd))`
