### ISSUE TITLE
Seeing technically invalid combinations of CHTime and CHTimeStatus in test output

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#88]
Seeing these values in reports run off sample code, which are logical, but *technically* not valid.
CHTime | CHTimeStatus
-- | --
0 | 3
0 | 2
0 | -1
270 | 3
270 | 2

**Comment by MollyMcEvilley** [comment]
CHTime = 0 and CHTimeStatus = -1 is a valid combination, but the other 4 are not.  Correcting the sample code now... 

![image](https://user-images.githubusercontent.com/6156815/50228200-6316b400-0375-11e9-864b-57e6eb93672a.png)

**Comment by JulesABrown** [comment]
For the record, the updates to CH results in HDX 2.0 that will get pushed out this week accommodate all of the combinations in the original question.
