### ISSUE TITLE
lhh.StatEnrollmentID (4.29b)

### ISSUE THREAD

**Issue by thomas-powers** [abtassociates/LSASampleCode#89]
Below is my code for setting the StatEnrollmentID for tmp_Household table. I have run into issues with the line that is commented out below. IF I uncomment the line, I get 0 results every single time; but if I uncomment it, I get results and snag the first one. However, there is something off here as I never get a Stat = 1 (Households experiencing homelessness for the first time this period) if I uncomment it. If I comment it, I never get a Stat = 3 or Stat = 4 (Households that re-engaged in the homeless system after a previous temporary or unknown destination). This happens because if no result is returned for this query then StatEnrollmentID is (of course) null and therefore Stat = 1 for every entry, and vice versa when it's commented out. It always returns a value for StatEnrollmentID, even if maybe it shouldn't.

I cannot use the sample SQL verbatim, as we use Postgres 10 and not MS-SQL, so some interpretation is required. Am I doing something wrong?

Explanation: +/- INTERVAL '# days' is the same as dateadd(dd, +/- #, [field]) in MS-SQL

```
$sql = <<<SQL
update tmp_Household
set StatEnrollmentID = 
    (select prior.EnrollmentID
            from tmp_Household lhh 
            inner join Enrollment_csv prior ON prior.PersonalId = lhh.HoHID
            inner join LSAProject p ON p.ProjectID = prior.ProjectID 
            inner join Exit_csv hx on hx.EnrollmentID = prior.EnrollmentID
                and (hx.ExitDate::DATE > prior.EntryDate::DATE
                -- Thomas 11/27/2018 HUD Changes
                    or (hx.ExitDate::DATE = prior.EntryDate::DATE AND prior.MoveInDate IS NULL and p.ProjectType::INT in (3,13)))
-- Thomas 1/7/19 - If I uncomment this, I get ZERO results every time                    
--                and hx.ExitDate::DATE BETWEEN (lhh.FirstEntry - INTERVAL '730 days') AND lhh.FirstEntry
            inner join hhView on hhView.HouseholdID = prior.HouseholdID                   
                where prior.RelationshiptoHoH::INT = 1
                    and hhView.HHType = lhh.HHType 
                order by hx.ExitDate desc LIMIT 1);
SQL;
```

**Comment by thomas-powers** [comment]
Part of this issue has been resolved. However, I am now not getting Stat = 1. This occurs when StatEnrollmentID is null. I've ran it across multiple agencies and Stat never equals 1. I can't see this being expected. I'm also seeing that Stat = 2 isn't getting set. It seems the second line of the SQL case for the Stat is always true so the 3rd and 4th lines never execute. Is *this* expected behavior?

**Comment by thomas-powers** [comment]
I found the issue here. I think this is resolved. Will update when I know for sure.

**Comment by thomas-powers** [comment]
I made a few modifications and I am now getting Stat = 2. However, I do not get Stat = 1 under any circumstances, even our biggest CoC. It just seems wrong. Any help here would be appreciated as this is my last hurdle.

**Comment by MollyMcEvilley** [comment]
Hi Thomas.  

As far as I can tell, the criteria that requires that the prior exit date is in the 730 days ending on tmp_Household.EntryDate -- the one you have commented out -- is the only one that prevents a match to an active EnrollmentID.  You could prevent that by excluding any EnrollmentIDs in active_Enrollment, BUT it's also critical that the prior ExitDate is no more than 730 days prior to tmp_Household.FirstEntry.  Could you re-work the commented out bit?  I'm sorry I can't help figure out WHY it's not doing what it should, but those criteria have to be incorporated...
