### ISSUE TITLE
4.64 Has extra universe:

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#9]
https://github.com/MollyMcEvilley/LSASampleCode/blob/e0aad6fa5a5ebe1b3596f36f6d73f81ba5b59ec8/LSASampleCode.sql#L4134-L4176

This section inserts data where univers = 16. However this is not a universe to be included in the specs.

![image](https://user-images.githubusercontent.com/44095973/46966959-5ec7d500-d06c-11e8-9b66-14771adfab7a.png)

**Comment by MollyMcEvilley** [comment]
Specs updated; the combined ES/SH/TH universe was inadvertently omitted...
![image](https://user-images.githubusercontent.com/6156815/47376279-2fdede00-d6c0-11e8-8528-bdbf523f430d.png)
