### ISSUE TITLE
4.10 HHType

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#94]
This is also in reference to the data quality check error sheets coming in.

A lot of flags are saying the HHAdultAge is not appropriate for HHType 2.
It seems that 4.10 could be causing this issue.

HHType 2 should not allow Adults in the age group 25 or over but yet a lot of them are in there.
`UPDATE hhid
SET   hhid.HHAdult = (SELECT COUNT(DISTINCT an.PersonalID) FROM #active_Enrollment an WHERE an.HouseholdID = hhid.HouseholdID AND an.AgeGroup BETWEEN 18 AND 65)
    , hhid.HHChild = (SELECT COUNT(DISTINCT an.PersonalID) FROM #active_Enrollment an Where an.HouseholdID = hhid.HouseholdID AND an.AgeGroup < 18)
    , hhid.HHNoDOB = (SELECT COUNT(DISTINCT an.PersonalID) FROM #active_Enrollment an Where an.HouseholdID = hhid.HouseholdID AND an.AgeGroup IN (98,99))
FROM #active_household hhid

UPDATE hhid
SET hhid.HHType = CASE WHEN HHAdult > 0 AND HHChild > 0 THEN 2  --(2) ADULT & CHILD
				   WHEN HHNoDOB > 0 THEN 99			    --(99) UNKNOWN
				   WHEN HHAdult > 0 THEN 1			    --(1) ADULT ONLY
				   ELSE 3 END						    --(3) CHILD ONLY`
The setting of HHAdult is allowing in those between 18 and 65.  Then below in the update, is setting the HHType to 2.  Later on in 4.22 when it goes to get the HHAdultAge, the else statement is picking up someone in the 25 age group that had 3 kids because it didn't meet any of the other case when conditions.  Now we have HHType 2 with HHAdultAge of 25 and the data quality check saying that's not allowed.
I see that tmp_Household sets HHAdultAge to -1 for that group but that's not used to insert into LSA_Household it seems.

It almost seems that there needs to be an HHType for AC type households with parenting youth or a fix put in place to the HHAdultAge that is used by LSA_Household.

Please advise.

**Comment by MollyMcEvilley** [comment]
I'm seeking further info on this.  We told vendors several months ago that it would be fine to leave this alone for this year -- the specs are inconsistent and the existence of value combinations (e.g., HHType AC and HHAdultAge 25) that aren't relevant to a specific population doesn't interfere with reporting.

**Comment by eanders** [comment]
@jbloescw, thank you for documenting this.  We are also seeing the same errors.  Thanks @MollyMcEvilley for investigating.

**Comment by MollyMcEvilley** [comment]
Closing this -- flag has been removed from the HDX report -- but tagging it to resolve for v2.0.

**Comment by michelleogburn** [comment]
@jbloescw 
Was flag 134 involved with this issue? Seems like it should be, but a file just reviewed yesterday (4/17) is still showing it as a flag. @MollyMcEvilley , is 134 one of the flags that should be removed?

**Comment by michelleogburn** [comment]
@MollyMcEvilley I thought flag 186 and 187 would be removed as a result of this finding. Is that not the case? A file reviewed yesterday is still getting flagged for 186.

If not 186 and 187, which flag was removed?
