### ISSUE TITLE
Data Quality Error ID 143

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#95]
ErrorID 143 States that THDays cannot be -1 when ESTStatus shows that the person was served in ES, SH, or TH during the report period or in the contiguous period prior to the report start.

The problem seems that section 4.36 is setting THDays as follows:
`THDays = (SELECT COUNT(DISTINCT st.sysDate) FROM #sys_Time st WHERE st.sysStatus = 3 AND st.HoHID = lhh.HoHID AND st.HHType = lhh.HHType)`

But in the next section 4.37 it's setting the ESTStatus to 2 as follows:
`UPDATE lhh
SET lhh.ESTStatus = 2
FROM #tmp_Household lhh
    INNER JOIN #sys_Time st
	   ON st.HoHID = lhh.HoHID
	   AND st.HHType = lhh.HHType
WHERE lhh.ESTStatus = 0 
    AND st.sysStatus IN (3,4)`

THDays is only looking at sysStatus = 3 but section 4.37 ESTStatus = 2 is allowing sysStatus of 3 AND 4.  This is flagging folks who have an ESTStatus of 2 but only days of sysStatus 4.

Shouldn't the error be looking at ESTDays instead of THDays?  

Please advise.

**Comment by michelleogburn** [comment]
As we work through the data quality flags, @MollyMcEvilley, do you want us to post issues we find in Git Hub?

**Comment by MollyMcEvilley** [comment]
@michelleogburn If a data quality flag identifies a bug in the sample code, yes, definitely, please post it here.  I will work on fixes/updates to the code early next week.

The data quality flags are completely separate from the sample code and specs, so issues with or questions related to the flags themselves shouldn't be posted here. 

Thanks!

**Comment by eanders** [comment]
We are seeing this same issue but also with ESDays, RRHPreMoveInDays, and RRHHousedDays.

**Comment by MollyMcEvilley** [comment]
The part of the flag description in bold italics below is wrong.  If ESTStatus = 2, either (but not both) of ESDays and THDays may = -1.

> The LSAHousehold field ESDays, which reports days spent in ES or SH during the report period or in the contiguous period prior to the report start, must NOT equal -1 (not applicable) if the household was served in ES, SH, or TH during the report period _**or in the contiguous period prior to the report start**_ (as reported in ESTStatus). (If the household was only served in TH, then ESDays should equal 0.) The following row in your LSAHousehold file violates that rule.

**Comment by MollyMcEvilley** [comment]
The part of the flag description in bold italics below is wrong.  If ESTStatus = 2, either (but not both) of ESDays and THDays may = -1.

> The LSAHousehold field ESDays, which reports days spent in ES or SH during the report period or in the contiguous period prior to the report start, must NOT equal -1 (not applicable) if the household was served in ES, SH, or TH during the report period _**or in the contiguous period prior to the report start**_ (as reported in ESTStatus). (If the household was only served in TH, then ESDays should equal 0.) The following row in your LSAHousehold file violates that rule.

**Comment by nathanandrade74** [comment]
Does this error in the flag description also apply to the related error for RRHPreMoveInDays? 

> The LSAHousehold field RRHPreMoveInDays, which reports days enrolled in RRH prior to placement, must NOT equal -1 (not applicable) if the household was enrolled in RRH during the report period or in the contiguous period prior to the report start (as reported in RRHStatus). The following row in your LSAHousehold file violates that rule.

>

**Comment by MollyMcEvilley** [comment]
Yes, that flag description is also inconsistent with the specs.  If **RRHStatus** = 2, either (but not both) of **RRHPreMoveInDays** and **RRHHousedDays** may = -1.  

I don't know if there's a similar flag for **RRHPSHPreMoveInDays** when **RRHStatus** = 2, but if there is, it would also be inconsistent with the specs.

**Comment by nathanandrade74** [comment]
Thanks for the additional clarification Molly. I just have one more question about this. If you have a case where the client has an RRH enrollment that was active outside of the reporting period that does not have a Housing Move In Date, couldn't you have a situation where both RRHPreMoveInDays and RRHHousedDays both equal -1? This would be because RRHPreMoveInDays is set based only off of active_enrollments, so if the enrollment is not active during the reporting period, they would not have any pre-move-in days during the reporting period thus setting RRHPreMoveInDays = -1. Then since the enrollment was never given a Housing Move In Date they would also not have any days in housing meaning that RRHHousedDays would also equal -1. But since if this enrollment was in a contiguous period prior to the report start, RRHStatus would still be set equal to 2.

**Comment by michelleogburn** [comment]
Confirming this logic is the same for the following error flags: 141, 143, 145.

And for RRH, error flags: 166, 169
