### ISSUE TITLE
ESDays is not consistent with ESTStatus

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#98]
We are receiving data quality reports that state `ESDays = -1 and ESTStatus > 0`.  This code appears to prevent ESTStatus ever being set to 0.

https://github.com/HMIS/LSASampleCode/blob/96d68bda09295ba6b92211a5680102021f23d6a6/LSASampleCode.sql#L1795:L1801

Should the case statement have a `when an.EntryDate < rpt.ReportStart then 0`?  
The next query
https://github.com/HMIS/LSASampleCode/blob/96d68bda09295ba6b92211a5680102021f23d6a6/LSASampleCode.sql#L1804:L1814
only adds to ESTStatus if the previous values was `> 0` but the first query will never set it to zero because the coalesce doesn't get called since the min cannot return a null.

**Comment by eanders** [comment]
This appears to affect all of the coalesce statements in 4.26

**Comment by jbloescw** [comment]
Elliot, just my 2 cents here...
That first bit of code you highlighted is setting 0s for us who don't have a value that meet the select statement condition.  If that select statement finds that there was no record to match on that project type, it returns null thus being picked up by the coalesce.

I double checked by doing a select in the same manner of the update to test.  I am getting 0, 1, and 2 for results:
`Select
    hh.HoHID
    , coalesce((SELECT MIN(CASE WHEN an.ExitDate = '12/31/9999' THEN 1 ELSE 2 END) 
			FROM #active_Enrollment an
			   WHERE an.PersonalID = hh.HoHID
				   AND hh.HHType = an.HHType AND an.RelationshipToHoH = 1
			   AND an.ProjectType IN (1,2,8)), 0) as ResultFromCoalesce
FROM #tmp_Household hh`

Sorry if I'm over stepping.  There are so many of these "flags" on the report that I'm curious to see if we were experiencing the same thing you are.

**Comment by eanders** [comment]
@jbloescw thanks for the info.  We'll have to get further into our investigation to determine if we're seeing the same thing.  What you say makes sense, I missed the final `from #tmp_Household hh`.  The flag that this is triggering for us is: 

```The LSAHousehold field ESDays, which reports days spent in ES or SH during the report period or in the contiguous period prior to the report start, must NOT equal -1 (not applicable) if the household was served in ES, SH, or TH during the report period or in the contiguous period prior to the report start (as reported in ESTStatus). (If the household was only served in TH, then ESDays should equal 0.) The following row in your LSAHousehold file violates that rule.```

**Comment by jbloescw** [comment]
Yep, I caught that too.  That should be issue #95 I added.

**Comment by eanders** [comment]
This is the same issues as #95

**Comment by MollyMcEvilley** [comment]
Revise specs in sections 4.38 (table) and 4.73 consistent with section 4.37.
