### ISSUE TITLE
4.59 thru 4.64 Tracking Method in Where Clause

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#99]
We are getting a lot of QC Errors stating that LSA Calculated is showing counts of people greater than 0 in certain circumstances yet in report row 55, they are showing a zero.

It appears that sections 4.59 through 4.64 have a bugged where clause:
`p.TrackingMethod <> 3 and p.ProjectType in (1,2,8)`

The issue with this is that tracking method must be null for types 2 and 8 so project type 1 will be the only one to ever win this.  In order to allow types 2 and 8 through it will need to be adjusted slightly to allows nulls: 
`(p.TrackingMethod <> 3 or p.TrackingMethod IS NULL) and p.ProjectType in (1,2,8)`

I have a feeling this will clear up a good number of errors in the QC sheet that are LSA_Calculated related.

**Comment by eanders** [comment]
QC error codes: 10562 through 10605. 
We are seeing this same issue.  NULL is only allowed for ProjectType not equal to 1, so the fix might need to be a bit more complicated:
```
(p.TrackingMethod <> 3 ) and p.ProjectType = 1
or
(p.TrackingMethod <> 3 or p.TrackingMethod IS NULL) and p.ProjectType in (2,8)
```

**Comment by jbloescw** [comment]
I'm seeing in on these also: 25289, 25290, 25361, 10570

There seems to be more; just haven't verified yet.

**Comment by eanders** [comment]
Also 25528 - 27015

**Comment by kcourtneywellsky** [comment]
I found 16 different locations in the LSASampleCode.sql where the phrase "p.TrackingMethod <> 3" occurs. I believe all of them need to be replaced with "(p.TrackingMethod IS NULL or p.TrackingMethod <> 3)". In Section 4.7, the p.tracking method IS NULL check is already in place. Sections 4.59 through 4.64 are where most of the omissions of the null check occur. The null check is present in 4.65, 4.66, 4.67, and 4.68, but it occurs after the "p.TrackingMethod <> 3".
